/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.
 * This source file is part of the Cangjie project, licensed under Apache-2.0
 * with Runtime Library Exception.
 *
 * See https://cangjie-lang.cn/pages/LICENSE for license information.
 */

package com.huawei.excelsior.jet.compiler.llvm.bitcode

object AttributeKindCodes {
  // = 0 is unused
  val ATTR_KIND_ALIGNMENT = 1
  val ATTR_KIND_ALWAYS_INLINE = 2
  val ATTR_KIND_BY_VAL = 3
  val ATTR_KIND_INLINE_HINT = 4
  val ATTR_KIND_IN_REG = 5
  val ATTR_KIND_MIN_SIZE = 6
  val ATTR_KIND_NAKED = 7
  val ATTR_KIND_NEST = 8
  val ATTR_KIND_NO_ALIAS = 9
  val ATTR_KIND_NO_BUILTIN = 10
  val ATTR_KIND_NO_CAPTURE = 11
  val ATTR_KIND_NO_DUPLICATE = 12
  val ATTR_KIND_NO_IMPLICIT_FLOAT = 13
  val ATTR_KIND_NO_INLINE = 14
  val ATTR_KIND_NON_LAZY_BIND = 15
  val ATTR_KIND_NO_RED_ZONE = 16
  val ATTR_KIND_NO_RETURN = 17
  val ATTR_KIND_NO_UNWIND = 18
  val ATTR_KIND_OPTIMIZE_FOR_SIZE = 19
  val ATTR_KIND_READ_NONE = 20
  val ATTR_KIND_READ_ONLY = 21
  val ATTR_KIND_RETURNED = 22
  val ATTR_KIND_RETURNS_TWICE = 23
  val ATTR_KIND_S_EXT = 24
  val ATTR_KIND_STACK_ALIGNMENT = 25
  val ATTR_KIND_STACK_PROTECT = 26
  val ATTR_KIND_STACK_PROTECT_REQ = 27
  val ATTR_KIND_STACK_PROTECT_STRONG = 28
  val ATTR_KIND_STRUCT_RET = 29
  val ATTR_KIND_SANITIZE_ADDRESS = 30
  val ATTR_KIND_SANITIZE_THREAD = 31
  val ATTR_KIND_SANITIZE_MEMORY = 32
  val ATTR_KIND_UW_TABLE = 33
  val ATTR_KIND_Z_EXT = 34
  val ATTR_KIND_BUILTIN = 35
  val ATTR_KIND_COLD = 36
  val ATTR_KIND_OPTIMIZE_NONE = 37
  val ATTR_KIND_IN_ALLOCA = 38
  val ATTR_KIND_NON_NULL = 39
  val ATTR_KIND_JUMP_TABLE = 40
  val ATTR_KIND_DEREFERENCEABLE = 41
  val ATTR_KIND_DEREFERENCEABLE_OR_NULL = 42
  val ATTR_KIND_CONVERGENT = 43
  val ATTR_KIND_SAFESTACK = 44
  val ATTR_KIND_ARGMEMONLY = 45
  val ATTR_KIND_SWIFT_SELF = 46
  val ATTR_KIND_SWIFT_ERROR = 47
  val ATTR_KIND_NO_RECURSE = 48
  val ATTR_KIND_INACCESSIBLEMEM_ONLY = 49
  val ATTR_KIND_INACCESSIBLEMEM_OR_ARGMEMONLY = 50
  val ATTR_KIND_ALLOC_SIZE = 51
  val ATTR_KIND_WRITEONLY = 52
  val ATTR_KIND_SPECULATABLE = 53
  val ATTR_KIND_STRICT_FP = 54
  val ATTR_KIND_SANITIZE_HWADDRESS = 55
  val ATTR_KIND_NOCF_CHECK = 56
  val ATTR_KIND_OPT_FOR_FUZZING = 57
  val ATTR_KIND_SHADOWCALLSTACK = 58
  val ATTR_KIND_SPECULATIVE_LOAD_HARDENING = 59
  val ATTR_KIND_IMMARG = 60
  val ATTR_KIND_WILLRETURN = 61
  val ATTR_KIND_NOFREE = 62
  val ATTR_KIND_NOSYNC = 63
  val ATTR_KIND_SANITIZE_MEMTAG = 64
  val ATTR_KIND_PREALLOCATED = 65
  val ATTR_KIND_NO_MERGE = 66
  val ATTR_KIND_NULL_POINTER_IS_VALID = 67
  val ATTR_KIND_NOUNDEF = 68
  val ATTR_KIND_BYREF = 69
  val ATTR_KIND_MUSTPROGRESS = 70
  val ATTR_KIND_NO_CALLBACK = 71
  val ATTR_KIND_HOT = 72
  val ATTR_KIND_NO_PROFILE = 73
  val ATTR_KIND_VSCALE_RANGE = 74
  val ATTR_KIND_SWIFT_ASYNC = 75
  val ATTR_KIND_NO_SANITIZE_COVERAGE = 76
  val ATTR_KIND_ELEMENTTYPE = 77
}