/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.
 * This source file is part of the Cangjie project, licensed under Apache-2.0
 * with Runtime Library Exception.
 *
 * See https://cangjie-lang.cn/pages/LICENSE for license information.
 */

package com.huawei.excelsior.jet.compiler.o2lib.u

import com.huawei.excelsior.common.Arch.{AMD64, ARM64}
import com.huawei.excelsior.common.Language
import com.huawei.excelsior.common.Language.*
import com.huawei.excelsior.jet.compiler.Env.{targetArch, targetOS}
import xscala.properties.OS.LINUX

enum ClassID(_name: String, val languageOnly: Option[Language] = None) {

  // NOTE: must be first types here, as they will be loaded first and used to patch other types (e.g. scala/AnyRef)
  case JavaRefType           extends ClassID("com/huawei/excelsior/jet/runtime/lang/JavaRefType"    , Some(JAVA))
  case ScalaRefType          extends ClassID("com/huawei/excelsior/jet/runtime/lang/ScalaRefType"   , Some(SCALA))
  case CangjieRefType        extends ClassID("com/huawei/excelsior/jet/runtime/lang/CangjieRefType" , Some(CANGJIE))

  case Object                extends ClassID("java/lang/Object"              )
  case Serializable          extends ClassID("java/io/Serializable"          )
  case Cloneable             extends ClassID("java/lang/Cloneable"           , Some(JAVA))
  case Class                 extends ClassID("java/lang/Class"               , Some(JAVA))
  case Field                 extends ClassID("java/lang/reflect/Field"       , Some(JAVA))
  case JavaReference         extends ClassID("java/lang/ref/Reference"       )
  case JavaSoftReference     extends ClassID("java/lang/ref/SoftReference"   , Some(JAVA))
  case JavaWeakReference     extends ClassID("java/lang/ref/WeakReference"   , Some(JAVA))
  case Iterator              extends ClassID("java/util/Iterator"            )
  case String                extends ClassID("java/lang/String"              )
  case JavaStringBuffer      extends ClassID("java/lang/StringBuffer"        , Some(JAVA))
  case System                extends ClassID("java/lang/System"              )
  case ClassLoader           extends ClassID("java/lang/ClassLoader"         )
  case Unsafe                extends ClassID("sun/misc/Unsafe"               )
  case JavaMath              extends ClassID("java/lang/Math"                , Some(JAVA))
  case StrictMath            extends ClassID("java/lang/StrictMath"          )
  case Method                extends ClassID("java/lang/reflect/Method"      )
  case MethodHandle          extends ClassID("java/lang/invoke/MethodHandle" )
  case LambdaForm            extends ClassID("java/lang/invoke/LambdaForm"   )
  case MemberName            extends ClassID("java/lang/invoke/MemberName"   )
  case JavaStringBuilder     extends ClassID("java/lang/StringBuilder"       , Some(JAVA))
  case JavaCharSequence      extends ClassID("java/lang/CharSequence"        , Some(JAVA))
  case JavaCharset           extends ClassID("java/nio/charset/Charset"      , Some(JAVA))
  case JavaThread            extends ClassID("java/lang/Thread"              , Some(JAVA))
  case JavaAutoCloseable     extends ClassID("java/lang/AutoCloseable"       , Some(JAVA))
  case JavaCloseable         extends ClassID("java/io/Closeable"             , Some(JAVA))
  case JavaArrays            extends ClassID("java/util/Arrays"              , Some(JAVA))
  case JavaReflectArray      extends ClassID("java/lang/reflect/Array"       , Some(JAVA))
  case JavaPrintStream       extends ClassID("java/io/PrintStream"           , Some(JAVA))
  case JavaRunnable          extends ClassID("java/lang/Runnable"            , Some(JAVA))

  case JavaBoxBoolean        extends ClassID("java/lang/Boolean"             , Some(JAVA))
  case JavaBoxByte           extends ClassID("java/lang/Byte"                , Some(JAVA))
  case JavaBoxShort          extends ClassID("java/lang/Short"               , Some(JAVA))
  case JavaBoxChar           extends ClassID("java/lang/Character"           , Some(JAVA))
  case JavaBoxInteger        extends ClassID("java/lang/Integer"             , Some(JAVA))
  case JavaBoxLong           extends ClassID("java/lang/Long"                , Some(JAVA))
  case JavaBoxFloat          extends ClassID("java/lang/Float"               , Some(JAVA))
  case JavaBoxDouble         extends ClassID("java/lang/Double"              , Some(JAVA))
  case JavaBoxNumber         extends ClassID("java/lang/Number"              , Some(JAVA))
  case JavaBoxVoid           extends ClassID("java/lang/Void"                , Some(JAVA))

  case JavaThrowable                       extends ClassID("java/lang/Throwable"                       )
  case JavaException                       extends ClassID("java/lang/Exception"                       , Some(JAVA))
  case JavaError                           extends ClassID("java/lang/Error"                           , Some(JAVA))
  case JavaRuntimeException                extends ClassID("java/lang/RuntimeException"                , Some(JAVA))
  case JavaIOException                     extends ClassID("java/io/IOException"                       , Some(JAVA))
  case JavaInterruptedException            extends ClassID("java/lang/InterruptedException"            , Some(JAVA))
  case JavaGeneralSecurityException        extends ClassID("java/security/GeneralSecurityException"    , Some(JAVA))
  case JavaArrayIndexOutOfBoundsException  extends ClassID("java/lang/ArrayIndexOutOfBoundsException"  , Some(JAVA))
  case JavaArrayStoreException             extends ClassID("java/lang/ArrayStoreException"             , Some(JAVA))
  case JavaNullPointerException            extends ClassID("java/lang/NullPointerException"            , Some(JAVA))
  case JavaArithmeticException             extends ClassID("java/lang/ArithmeticException"             , Some(JAVA))
  case JavaClassCastException              extends ClassID("java/lang/ClassCastException"              , Some(JAVA))
  case JavaNegativeArraySizeException      extends ClassID("java/lang/NegativeArraySizeException"      , Some(JAVA))
  case JavaNoSuchMethodException           extends ClassID("java/lang/NoSuchMethodException"           , Some(JAVA))
  case JavaIllegalArgumentException        extends ClassID("java/lang/IllegalArgumentException"        , Some(JAVA))
  case JavaIllegalStateException           extends ClassID("java/lang/IllegalStateException"           , Some(JAVA))
  case JavaIndexOutOfBoundsException       extends ClassID("java/lang/IndexOutOfBoundsException"       , Some(JAVA))
  case JavaSecurityException               extends ClassID("java/lang/SecurityException"               , Some(JAVA))
  case JavaUnsupportedOperationException   extends ClassID("java/lang/UnsupportedOperationException"   , Some(JAVA))
  case JavaConcurrentModificationException extends ClassID("java/util/ConcurrentModificationException" , Some(JAVA))
  case JavaNoSuchElementException          extends ClassID("java/util/NoSuchElementException"          , Some(JAVA))
  case JavaLinkageError                    extends ClassID("java/lang/LinkageError"                    , Some(JAVA))
  case JavaVirtualMachineError             extends ClassID("java/lang/VirtualMachineError"             , Some(JAVA))
  case JavaAssertionError                  extends ClassID("java/lang/AssertionError"                  , Some(JAVA))
  case JavaIOError                         extends ClassID("java/io/IOError"                           , Some(JAVA))
  case JavaThreadDeath                     extends ClassID("java/lang/ThreadDeath"                     , Some(JAVA))
  case JavaIncompatibleClassChangeError    extends ClassID("java/lang/IncompatibleClassChangeError"    , Some(JAVA))
  case JavaInstantiationError              extends ClassID("java/lang/InstantiationError"              , Some(JAVA))
  case JavaStackOverflowError              extends ClassID("java/lang/StackOverflowError"              , Some(JAVA))
  case JavaOutOfMemoryError                extends ClassID("java/lang/OutOfMemoryError"                , Some(JAVA))
  case JavaInternalError                   extends ClassID("java/lang/InternalError"                   , Some(JAVA))
  case JavaNumberFormatException           extends ClassID("java/lang/NumberFormatException"           , Some(JAVA))
  case JavaNoSuchAlgorithmException        extends ClassID("java/security/NoSuchAlgorithmException"    , Some(JAVA))
  case JavaEOFException                    extends ClassID("java/io/EOFException"                      , Some(JAVA))
  case JavaFileNotFoundException           extends ClassID("java/io/FileNotFoundException"             , Some(JAVA))
  case JavaUnsupportedEncodingException    extends ClassID("java/io/UnsupportedEncodingException"      , Some(JAVA))
  case JavaStringIndexOutOfBoundsException extends ClassID("java/lang/StringIndexOutOfBoundsException" , Some(JAVA))
  case JavaUncaughtExceptionHandler        extends ClassID("java/lang/Thread$UncaughtExceptionHandler" , Some(JAVA))

  case AJObject                  extends ClassID("com/huawei/excelsior/aj/lang/AJObject"                                )
  case LockableAJObject          extends ClassID("com/huawei/excelsior/aj/lang/LockableAJObject"                        )
  case Finalizable               extends ClassID("com/huawei/excelsior/aj/lang/Finalizable"                             )
  case AJWeakRef                 extends ClassID("com/huawei/excelsior/aj/util/ref/WeakRef"                             )
  case AJRefArray                extends ClassID("com/huawei/excelsior/aj/lang/AJRefArray"                              )
  case AJByteArray               extends ClassID("com/huawei/excelsior/aj/lang/AJByteArray"                             )
  case AJBooleanArray            extends ClassID("com/huawei/excelsior/aj/lang/AJBooleanArray"                          )
  case AJCharArray               extends ClassID("com/huawei/excelsior/aj/lang/AJCharArray"                             )
  case AJShortArray              extends ClassID("com/huawei/excelsior/aj/lang/AJShortArray"                            )
  case AJIntArray                extends ClassID("com/huawei/excelsior/aj/lang/AJIntArray"                              )
  case AJLongArray               extends ClassID("com/huawei/excelsior/aj/lang/AJLongArray"                             )
  case AJFloatArray              extends ClassID("com/huawei/excelsior/aj/lang/AJFloatArray"                            )
  case AJDoubleArray             extends ClassID("com/huawei/excelsior/aj/lang/AJDoubleArray"                           )
  case CompilerInterface         extends ClassID("com/huawei/excelsior/jet/runtime/compilerinterface/CompilerInterface" )
  case KeyStrings                extends ClassID("com/huawei/excelsior/jet/runtime/javalib/java/lang/KeyStrings"        , Some(JAVA))
  case StrConcat                 extends ClassID("com/huawei/excelsior/jet/runtime/javalib/java/lang/StrConcat"         , Some(JAVA))
  case CompoundType              extends ClassID("com/huawei/excelsior/aj/lang/CompoundType"                            )
  case ThinType                  extends ClassID("com/huawei/excelsior/aj/lang/ThinType"                                )
  case PolyThinType              extends ClassID("com/huawei/excelsior/aj/lang/PolyThinType"                            )
  case ParameterPassingLocations extends ClassID("com/huawei/excelsior/aj/jetrt/ParameterPassingLocations"              )
  case AJString                  extends ClassID("com/huawei/excelsior/aj/lang/AJString"                                )
  case AJThrowable               extends ClassID("com/huawei/excelsior/aj/lang/AJThrowable"                             )
  case AJIterator                extends ClassID("com/huawei/excelsior/aj/util/AJIterator"                              )
  case Backtrace                 extends ClassID("com/huawei/excelsior/jet/runtime/excepts/stacktrace/Backtrace"        )
  case ManagedEopType            extends ClassID("com/huawei/excelsior/aj/jetrt/ManagedEopType"                         )

  case CVarArgListDesc extends ClassID(
    if (targetArch == ARM64)
      "com/huawei/excelsior/aj/util/arm64/CVarArgListDesc"
    else if (targetArch == AMD64 && targetOS == LINUX)
      "com/huawei/excelsior/aj/util/linux_amd64/CVarArgListDesc"
    else "com/huawei/excelsior/aj/util/CVarArgListDesc")

  case XScalaAnyRef            extends ClassID("xscala/AnyRef"               , Some(SCALA))
  case XScalaString            extends ClassID("xscala/String"               , Some(SCALA))
  case XScalaClass             extends ClassID("xscala/Class"                , Some(SCALA))
  case XScalaField             extends ClassID("xscala/Field"                , Some(SCALA))
  case XScalaReference         extends ClassID("xscala/ref/Reference"        , Some(SCALA))
  case XScalaSoftReference     extends ClassID("xscala/ref/SoftReference"    , Some(SCALA))
  case XScalaWeakReference     extends ClassID("xscala/ref/WeakReference"    , Some(SCALA))
  case XScalaMath              extends ClassID("xscala/Math"                 , Some(SCALA))
  case XScalaStringBuilder     extends ClassID("xscala/StringBuilder"        , Some(SCALA))
  case XScalaStringBuffer      extends ClassID("xscala/StringBuffer"         , Some(SCALA))
  case XScalaCharSequence      extends ClassID("xscala/CharSequence"         , Some(SCALA))
  case XScalaCharset           extends ClassID("xscala/text/Charset"         , Some(SCALA))
  case XScalaThread            extends ClassID("xscala/concurrency/Thread"   , Some(SCALA))
  case XScalaSystem            extends ClassID("xscala/System"               , Some(SCALA))
  case XScalaAutoCloseable     extends ClassID("xscala/AutoCloseable"        , Some(SCALA))
  case XScalaCloseable         extends ClassID("xscala/Closeable"            , Some(SCALA))
  case XScalaSerializable      extends ClassID("xscala/Serializable"         , Some(SCALA))
  case XScalaCloneable         extends ClassID("xscala/Cloneable"            , Some(SCALA))
  case XScalaArrays            extends ClassID("xscala/utils/Arrays"         , Some(SCALA))
  case XScalaReflectArray      extends ClassID("xscala/reflect/Array"        , Some(SCALA))
  case XScalaPrintStream       extends ClassID("xscala/io/PrintStream"       , Some(SCALA))
  case XScalaIOJET             extends ClassID("xscala/io/IOJET"             , Some(SCALA))
  case XScalaRunnable          extends ClassID("xscala/Runnable"             , Some(SCALA))

  case XScalaBoxBoolean        extends ClassID("xscala/boxing/BoxedBoolean"  , Some(SCALA))
  case XScalaBoxByte           extends ClassID("xscala/boxing/BoxedByte"     , Some(SCALA))
  case XScalaBoxShort          extends ClassID("xscala/boxing/BoxedShort"    , Some(SCALA))
  case XScalaBoxChar           extends ClassID("xscala/boxing/BoxedChar"     , Some(SCALA))
  case XScalaBoxInteger        extends ClassID("xscala/boxing/BoxedInt"      , Some(SCALA))
  case XScalaBoxLong           extends ClassID("xscala/boxing/BoxedLong"     , Some(SCALA))
  case XScalaBoxFloat          extends ClassID("xscala/boxing/BoxedFloat"    , Some(SCALA))
  case XScalaBoxDouble         extends ClassID("xscala/boxing/BoxedDouble"   , Some(SCALA))
  case XScalaBoxNumber         extends ClassID("xscala/boxing/Number"        , Some(SCALA))
  case XScalaBoxVoid           extends ClassID("xscala/boxing/BoxedUnit"     , Some(SCALA))

  case XScalaThrowable                       extends ClassID("xscala/exceptions/Throwable"                       , Some(SCALA))
  case XScalaException                       extends ClassID("xscala/exceptions/Exception"                       , Some(SCALA))
  case XScalaError                           extends ClassID("xscala/exceptions/Error"                           , Some(SCALA))
  case XScalaRuntimeException                extends ClassID("xscala/exceptions/RuntimeException"                , Some(SCALA))
  case XScalaIOException                     extends ClassID("xscala/exceptions/IOException"                     , Some(SCALA))
  case XScalaInterruptedException            extends ClassID("xscala/exceptions/InterruptedException"            , Some(SCALA))
  case XScalaGeneralSecurityException        extends ClassID("xscala/exceptions/GeneralSecurityException"        , Some(SCALA))
  case XScalaArrayIndexOutOfBoundsException  extends ClassID("xscala/exceptions/ArrayIndexOutOfBoundsException"  , Some(SCALA))
  case XScalaArrayStoreException             extends ClassID("xscala/exceptions/ArrayStoreException"             , Some(SCALA))
  case XScalaNullPointerException            extends ClassID("xscala/exceptions/NullPointerException"            , Some(SCALA))
  case XScalaArithmeticException             extends ClassID("xscala/exceptions/ArithmeticException"             , Some(SCALA))
  case XScalaClassCastException              extends ClassID("xscala/exceptions/ClassCastException"              , Some(SCALA))
  case XScalaNegativeArraySizeException      extends ClassID("xscala/exceptions/NegativeArraySizeException"      , Some(SCALA))
  case XScalaNoSuchMethodException           extends ClassID("xscala/exceptions/NoSuchMethodException"           , Some(SCALA))
  case XScalaIllegalArgumentException        extends ClassID("xscala/exceptions/IllegalArgumentException"        , Some(SCALA))
  case XScalaIllegalStateException           extends ClassID("xscala/exceptions/IllegalStateException"           , Some(SCALA))
  case XScalaIndexOutOfBoundsException       extends ClassID("xscala/exceptions/IndexOutOfBoundsException"       , Some(SCALA))
  case XScalaSecurityException               extends ClassID("xscala/exceptions/SecurityException"               , Some(SCALA))
  case XScalaUnsupportedOperationException   extends ClassID("xscala/exceptions/UnsupportedOperationException"   , Some(SCALA))
  case XScalaConcurrentModificationException extends ClassID("xscala/exceptions/ConcurrentModificationException" , Some(SCALA))
  case XScalaNoSuchElementException          extends ClassID("xscala/exceptions/NoSuchElementException"          , Some(SCALA))
  case XScalaLinkageError                    extends ClassID("xscala/exceptions/LinkageError"                    , Some(SCALA))
  case XScalaVirtualMachineError             extends ClassID("xscala/exceptions/VirtualMachineError"             , Some(SCALA))
  case XScalaAssertionError                  extends ClassID("xscala/exceptions/AssertionError"                  , Some(SCALA))
  case XScalaIOError                         extends ClassID("xscala/exceptions/IOError"                         , Some(SCALA))
  case XScalaThreadDeath                     extends ClassID("xscala/exceptions/ThreadDeath"                     , Some(SCALA))
  case XScalaIncompatibleClassChangeError    extends ClassID("xscala/exceptions/IncompatibleClassChangeError"    , Some(SCALA))
  case XScalaInstantiationError              extends ClassID("xscala/exceptions/InstantiationError"              , Some(SCALA))
  case XScalaStackOverflowError              extends ClassID("xscala/exceptions/StackOverflowError"              , Some(SCALA))
  case XScalaOutOfMemoryError                extends ClassID("xscala/exceptions/OutOfMemoryError"                , Some(SCALA))
  case XScalaInternalError                   extends ClassID("xscala/exceptions/InternalError"                   , Some(SCALA))
  case XScalaNumberFormatException           extends ClassID("xscala/exceptions/NumberFormatException"           , Some(SCALA))
  case XScalaNoSuchAlgorithmException        extends ClassID("xscala/exceptions/NoSuchAlgorithmException"        , Some(SCALA))
  case XScalaEOFException                    extends ClassID("xscala/exceptions/EOFException"                    , Some(SCALA))
  case XScalaFileNotFoundException           extends ClassID("xscala/exceptions/FileNotFoundException"           , Some(SCALA))
  case XScalaUnsupportedEncodingException    extends ClassID("xscala/exceptions/UnsupportedEncodingException"    , Some(SCALA))
  case XScalaStringIndexOutOfBoundsException extends ClassID("xscala/exceptions/StringIndexOutOfBoundsException" , Some(SCALA))
  case XScalaUncaughtExceptionHandler        extends ClassID("xscala/concurrency/UncaughtExceptionHandler"       , Some(SCALA))

  val name = JStringsModule.internJString(_name)
}
