/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.
 * This source file is part of the Cangjie project, licensed under Apache-2.0
 * with Runtime Library Exception.
 *
 * See https://cangjie-lang.cn/pages/LICENSE for license information.
 */

package com.huawei.excelsior.jet.compiler.o2lib.u

import com.huawei.excelsior.jet.common.XString
import com.huawei.excelsior.jet.compiler.Env.targetArch

enum MethodID(val cls: ClassID, _nme: String, _sig: String) {
  // see LightweightEnvironment.getSpecStrConcatMethod
  case KeyStrings_newKeyString0 extends MethodID(ClassID.KeyStrings, "newKeyString0", "(I)Ljava/lang/String;")
  case KeyStrings_newString extends MethodID(ClassID.KeyStrings, "newString", "()Ljava/lang/String;")
  case KeyStrings_newString_aC extends MethodID(ClassID.KeyStrings, "newString", "([C)Ljava/lang/String;")
  case KeyStrings_newString_aCII extends MethodID(ClassID.KeyStrings, "newString", "([CII)Ljava/lang/String;")
  case KeyStrings_newString_aBIII extends MethodID(ClassID.KeyStrings, "newString", "([BIII)Ljava/lang/String;")
  case KeyStrings_newString_aBI extends MethodID(ClassID.KeyStrings, "newString", "([BI)Ljava/lang/String;")

  // see LightweightEnvironment.getSpecStrConcatMethod
  case StrConcat_concat_s extends MethodID(ClassID.StrConcat, "concat_s", "(Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_ss extends MethodID(ClassID.StrConcat, "concat_ss", "(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_si extends MethodID(ClassID.StrConcat, "concat_si", "(Ljava/lang/String;I)Ljava/lang/String;")
  case StrConcat_concat_sc extends MethodID(ClassID.StrConcat, "concat_sc", "(Ljava/lang/String;C)Ljava/lang/String;")
  case StrConcat_concat_sb extends MethodID(ClassID.StrConcat, "concat_sb", "(Ljava/lang/String;Z)Ljava/lang/String;")
  case StrConcat_concat_ds extends MethodID(ClassID.StrConcat, "concat_ds", "(DLjava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_cs extends MethodID(ClassID.StrConcat, "concat_cs", "(CLjava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_ci extends MethodID(ClassID.StrConcat, "concat_ci", "(CI)Ljava/lang/String;")
  case StrConcat_concat_sss extends MethodID(ClassID.StrConcat, "concat_sss", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_ssi extends MethodID(ClassID.StrConcat, "concat_ssi", "(Ljava/lang/String;Ljava/lang/String;I)Ljava/lang/String;")
  case StrConcat_concat_ssc extends MethodID(ClassID.StrConcat, "concat_ssc", "(Ljava/lang/String;Ljava/lang/String;C)Ljava/lang/String;")
  case StrConcat_concat_slc extends MethodID(ClassID.StrConcat, "concat_slc", "(Ljava/lang/String;JC)Ljava/lang/String;")
  case StrConcat_concat_sis extends MethodID(ClassID.StrConcat, "concat_sis", "(Ljava/lang/String;ILjava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_sic extends MethodID(ClassID.StrConcat, "concat_sic", "(Ljava/lang/String;IC)Ljava/lang/String;")
  case StrConcat_concat_scs extends MethodID(ClassID.StrConcat, "concat_scs", "(Ljava/lang/String;CLjava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_sci extends MethodID(ClassID.StrConcat, "concat_sci", "(Ljava/lang/String;CI)Ljava/lang/String;")
  case StrConcat_concat_scc extends MethodID(ClassID.StrConcat, "concat_scc", "(Ljava/lang/String;CC)Ljava/lang/String;")
  case StrConcat_concat_sS8 extends MethodID(ClassID.StrConcat, "concat_sS8", "(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_sS7 extends MethodID(ClassID.StrConcat, "concat_sS7", "(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_sS6 extends MethodID(ClassID.StrConcat, "concat_sS6", "(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_sS5 extends MethodID(ClassID.StrConcat, "concat_sS5", "(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_sS4 extends MethodID(ClassID.StrConcat, "concat_sS4", "(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_sS3 extends MethodID(ClassID.StrConcat, "concat_sS3", "(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_ici extends MethodID(ClassID.StrConcat, "concat_ici", "(ICI)Ljava/lang/String;")
  case StrConcat_concat_css extends MethodID(ClassID.StrConcat, "concat_css", "(CLjava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_csi extends MethodID(ClassID.StrConcat, "concat_csi", "(CLjava/lang/String;I)Ljava/lang/String;")
  case StrConcat_concat_csc extends MethodID(ClassID.StrConcat, "concat_csc", "(CLjava/lang/String;C)Ljava/lang/String;")
  case StrConcat_concat_ccs extends MethodID(ClassID.StrConcat, "concat_ccs", "(CCLjava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_cci extends MethodID(ClassID.StrConcat, "concat_cci", "(CCI)Ljava/lang/String;")
  case StrConcat_concat_S8s extends MethodID(ClassID.StrConcat, "concat_S8s", "(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_S7s extends MethodID(ClassID.StrConcat, "concat_S7s", "(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_S7i extends MethodID(ClassID.StrConcat, "concat_S7i", "(Ljava/lang/String;I)Ljava/lang/String;")
  case StrConcat_concat_S6s extends MethodID(ClassID.StrConcat, "concat_S6s", "(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_S6i extends MethodID(ClassID.StrConcat, "concat_S6i", "(Ljava/lang/String;I)Ljava/lang/String;")
  case StrConcat_concat_S5s extends MethodID(ClassID.StrConcat, "concat_S5s", "(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_S5i extends MethodID(ClassID.StrConcat, "concat_S5i", "(Ljava/lang/String;I)Ljava/lang/String;")
  case StrConcat_concat_S4s extends MethodID(ClassID.StrConcat, "concat_S4s", "(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_S4i extends MethodID(ClassID.StrConcat, "concat_S4i", "(Ljava/lang/String;I)Ljava/lang/String;")
  case StrConcat_concat_S3s extends MethodID(ClassID.StrConcat, "concat_S3s", "(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_S3i extends MethodID(ClassID.StrConcat, "concat_S3i", "(Ljava/lang/String;I)Ljava/lang/String;")
  case StrConcat_concat_sssc extends MethodID(ClassID.StrConcat, "concat_sssc", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;C)Ljava/lang/String;")
  case StrConcat_concat_ssic extends MethodID(ClassID.StrConcat, "concat_ssic", "(Ljava/lang/String;Ljava/lang/String;IC)Ljava/lang/String;")
  case StrConcat_concat_sscc extends MethodID(ClassID.StrConcat, "concat_sscc", "(Ljava/lang/String;Ljava/lang/String;CC)Ljava/lang/String;")
  case StrConcat_concat_ssbc extends MethodID(ClassID.StrConcat, "concat_ssbc", "(Ljava/lang/String;Ljava/lang/String;ZC)Ljava/lang/String;")
  case StrConcat_concat_ssS5 extends MethodID(ClassID.StrConcat, "concat_ssS5", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_ssS4 extends MethodID(ClassID.StrConcat, "concat_ssS4", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_ssS3 extends MethodID(ClassID.StrConcat, "concat_ssS3", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_slcc extends MethodID(ClassID.StrConcat, "concat_slcc", "(Ljava/lang/String;JCC)Ljava/lang/String;")
  case StrConcat_concat_slS6 extends MethodID(ClassID.StrConcat, "concat_slS6", "(Ljava/lang/String;JLjava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_sici extends MethodID(ClassID.StrConcat, "concat_sici", "(Ljava/lang/String;ICI)Ljava/lang/String;")
  case StrConcat_concat_sicc extends MethodID(ClassID.StrConcat, "concat_sicc", "(Ljava/lang/String;ICC)Ljava/lang/String;")
  case StrConcat_concat_siS8 extends MethodID(ClassID.StrConcat, "concat_siS8", "(Ljava/lang/String;ILjava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_siS6 extends MethodID(ClassID.StrConcat, "concat_siS6", "(Ljava/lang/String;ILjava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_scss extends MethodID(ClassID.StrConcat, "concat_scss", "(Ljava/lang/String;CLjava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_scsc extends MethodID(ClassID.StrConcat, "concat_scsc", "(Ljava/lang/String;CLjava/lang/String;C)Ljava/lang/String;")
  case StrConcat_concat_sccs extends MethodID(ClassID.StrConcat, "concat_sccs", "(Ljava/lang/String;CCLjava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_sS6i extends MethodID(ClassID.StrConcat, "concat_sS6i", "(Ljava/lang/String;Ljava/lang/String;I)Ljava/lang/String;")
  case StrConcat_concat_cscs extends MethodID(ClassID.StrConcat, "concat_cscs", "(CLjava/lang/String;CLjava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_ccsc extends MethodID(ClassID.StrConcat, "concat_ccsc", "(CCLjava/lang/String;C)Ljava/lang/String;")
  case StrConcat_concat_S8ic extends MethodID(ClassID.StrConcat, "concat_S8ic", "(Ljava/lang/String;IC)Ljava/lang/String;")
  case StrConcat_concat_S7ss extends MethodID(ClassID.StrConcat, "concat_S7ss", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_S7sc extends MethodID(ClassID.StrConcat, "concat_S7sc", "(Ljava/lang/String;Ljava/lang/String;C)Ljava/lang/String;")
  case StrConcat_concat_S7ic extends MethodID(ClassID.StrConcat, "concat_S7ic", "(Ljava/lang/String;IC)Ljava/lang/String;")
  case StrConcat_concat_S6ss extends MethodID(ClassID.StrConcat, "concat_S6ss", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_S6sc extends MethodID(ClassID.StrConcat, "concat_S6sc", "(Ljava/lang/String;Ljava/lang/String;C)Ljava/lang/String;")
  case StrConcat_concat_S5ss extends MethodID(ClassID.StrConcat, "concat_S5ss", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_S5sc extends MethodID(ClassID.StrConcat, "concat_S5sc", "(Ljava/lang/String;Ljava/lang/String;C)Ljava/lang/String;")
  case StrConcat_concat_S4sc extends MethodID(ClassID.StrConcat, "concat_S4sc", "(Ljava/lang/String;Ljava/lang/String;C)Ljava/lang/String;")
  case StrConcat_concat_S3ic extends MethodID(ClassID.StrConcat, "concat_S3ic", "(Ljava/lang/String;IC)Ljava/lang/String;")
  case StrConcat_concat_sssss extends MethodID(ClassID.StrConcat, "concat_sssss", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_ssssc extends MethodID(ClassID.StrConcat, "concat_ssssc", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;C)Ljava/lang/String;")
  case StrConcat_concat_ssscc extends MethodID(ClassID.StrConcat, "concat_ssscc", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;CC)Ljava/lang/String;")
  case StrConcat_concat_sssS5 extends MethodID(ClassID.StrConcat, "concat_sssS5", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_ssisi extends MethodID(ClassID.StrConcat, "concat_ssisi", "(Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;I)Ljava/lang/String;")
  case StrConcat_concat_sscsc extends MethodID(ClassID.StrConcat, "concat_sscsc", "(Ljava/lang/String;Ljava/lang/String;CLjava/lang/String;C)Ljava/lang/String;")
  case StrConcat_concat_sscis extends MethodID(ClassID.StrConcat, "concat_sscis", "(Ljava/lang/String;Ljava/lang/String;CILjava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_ssS6i extends MethodID(ClassID.StrConcat, "concat_ssS6i", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)Ljava/lang/String;")
  case StrConcat_concat_ssS4s extends MethodID(ClassID.StrConcat, "concat_ssS4s", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_ssS6s extends MethodID(ClassID.StrConcat, "concat_ssS6s", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_siccs extends MethodID(ClassID.StrConcat, "concat_siccs", "(Ljava/lang/String;ICCLjava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_scscs extends MethodID(ClassID.StrConcat, "concat_scscs", "(Ljava/lang/String;CLjava/lang/String;CLjava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_scicc extends MethodID(ClassID.StrConcat, "concat_scicc", "(Ljava/lang/String;CICC)Ljava/lang/String;")
  case StrConcat_concat_sccsc extends MethodID(ClassID.StrConcat, "concat_sccsc", "(Ljava/lang/String;CCLjava/lang/String;C)Ljava/lang/String;")
  case StrConcat_concat_sS8ss extends MethodID(ClassID.StrConcat, "concat_sS8ss", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_sS8sc extends MethodID(ClassID.StrConcat, "concat_sS8sc", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;C)Ljava/lang/String;")
  case StrConcat_concat_sS8ic extends MethodID(ClassID.StrConcat, "concat_sS8ic", "(Ljava/lang/String;Ljava/lang/String;IC)Ljava/lang/String;")
  case StrConcat_concat_sS4ss extends MethodID(ClassID.StrConcat, "concat_sS4ss", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_sS3sc extends MethodID(ClassID.StrConcat, "concat_sS3sc", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;C)Ljava/lang/String;")
  case StrConcat_concat_sS3ic extends MethodID(ClassID.StrConcat, "concat_sS3ic", "(Ljava/lang/String;Ljava/lang/String;IC)Ljava/lang/String;")
  case StrConcat_concat_ssscs extends MethodID(ClassID.StrConcat, "concat_ssscs", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;CLjava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_icicc extends MethodID(ClassID.StrConcat, "concat_icicc", "(ICICC)Ljava/lang/String;")
  case StrConcat_concat_ccscc extends MethodID(ClassID.StrConcat, "concat_ccscc", "(CCLjava/lang/String;CC)Ljava/lang/String;")
  case StrConcat_concat_S8scc extends MethodID(ClassID.StrConcat, "concat_S8scc", "(Ljava/lang/String;Ljava/lang/String;CC)Ljava/lang/String;")
  case StrConcat_concat_S7sS7 extends MethodID(ClassID.StrConcat, "concat_S7sS7", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_S7sS6 extends MethodID(ClassID.StrConcat, "concat_S7sS6", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_S7sS4 extends MethodID(ClassID.StrConcat, "concat_S7sS4", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_S7sS5 extends MethodID(ClassID.StrConcat, "concat_S7sS5", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_S7iS6 extends MethodID(ClassID.StrConcat, "concat_S7iS6", "(Ljava/lang/String;ILjava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_S6sss extends MethodID(ClassID.StrConcat, "concat_S6sss", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_S6sS7 extends MethodID(ClassID.StrConcat, "concat_S6sS7", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_S6iS3 extends MethodID(ClassID.StrConcat, "concat_S6iS3", "(Ljava/lang/String;ILjava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_S4sS3 extends MethodID(ClassID.StrConcat, "concat_S4sS3", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_S3scc extends MethodID(ClassID.StrConcat, "concat_S3scc", "(Ljava/lang/String;Ljava/lang/String;CC)Ljava/lang/String;")
  case StrConcat_concat_S3iS4 extends MethodID(ClassID.StrConcat, "concat_S3iS4", "(Ljava/lang/String;ILjava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_sssiS3 extends MethodID(ClassID.StrConcat, "concat_sssiS3", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_sscscc extends MethodID(ClassID.StrConcat, "concat_sscscc", "(Ljava/lang/String;Ljava/lang/String;CLjava/lang/String;CC)Ljava/lang/String;")
  case StrConcat_concat_ssciS6 extends MethodID(ClassID.StrConcat, "concat_ssciS6", "(Ljava/lang/String;Ljava/lang/String;CILjava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_ssS7sc extends MethodID(ClassID.StrConcat, "concat_ssS7sc", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;C)Ljava/lang/String;")
  case StrConcat_concat_ssS6S3 extends MethodID(ClassID.StrConcat, "concat_ssS6S3", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_ssS3ic extends MethodID(ClassID.StrConcat, "concat_ssS3ic", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IC)Ljava/lang/String;")
  case StrConcat_concat_ssS4ss extends MethodID(ClassID.StrConcat, "concat_ssS4ss", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_sS4iS6 extends MethodID(ClassID.StrConcat, "concat_sS4iS6", "(Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_sssS5s extends MethodID(ClassID.StrConcat, "concat_sssS5s", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_sssS4s extends MethodID(ClassID.StrConcat, "concat_sssS4s", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_cssicc extends MethodID(ClassID.StrConcat, "concat_cssicc", "(CLjava/lang/String;Ljava/lang/String;ICC)Ljava/lang/String;")
  case StrConcat_concat_cscfS4 extends MethodID(ClassID.StrConcat, "concat_cscfS4", "(CLjava/lang/String;CFLjava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_S7sS6s extends MethodID(ClassID.StrConcat, "concat_S7sS6s", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_S3sS3i extends MethodID(ClassID.StrConcat, "concat_S3sS3i", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)Ljava/lang/String;")
  case StrConcat_concat_S3iccs extends MethodID(ClassID.StrConcat, "concat_S3iccs", "(Ljava/lang/String;ICCLjava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_ssccicc extends MethodID(ClassID.StrConcat, "concat_ssccicc", "(Ljava/lang/String;Ljava/lang/String;CCICC)Ljava/lang/String;")
  case StrConcat_concat_siS4lS8 extends MethodID(ClassID.StrConcat, "concat_siS4lS8", "(Ljava/lang/String;ILjava/lang/String;JLjava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_scsssS4 extends MethodID(ClassID.StrConcat, "concat_scsssS4", "(Ljava/lang/String;CLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_scsS7sc extends MethodID(ClassID.StrConcat, "concat_scsS7sc", "(Ljava/lang/String;CLjava/lang/String;Ljava/lang/String;Ljava/lang/String;C)Ljava/lang/String;")
  case StrConcat_concat_scsS6sc extends MethodID(ClassID.StrConcat, "concat_scsS6sc", "(Ljava/lang/String;CLjava/lang/String;Ljava/lang/String;Ljava/lang/String;C)Ljava/lang/String;")
  case StrConcat_concat_scsS3sc extends MethodID(ClassID.StrConcat, "concat_scsS3sc", "(Ljava/lang/String;CLjava/lang/String;Ljava/lang/String;Ljava/lang/String;C)Ljava/lang/String;")
  case StrConcat_concat_sciccci extends MethodID(ClassID.StrConcat, "concat_sciccci", "(Ljava/lang/String;CICCCI)Ljava/lang/String;")
  case StrConcat_concat_icicici extends MethodID(ClassID.StrConcat, "concat_icicici", "(ICICICI)Ljava/lang/String;")
  case StrConcat_concat_ccsssS4 extends MethodID(ClassID.StrConcat, "concat_ccsssS4", "(CCLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_S7icisc extends MethodID(ClassID.StrConcat, "concat_S7icisc", "(Ljava/lang/String;ICILjava/lang/String;C)Ljava/lang/String;")
  case StrConcat_concat_S6sciS3 extends MethodID(ClassID.StrConcat, "concat_S6sciS3", "(Ljava/lang/String;Ljava/lang/String;CILjava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_S6sccis extends MethodID(ClassID.StrConcat, "concat_S6sccis", "(Ljava/lang/String;Ljava/lang/String;CCILjava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_S6iccsc extends MethodID(ClassID.StrConcat, "concat_S6iccsc", "(Ljava/lang/String;ICCLjava/lang/String;C)Ljava/lang/String;")
  case StrConcat_concat_S4sS3ic extends MethodID(ClassID.StrConcat, "concat_S4sS3ic", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IC)Ljava/lang/String;")
  case StrConcat_concat_sissccsc extends MethodID(ClassID.StrConcat, "concat_sissccsc", "(Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;CCLjava/lang/String;C)Ljava/lang/String;")
  case StrConcat_concat_sicssics extends MethodID(ClassID.StrConcat, "concat_sicssics", "(Ljava/lang/String;ICLjava/lang/String;Ljava/lang/String;ICLjava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_scscscS5 extends MethodID(ClassID.StrConcat, "concat_scscscS5", "(Ljava/lang/String;CLjava/lang/String;CLjava/lang/String;CLjava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_sS4sccss extends MethodID(ClassID.StrConcat, "concat_sS4sccss", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;CCLjava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_S8fcfS5s extends MethodID(ClassID.StrConcat, "concat_S8fcfS5s", "(Ljava/lang/String;FCFLjava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_S7iS5lcc extends MethodID(ClassID.StrConcat, "concat_S7iS5lcc", "(Ljava/lang/String;ILjava/lang/String;JCC)Ljava/lang/String;")
  case StrConcat_concat_S6icclcc extends MethodID(ClassID.StrConcat, "concat_S6icclcc", "(Ljava/lang/String;ICCJCC)Ljava/lang/String;")
  case StrConcat_concat_S5sssssc extends MethodID(ClassID.StrConcat, "concat_S5sssssc", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;C)Ljava/lang/String;")
  case StrConcat_concat_ssS6iccis extends MethodID(ClassID.StrConcat, "concat_ssS6iccis", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ICCILjava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_siS5islS4 extends MethodID(ClassID.StrConcat, "concat_siS5islS4", "(Ljava/lang/String;ILjava/lang/String;ILjava/lang/String;JLjava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_sssS4sS4s extends MethodID(ClassID.StrConcat, "concat_sssS4sS4s", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_cscscscsc extends MethodID(ClassID.StrConcat, "concat_cscscscsc", "(CLjava/lang/String;CLjava/lang/String;CLjava/lang/String;CLjava/lang/String;C)Ljava/lang/String;")
  case StrConcat_concat_S7iS8fcsc extends MethodID(ClassID.StrConcat, "concat_S7iS8fcsc", "(Ljava/lang/String;ILjava/lang/String;FCLjava/lang/String;C)Ljava/lang/String;")
  case StrConcat_concat_S4sssssS3 extends MethodID(ClassID.StrConcat, "concat_S4sssssS3", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_sssccscccc extends MethodID(ClassID.StrConcat, "concat_sssccscccc", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;CCLjava/lang/String;CCCC)Ljava/lang/String;")
  case StrConcat_concat_sssS6S7sS3 extends MethodID(ClassID.StrConcat, "concat_sssS6S7sS3", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_sssS3scccc extends MethodID(ClassID.StrConcat, "concat_sssS3scccc", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;CCCC)Ljava/lang/String;")
  case StrConcat_concat_ssS6sccsS4s extends MethodID(ClassID.StrConcat, "concat_ssS6sccsS4s", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;CCLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_S6iS7iS8scs extends MethodID(ClassID.StrConcat, "concat_S6iS7iS8scs", "(Ljava/lang/String;ILjava/lang/String;ILjava/lang/String;Ljava/lang/String;CLjava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_csS4sS4sS4sc extends MethodID(ClassID.StrConcat, "concat_csS4sS4sS4sc", "(CLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;C)Ljava/lang/String;")
  case StrConcat_concat_sscccscS4csS7 extends MethodID(ClassID.StrConcat, "concat_sscccscS4csS7", "(Ljava/lang/String;Ljava/lang/String;CCCLjava/lang/String;CLjava/lang/String;CLjava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_sscccscS4csS5 extends MethodID(ClassID.StrConcat, "concat_sscccscS4csS5", "(Ljava/lang/String;Ljava/lang/String;CCCLjava/lang/String;CLjava/lang/String;CLjava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_cicicicicicfc extends MethodID(ClassID.StrConcat, "concat_cicicicicicfc", "(CICICICICICFC)Ljava/lang/String;")
  case StrConcat_concat_S6sS7sscsS7icc extends MethodID(ClassID.StrConcat, "concat_S6sS7sscsS7icc", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;CLjava/lang/String;Ljava/lang/String;ICC)Ljava/lang/String;")
  case StrConcat_concat_S5sfcfcfcfS6S5 extends MethodID(ClassID.StrConcat, "concat_S5sfcfcfcfS6S5", "(Ljava/lang/String;Ljava/lang/String;FCFCFCFLjava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
  case StrConcat_concat_sisisisisisisisisic extends MethodID(ClassID.StrConcat, "concat_sisisisisisisisisic", "(Ljava/lang/String;ILjava/lang/String;ILjava/lang/String;ILjava/lang/String;ILjava/lang/String;ILjava/lang/String;ILjava/lang/String;ILjava/lang/String;ILjava/lang/String;IC)Ljava/lang/String;")
  case invoke extends MethodID(ClassID.Method, "invoke", "(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;")

  val nme = JStringsModule.internJString(_nme)
  val sig = JStringsModule.intern(processSig(JStringsModule.internJString(_sig)))

  private def processSig(sig: XString) = if (targetArch.is64Bit) {
    sig.replace('&', 'J')
  } else {
    sig.replace('&', 'I')
  }
}
