/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.
 * This source file is part of the Cangjie project, licensed under Apache-2.0
 * with Runtime Library Exception.
 *
 * See https://cangjie-lang.cn/pages/LICENSE for license information.
 */

package com.huawei.excelsior.jet.compiler

enum RTSProc {
  case JRS_ThrowInstantiationError
  case JR_ArrayCast
  case JR_ScalaArrayCast
  case JR_ArrayIs
  case JR_ScalaArrayIs
  case CJ_UncheckedArrayCopy
  case CJ_ArrayCopyOf
  case CJ_ArrayCopyOfRange
  case CJ_ArrayCopyGeneric
  case CJ_ArrayCopyInitGeneric
  case CJ_ArrayCopyDirty
  case JR_CheckArrayStore
  case JR_CheckArrayStoreNotNull
  case JR_CheckArrayStoreOpt
  case JR_ScalaCheckArrayStore
  case JR_ScalaCheckArrayStoreNotNull
  case JR_ScalaCheckArrayStoreOpt
  case CJ_AcquireRawData
  case CJ_ReleaseRawData
  case JR_Clinit
  case JR_ClinitedAssert
  case JR_InitializedAssert
  case JR_FatalError
  case JR_FatalError_Exception
  case JR_GetClassObjectNonAbsent
  case JR_GetClassObject
  case JR_GetScalaClassObject
  case JR_InterfaceCheckCast
  case JR_ResolveJSR292
  case JR_getTargetForLinkToSpecial
  case JR_MemberNamePreparationCheck
  case JR_ResolveDeferred
  case JR_LinkDeferred
  case JR_DeferredGetClassObject
  case JR_DeferredInstanceof
  case JR_DeferredCast
  case JR_LoadConstantMethodHandleThroughDAI
  case JR_LoadConstantMethodTypeThroughDAI
  case JR_DeferredNew
  case JR_DeferredNewArray
  case JR_FindIMTOrThrow
  case JR_FindIMTForThunk
  case StandardExceptions_throwIllegalMonitorStateException
  case JR_MonitorEnter
  case JR_MonitorExit
  case JR_FillStructuredCheckingTable
  case JR_CheckStructuredLockingOnNormalExit
  case JR_CheckedMonitorEnter
  case JR_CheckedMonitorExit
  case JR_NEW
  case JR_NEW8
  case JR_NEW16
  case JR_NEW24
  case JR_NEW32
  case JR_NEW40
  case JR_NEW48
  case JR_NEW56
  case JR_NEW64
  case JR_NEW72
  case JR_NEW80
  case JR_NEW88
  case JR_NEW96
  case JR_NEW_STRING
  case JR_NEW_STRING40
  case JR_NEW_STRING48
  case JR_NEW_STRING56
  case JR_NEW_STRING64
  case JR_NEW_STRING72
  case JR_NEW_STRING80
  case JR_NEW_STRING88
  case JR_NEW_STRING96
  case JR_NEW_STRING104
  case JR_NEW_STRING112
  case JR_NEW_STRING120
  case JR_NEW_STRING128
  case JR_NEW_STRING136
  case JR_NEW_STRING144
  case JR_NEW_ARRAY16
  case JR_NEW_ARRAY24
  case JR_NEW_ARRAY32
  case JR_NEW_ARRAY40
  case JR_NEW_ARRAY48
  case JR_NEW_ARRAY56
  case JR_NEW_ARRAY64
  case JR_NEW_ARRAY72
  case JR_NEW_ARRAY80
  case JR_NEW_ARRAY88
  case JR_NEW_ARRAY96
  case JR_NEW_ARRAY104
  case JR_NEW_ARRAY112
  case JR_NEW_ARRAY_MD
  case JR_NEW_PRIMARRAY
  case JR_NEW_PRIMARRAY_COPY
  case JR_NEW_REFARRAY
  case JR_NEW_REFARRAY_COPY
  case JR_NEW_REFARRAY_SAMETYPE
  case JR_NEW_REFARRAY_OFTYPE
  case JR_NEW_AJ_ARRAY
  case JR_NEW_CJ_ARRAY
  case JR_NEW_CJ_ARRAY_NO_INIT
  case JR_NEW_AJ_PRIMARRAY
  case JR_NEW_CJ_PRIMARRAY
  case JR_NEW_CJ_RECORD_ARRAY_WITHOUT_REFS
  case JR_NEW_CJ_RECORD_ARRAY_WITH_REFS
  case JR_NEW_AJ_REFARRAY
  case JR_NEW_CJ_REFARRAY
  case JR_NEW_SCALA_PRIMARRAY
  case JR_NEW_SCALA_REFARRAY
  case JR_PrepareType
  case JR_Throw
  case JR_ThrowAbstractMethodError
  case JR_ThrowAbstractMethodError0
  case JR_ThrowArithmeticException
  case JR_ThrowArrayIndexOutOfBoundsException
  case JR_ThrowArrayStoreException
  case JR_ThrowClassCastExceptionByObj
  case JR_ThrowClassCircularityError
  case JR_ThrowClassFormatError
  case JR_ThrowIllegalAccessError
  case JR_ThrowIllegalAccessError0
  case JR_ThrowIllegalArgumentException
  case JR_ThrowIncompatibleClassChangeError
  case JR_ThrowIncompatibleClassChangeError0
  case JR_ThrowInstantiationError
  case JR_ThrowNegativeArraySizeException
  case JR_ThrowNoClassDefFoundError
  case JR_ThrowNoSuchFieldError
  case JR_ThrowNoSuchMethodError
  case JR_ThrowNullPointerException
  case JR_ThrowUnsupportedClassVersionError
  case JR_ThrowVerifyError
  case JR_ForwardException
  case JR_ThrowAJArithmeticException
  case JR_ThrowAJAddOverflowException
  case JR_ThrowAJSubOverflowException
  case JR_ThrowAJMulOverflowException
  case JR_ThrowAJDivOverflowException
  case JR_ThrowManualAJAddOverflowException
  case JR_ThrowManualAJSubOverflowException
  case JR_ThrowManualAJMulOverflowException
  case JR_ThrowManualAJDivOverflowException
  case JR_ThrowAJArrayIndexOutOfBoundsException
  case JR_ThrowAJClassCastException
  case JR_ThrowAJNullPointerException
  case JR_ThrowCJArithmeticException
  case JR_ThrowCJIndexOutOfBoundsException
  case JR_ThrowCJNegativeArraySizeException
  case JR_ThrowCJNoneValueException
  case JR_ThrowScalaArithmeticException
  case JR_ThrowScalaArrayIndexOutOfBoundsException
  case JR_ThrowScalaArrayStoreException
  case JR_ThrowScalaNegativeArraySizeException
  case JR_ThrowScalaNullPointerException
  case JR_ThrowScalaClassCastExceptionByObj
  case JR_ThrowScalaInstantiationError
  case JR_UnmanagedArrayCast
  case JR_UnmanagedCast
  case X2J_INIT_CLASS
  case JR_lmul
  case JR_lmulh
  case JR_ldiv
  case JR_lrem
  case JR_dstrictdiv
  case JR_dstrictmul
  case JR_d2i_st2mem_dprec
  case JR_f2i_st2mem_dprec
  case JR_fd2l_st2mem_dprec
  case JR_Adjust_F2I
  case JR_Adjust_F2L
  case JR_Adjust_D2I
  case JR_Adjust_D2L
  case JR_Bitcount_I_backupPath
  case JR_Bitcount_L_backupPath

  // Math intrinsics
  case JR_sin
  case JR_cos
  case JR_tan
  case JR_asin
  case JR_acos
  case JR_atan
  case JR_exp
  case JR_log
  case JR_sqrt
  case JR_sqrtf
  case JR_ceil
  case JR_floor
  case JR_rint
  case JR_dabs
  case JR_fabs
  case JR_atan2
  case JR_pow
  case JR_rem1
  case JR_drem
  case JR_frem
  case time
  case JR_GCSafeStateAssert
  case JR_EnterGCSafetyChecksFreeSection
  case JR_LeaveGCSafetyChecksFreeSection
  case JR_ObtainPendingException
  case ExceptionHandling_convertIntoDomain
  case ExceptionHandling_trivialHandler
  case JR_StrConcat
  case JR_AJStrConcat
  case JR_LinkNative
  case JR_PinFiberToCarrier
  case getCallerClassHandleForFrame
  case JR_ClassIs
  case JR_ClassCast
  case JR_InterfaceIs
  case JR_InterfaceIsWithCache
  case JR_idiv
  case JR_irem
  case JR_uidiv
  case JR_uirem
  case JR_f2l
  case JR_d2l
  case JR_l2f
  case JR_l2d
  case JR_f2ul
  case JR_d2ul
  case JR_ul2f
  case JR_ul2d
  case JR_CHABackupPath
  case JR_TauBackupPath
  case JR_TauFastPath
  case NewBaselineExceptionTable_findHandlerOrRethrow
  case NewBaselineExceptionTable_rethrow
  case NewBaselineJavaExceptionsHandling_findHandlerOrRethrowWithSLCheck
  case NewBaselineJavaExceptionsHandling_findHandlerOrUnlockAndRethrowWithSLCheck
  case NewBaselineJavaExceptionsHandling_rethrowWithSLCheck
  case NewBaselineJavaExceptionsHandling_unlockAndRethrowWithSLCheck
  case WriteBarriers_writeBarrier_instance_baseline
  case WriteBarriers_writeBarrier_instance_verification
  case WriteBarriers_writeBarrier_static_baseline
  case WriteBarriers_writeBarrier_static_verification
  case WriteBarriers_writeBarrier_record_baseline
  case IFaceOps_castAndEnrich
  case IFaceOps_castAndEnrichNoCache
  case IFaceOps_enrich
  case IFaceOps_getEnrichment
  case JR_atomicGetLong
  case JR_atomicGetDouble
  case JR_atomicPutLong
  case JR_atomicPutDouble
  case ThinObj_checkCast
  case ThinObj_isInstanceOf
  case ThinObj_castFailedError
  case JR_addsf
  case JR_adddf
  case JR_subsf
  case JR_subdf
  case JR_mulsf
  case JR_muldf
  case JR_divsf
  case JR_divdf
  case JR_negsf
  case JR_negdf
  case JR_extendsfdf
  case JR_truncdfsf
  case JR_fixsfsi
  case JR_fixdfsi
  case JR_fixsfdi
  case JR_fixdfdi
  case JR_floatsisf
  case JR_floatsidf
  case JR_floatdisf
  case JR_floatdidf
  case JR_eqsf
  case JR_eqdf
  case JR_nesf
  case JR_nedf
  case JR_gtsf
  case JR_gtdf
  case JR_gesf
  case JR_gedf
  case JR_ltsf
  case JR_ltdf
  case JR_lesf
  case JR_ledf
  case JR_cmplsf
  case JR_cmpldf
  case JR_cmpgsf
  case JR_cmpgdf
  case ObjectNatives_getClass
  case AnyRefNatives_getClass
  case HookInvokerFrameDescriptor_init
  case JR_incHeldLocks
  case JR_decHeldLocks
  case VMT_fatalErrorStub
  case JR_OBJECT_EVACUATE

  case CJ_IdentityHashCode
  case CJ_Spawn

  ///////////////////////////////
  // Cangjie special math support
  case CJ_saturatingAddI8
  case CJ_saturatingSubI8
  case CJ_saturatingMulI8
  case CJ_saturatingDivI8
  case CJ_saturatingModI8
  case CJ_saturatingIncI8
  case CJ_saturatingDecI8
  case CJ_saturatingNegI8
  case CJ_saturatingAddU8
  case CJ_saturatingSubU8
  case CJ_saturatingMulU8
  case CJ_saturatingDivU8
  case CJ_saturatingModU8
  case CJ_saturatingIncU8
  case CJ_saturatingDecU8
  case CJ_saturatingNegU8
  case CJ_saturatingAddI16
  case CJ_saturatingSubI16
  case CJ_saturatingMulI16
  case CJ_saturatingDivI16
  case CJ_saturatingModI16
  case CJ_saturatingIncI16
  case CJ_saturatingDecI16
  case CJ_saturatingNegI16
  case CJ_saturatingAddU16
  case CJ_saturatingSubU16
  case CJ_saturatingMulU16
  case CJ_saturatingDivU16
  case CJ_saturatingModU16
  case CJ_saturatingIncU16
  case CJ_saturatingDecU16
  case CJ_saturatingNegU16
  case CJ_saturatingAddI32
  case CJ_saturatingSubI32
  case CJ_saturatingMulI32
  case CJ_saturatingDivI32
  case CJ_saturatingModI32
  case CJ_saturatingIncI32
  case CJ_saturatingDecI32
  case CJ_saturatingNegI32
  case CJ_saturatingAddU32
  case CJ_saturatingSubU32
  case CJ_saturatingMulU32
  case CJ_saturatingDivU32
  case CJ_saturatingModU32
  case CJ_saturatingIncU32
  case CJ_saturatingDecU32
  case CJ_saturatingNegU32
  case CJ_saturatingAddI64
  case CJ_saturatingSubI64
  case CJ_saturatingMulI64
  case CJ_saturatingDivI64
  case CJ_saturatingModI64
  case CJ_saturatingIncI64
  case CJ_saturatingDecI64
  case CJ_saturatingNegI64
  case CJ_saturatingAddU64
  case CJ_saturatingSubU64
  case CJ_saturatingMulU64
  case CJ_saturatingDivU64
  case CJ_saturatingModU64
  case CJ_saturatingIncU64
  case CJ_saturatingDecU64
  case CJ_saturatingNegU64
  case CJ_saturatingPowI64
  case CJ_throwingPowI64
  ///////////////////////////////
}
