/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.
 * This source file is part of the Cangjie project, licensed under Apache-2.0
 * with Runtime Library Exception.
 *
 * See https://cangjie-lang.cn/pages/LICENSE for license information.
 */

package xscala.io

import xscala.io.ByteBuffer.INITIAL_CAPACITY
import xscala.text.{EncodingException, PlatformEncoding}
import xscala.util.MathUtils.{alignUp, isAligned, isNBits, isNBitsSigned}

import scala.annotation.{nowarn, varargs}

/** A machine-independent buffer for the generated data.
  * Contains a sequence of generated bytes, in little-endian.
  *
  * @author paul
  * @author cypok
  * @author conwor
  * @author ijorch
  */
object ByteBuffer {
  /** Default initial capacity of bytes buffer. */
  private val INITIAL_CAPACITY = 32
}

class ByteBuffer(protected var bytes: Array[Byte], protected var _length: Int) extends DataOutput {
  assert(_length <= bytes.length)

  def this(size: Int = INITIAL_CAPACITY) = this(new Array[Byte](size), 0)

  def this() = this(INITIAL_CAPACITY) // TODO-DECAF: use default parameters

  final def length = _length

  final def getBytesPointer = bytes

  /** @return byte array with no extra space after this buffer length. */
  def toByteArray = bytes.slice(0, length)

  override final def toString = try {
    PlatformEncoding.native.decodeStringThrowing(getBytesPointer, 0, length)
  } catch {
    case _: EncodingException => bytes.take(length).map(String.format("%02X", _)).mkString(" ")
  }

  final def isEmpty = length == 0

  final def nonEmpty = length > 0

  final def cropAt(pos: Int): Unit = _length = pos

  final def reset(): Unit = cropAt(0)

  private def expandCapacity(newCapacity: Int): Unit = {
    val newBytes = new Array[Byte](newCapacity)
    Array.copy(bytes, 0, newBytes, 0, length)
    bytes = newBytes
  }

  private def reserve(size: Int): Unit = {
    val requiredCapacity = length + size
    if (requiredCapacity > bytes.length) {
      expandCapacity(requiredCapacity max (bytes.length * 2))
    }
  }

  override def putBytes(data: Array[Byte], offset: Int, size: Int): Unit = {
    reserve(size)
    Array.copy(data, offset, this.bytes, this.length, size)
    this._length += size
  }

  def putByte(b: Int): Unit = {
    assert(isNBits(b, 8) || isNBitsSigned(b, 8))
    reserve(1)
    bytes(length) = b.toByte
    _length += 1
  }

  ///////////////////////////////////////////////////////////////////////////////////////////////

  final def append(that: ByteBuffer): Unit = putBytes(that.bytes, 0, that.length)

  def align(alignment: Int, filler: Int = 0): Unit = {
    val toAlign = alignUp(length, alignment) - length
    for (_ <- 0 until toAlign) {
      putByte(filler)
    }
    assert(isAligned(length, alignment))
  }

  final def setBytes(startPos: Int, bytes: collection.Seq[Int]): Unit = {
    for (i <- bytes.indices) {
      setByte(startPos + i, bytes(i))
    }
  }

  @varargs final def setBytes(startPos: Int, bytes: Int*): Unit = {
    setBytes(startPos, bytes)
  }

  final def setByte(pos: Int, b: Int): Unit = {
    assert(isNBits(b, 8), s"${b.toHexString}")
    assert(0 <= pos && pos < length)
    bytes(pos) = b.toByte
  }

  final def setW8(pos: Int, w8: Int): Unit = setByte(pos, w8)

  final def setW16(pos: Int, w16: Int): Unit = {
    assert(isNBits(w16, 16))
    setW8(pos, w16 & 0xff)
    setW8(pos + 1, w16 >>> 8)
  }

  final def setW32(pos: Int, w32: Int): Unit = {
    setW16(pos, w32 & 0xffff)
    setW16(pos + 2, w32 >>> 16)
  }

  final def setW64(pos: Int, w64: Long): Unit = {
    setW32(pos, w64.toInt)
    setW32(pos + 4, (w64 >>> 32).toInt)
  }

  final def getByte(pos: Int): Byte = {
    assert(0 <= pos && pos < length)
    bytes(pos)
  }

  final def getUByte(pos: Int): Int = 0xFF & getByte(pos)

  final def getW8(pos: Int): Byte = getByte(pos)

  final def getUW8(pos: Int): Int = getUByte(pos)

  final def getW16(pos: Int): Short = (getUW8(pos) | (getUW8(pos + 1) << 8)).toShort

  final def getUW16(pos: Int): Int = 0xFFFF & getW16(pos)

  final def getW32(pos: Int): Int = getUW16(pos) | (getUW16(pos + 2) << 16)

  final def getUW32(pos: Int): Long = {
    // Undo sign-extension
    0xffffffffL & getW32(pos).toLong
  }

  final def getW64(pos: Int): Long = getUW32(pos) | (getUW32(pos + 4) << 32)

  final def patchByte(pos: Int, addend: Int): Unit = {
    val content = getByte(pos)
    val value = content + addend
    assert(isNBitsSigned(value, 8))
    setByte(pos, value & 0xff)
  }

  final def patchW8(pos: Int, addend: Int): Unit = patchByte(pos, addend)

  final def patchW16(pos: Int, addend: Int): Unit = setW16(pos, getW16(pos).toInt + addend)

  final def patchW32(pos: Int, addend: Int): Unit = setW32(pos, getW32(pos) + addend)

  final def patchW64(pos: Int, addend: Long): Unit = setW64(pos, getW64(pos) + addend)
}
