/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.
 * This source file is part of the Cangjie project, licensed under Apache-2.0
 * with Runtime Library Exception.
 *
 * See https://cangjie-lang.cn/pages/LICENSE for license information.
 */

package com.huawei.excelsior.jet.compiler.opt.frontend.bytecode

import com.huawei.excelsior.common.CodeHelpers.*
import com.huawei.excelsior.common.Language.JAVA
import com.huawei.excelsior.common.LanguagePack
import com.huawei.excelsior.jet.assembler.AsmType
import com.huawei.excelsior.jet.codeemitter.BarrierKind
import com.huawei.excelsior.jet.codeemitter.BarrierKind.*
import com.huawei.excelsior.jet.common.{DAIRefKind, XString}
import com.huawei.excelsior.jet.compiler.Env.languagePack
import com.huawei.excelsior.jet.compiler.StatsKind.NoReturn
import com.huawei.excelsior.jet.compiler.abi.DAIGenerator
import com.huawei.excelsior.jet.compiler.bytecode.Bytecode.*
import com.huawei.excelsior.jet.compiler.bytecode.ConstantPool.Access
import com.huawei.excelsior.jet.compiler.bytecode.{MethodAccessKind as MAK, *}
import com.huawei.excelsior.jet.compiler.debug.dwarf.entries.langjava.JavaDwarfTypes
import com.huawei.excelsior.jet.compiler.debug.info.DebugLocalVar
import com.huawei.excelsior.jet.compiler.intrinsics.IntrinsicWithBody
import com.huawei.excelsior.jet.compiler.intrinsics.IntrinsicWithoutBody.*
import com.huawei.excelsior.jet.compiler.ir.{BytecodeOffset, ColumnNumber}
import com.huawei.excelsior.jet.compiler.lambda.LambdaTypeGenerator
import com.huawei.excelsior.jet.compiler.opt.frontend.bytecode.intrinsics.Intrinsics
import com.huawei.excelsior.jet.compiler.opt.ir.{CheckLevels, ConstBranchElimination, Universe}
import com.huawei.excelsior.jet.compiler.opt.middle.ClinitAnalysisConfig
import com.huawei.excelsior.jet.compiler.opt.middle.patterns.Arrays
import com.huawei.excelsior.jet.compiler.opt.CompilerException
import com.huawei.excelsior.jet.compiler.options.BoolOption.*
import com.huawei.excelsior.jet.compiler.symlevel.Type.asClassType
import com.huawei.excelsior.jet.compiler.symlevel.{TypeKind as TKind, *}
import com.huawei.excelsior.jet.compiler.symlevel.TypeKind.*
import com.huawei.excelsior.jet.compiler.types.ReferenceTypes.*
import com.huawei.excelsior.jet.compiler.types.References.UpperBounded
import com.huawei.excelsior.jet.compiler.*
import com.huawei.excelsior.jet.compiler.types.CompiledType
import com.huawei.excelsior.jet.util.ScalaCollections

import scala.util.control.Breaks

/**
 * Java bytecode data flow analysis and operations builder.
 * Used as second pass for java bytecode parsing.
 *
 * During first ([[com.huawei.excelsior.jet.compiler.opt.frontend.bytecode.ControlFlow ControlFlow]] pass we split bytecode
 * range by basic blocks and formed ControlFlow graph of basic blocks.
 * Here we provide abstract interpretation for each basic block completing
 * [[com.huawei.excelsior.jet.compiler.opt.ir.AbstractInterpreterComponent.AbstractInterpreter AbstractInterpreter]]
 * interface with `interpret` method.
 *
 * During abstract interpretation of a block, IR nodes are generated by corresponding bytecode instructions.
 *
 * @author paul
 */
trait DataFlow extends VMStates
                  with Intrinsics
                  with ConstBranchElimination
                  with ClinitAnalysisConfig
                  with Toolbox
                  with Arrays { self: Universe with ControlFlow =>

  case class ParseInfo(needMemBarBeforeReturn: Boolean)

  def parseMethod(method: Method, cfState: ControlFlowParsingState, args: Seq[Node]): ParseInfo = env.withDebugPosition(curPos()) {
    new BytecodeParser(method, cfState, args).parse()
  }

  private class BytecodeParser(method: Method, cfState: ControlFlowParsingState, args: Seq[Node]) {
    locally {
      val ic = Position.inlineContext(curPos()) getOrElse shouldNotReachHere("should be covered by withPos()")
      assert(method == ic.method)
    }

    private var bc: Int = -1
    def currentPosition() =
      if (bc >= 0) currentMethodPos(bc) else NoPosition

    val attr = method.codeAttribute
    val cp = method.getDeclaringClass.getClassConstantPool
    val bcIterator = new BytecodeIterator(attr)
    private var needMemBarBeforeReturn: Boolean = false

    val blockParsing = new Breaks

    private val managedContext = method.isManaged

    private val noNullCheck       = method.noNullCheck(env)
    private val noArrayIndexCheck = method.noArrayIndexCheck(env)
    private val noArrayStoreCheck = method.noArrayStoreCheck(env)

    if (method.isNonThrowing) {
      // At the moment, CompilerInterfaceGenerator do not add @CompilerHint.StackCheckByCaller annotations,
      // so the `isExternal` is a workaround for methods from CompilerInterface.
      assert(method.shouldStackCheckByCaller || method.isExternal,
        s"Method ${method.getFullName} annotated with @NonThrowing, so it must be annotated with @CompilerHint.StackCheckByCaller.")
    }

    class VMStateInterpreter extends AbstractInterpreter {
      type State = VMState

      override protected def debug(msg: String): Unit = {
        if (env.enabled(DetailedParsingLogs)) {
          dbgPrinter.debugNodes("All graph after " + msg)
        }
      }

      private def registerXCtrl(n: Node, state: State, handler: XBlock): Unit = {
        if (handler != null) n match {
          case sn: SpinalNode if sn.canThrow =>
            val xpoint = sn.xpoint
            handler.addArg(xpoint)

            val xstate = state.fork().dropStack()
            xstate.xobj = Invalid
            xstate.memory = Invalid
            xstate.rewind(sn)
            xstate.add(xpoint)
            addXCtrl(xpoint, xstate)

          case _ =>
        }
      }

      protected def startInputState(b: Block) =
        new VMState(entryMemory, attr.maxLocals, attr.maxStack)

      protected def interpret(block: Block, state: VMState): Block = {
        require(state != null)
        val anchor = block.outCtrl match {
          case anchor: HandlerAnchor => anchor
          case x => assert(x == block.blockEnd); null
        }

        currentScope.inState(state) {
          withIdempotentDominance {
            // In IR built from bytecode there may be only one exception handler for a block.
            val xhandler = if (anchor != null) anchor.xHandler else null
            onCommit.withCallback(n => registerXCtrl(n, state, xhandler)) {
              state.add(block)
              if (anchor != null) {
                state.add(anchor)
              }
              block.blockEnd.inCtrl = null
              block.spineBackwardIsBroken = true

              // Here both memory and control dependencies become broken in this block.
              // Note that overall CFG remains valid, because block and its block end are still linked.
              // TODO: do not break IR and rework state so that it can keep this block together,
              //       while allowing insertion of new nodes in parsing and in insert code.

              val blockParser = new BlockParser(block, state)
              for (kind <- cfState.kinds.get(block)) {
                blockParsing.breakable {
                  kind match {
                    case PrologBlock                   => blockParser.parseProlog()
                    case exBlock: ExceptionStuffBlock  => blockParser.parseExStuff(exBlock)
                    case BytecodeRange(startPC, endPC) => bcIterator.iterate(blockParser, startPC, endPC)
                  }
                }
              }
              blockParser.adjustBlockEnd()
              block.spineBackwardIsBroken = false
              checkConsistency(CheckLevels.Desirable)(Block.verifyBlockControlNums(block))
              if (state.contextTypes != null) {
                ContextTypesMap.setMapAt(block.blockEnd, state.contextTypes)
              }
            }
          }
        }
        bc = -1
        if (anchor != null) {
          strikeOut(anchor)
        }
        block
      }

      override protected def interpretEdge(blockExit: BlockExit, state: VMState): ControlNode = {
        if (state.contextTypes != null) {
          val filter = state.contextTypes.makeFilter(blockExit)
          if (filter != null) {
            val branchExit = blockExit.asInstanceOf[Branch.Exit] // Otherwise it cannot be filter exit
            if (filter.isRedundant) {
              ContextTypesStats.updateOnRedundantFilterRemove(filter)
              return replaceByGoto(branchExit)
            } else {
              state.contextTypes.appendFilter(filter)
              ContextTypesMap.setMapAt(branchExit, state.contextTypes)
            }
          }
        }
        blockExit
      }
    }

    def parse(): ParseInfo = {
      val intp = new VMStateInterpreter
      withPosFactory(currentPosition) {
        Node.withImplicitArgConversion(enrichArg()) {
          intp.iterate()
        }
      }
      ParseInfo(needMemBarBeforeReturn)
    }

    private class BlockParser(block: Block, st: VMState) extends BytecodeProcessor {

      private def throwErrorAndHalt(error: ConstantPool.ErrorAccessInfo): Nothing = {
        var proc = error.getThrowProc
        var msg = error.getErrorMessage

        if (!managedContext) {
          msg = XString.ascii(s"${proc.toString}: $msg")
          proc = RTSProc.JR_FatalError
        }

        throwErrorAndHalt(proc, msg)
      }

      private def throwErrorAndHalt(proc: RTSProc, msg: XString): Nothing = {
        ErrorRTSCall(proc)(AJString.bstr(msg))
        haltBlock(Halt.afterRTSCall(proc, msg.toString))
      }

      private def throwErrorAndHalt(proc: RTSProc, args: Node*): Nothing = {
        ErrorRTSCall(proc)(args: _*)
        haltBlock(Halt.explained("java bytecode data-flow analysis"))
      }

      private enum BlockEndStatus {
        case RAW, ADJUSTED, IN_STATE
      }
      import BlockEndStatus.*

      private var blockEndStatus = RAW

      /** Ties `block`'s end to current control and current memory. Block ends are created in
        * ControlFlow (to form normal CFG) and we do not append them again in DataFlow, so they
        * will not appear in scope state, except when we replace block end by some other block end
        * during DataFlow processing.
        */
      def adjustBlockEnd(): Unit = {
        val end = block.blockEnd
        val inState = end == currentCtrl
        blockEndStatus match {
          case IN_STATE =>
            assert(inState)
          case ADJUSTED =>
            assert(!inState)
            assert(end.inCtrl == currentCtrl && end.inMemory == currentMemory)
          case RAW if inState =>
            blockEndStatus = IN_STATE
          case RAW =>
            assert(currentCtrl != null && currentMemory != null && currentCtrl.block == block)
            end.inCtrl = currentCtrl.asInstanceOf[UpperPoint]
            end.inMemory = currentMemory
            blockEndStatus = ADJUSTED
        }
      }

      //////////// ENTRY BLOCK ///////////////

      // if i'th local is not an arg, argIndex must be negative like -1
      def debugVarNode(i: Int, method: Method, lvt: Method.LocalVariablesTable, argIndex: Int = -1): StackAlloc = {
        val name = lvt.localName(i)
        val symType = typeProvider.parseSingleElementSignature(lvt.localSignature(i))
        val isPointer = symType.isTraceableReference

        val varType = JavaDwarfTypes.typeToDebugType(symType)

        val decl = None // Decl is optional, when required - extract decl info from LVT.
        val info = DebugLocalVar(name, varType, argIndex, isPointer, decl)

        StackAlloc.DebugVar(symType, info)
      }

      def parseProlog(): Unit = {
        bc = 0 // prolog code is treated as bytecode with position 0

        var localIdx = 0
        val lvt = method.codeAttribute.getLocalVariablesTable()
        for ((arg, i) <- args.zipWithIndex) {
          if (genDebug && lvt.nonEmpty) {
            // StackAlloc.DebugVar nodes should be used for args locals
            val dbgNode = debugVarNode(i, method, lvt.get, i)
            st(localIdx) = dbgNode
          }
          st(localIdx) = arg
          localIdx += method.getParamType(i).jbcKind.nslots
        }
        if (genDebug) {
          if (lvt.nonEmpty) {
            // StackAlloc.DebugVar nodes should be used for other locals
            val localsCount = lvt.map(_.localCount()).get
            var i = args.length
            while (i < localsCount) {
              val dbgNode = debugVarNode(i, method, lvt.get)
              val sigType = dbgNode match {
                case StackAlloc.DebugVar(t, _) => t
              }
              st(localIdx) = dbgNode
              localIdx += sigType.jbcKind.nslots
              i += 1
            }
          }
          DebugPrologueEndBreakpoint()
        }

        val methodHostClass = method.getDeclaringClass

        if (env.enabled(PreparationAsserts) && managedContext && methodHostClass.preparationRequired) {
          PreparationCheck(methodHostClass, PreparationKind.PROLOGUE_ASSERTION)()
        }

        if (method.isStatic && methodHostClass.hasRunTimeTypeInfo) {
          if (managedContext) {
            if (!method.isPreClinited) {
              Clinit(methodHostClass)()
            } else if (Env.isWorkMode && !methodHostClass.isPreClinited) {
              // Verify clinit optimizations in static non-clinit methods.
              // We could not create "trusted" clinit check because it will be removed by context types.
              ClinitedAssert(methodHostClass)()
            }

          } else if (Env.isWorkMode && !methodHostClass.isPreClinited) {
            InitializedAssert(methodHostClass)()
          }
        }

        if (env.isTurboClinitHost(method)) {
          for (c <- typeProvider.getTurboClinitedClasses) {
            assert(!c.isPreClinited && !c.isTurboClinitedIn(method))
            Clinit(c)()
          }
        }
      }

      //////////// BYTECODE EXCEPTION TABLES ///////////////

      def parseExStuff(kind: ExceptionStuffBlock): Unit = {
        bc = Position.offset(block.pos) getOrElse -1
        kind match {
          case XBlockKind(None) =>
            st.xobj = block.asInstanceOf[XBlock].catchNode
          case XBlockKind(Some(domain)) =>
            st.xobj = ConvertDomain(domain)(block.asInstanceOf[XBlock].catchNode)

          case ThrowBlock =>
            withPos(currentMethodSyntheticPos) { makeThrow(st.xobj) }
            st.xobj = Invalid

          case TransitionToHandler =>
            st push st.xobj
            st.xobj = Invalid

          case ExceptionCheck(catchType) =>
            // TODO-SYMLEVEL think about cast
            val iof = instanceOf(catchType, st.xobj)
            makeIf(Cmp(iof.tpe, Condition.NE)(iof, IConst(0)))
        }
      }

      //////////// COMMON ///////////////

      private var lastPosition: BytecodePosition = _

      override def startInstruction(offset: Int, nextOffset: Int): Unit = {
        bc = offset
        if (method.isStrictMemory) {
          MemBarrier(Set(STRICT_MEM))()
        }
        if (genDebug) {
          val lineNumber = method.codeAttribute.findLineNumber(offset)
          val position = BytecodePosition(BytecodeOffset.SYNTHETIC, lineNumber, ColumnNumber.UNKNOWN, currentInlineContext)
          if (lastPosition == null || lastPosition != position) {
            withPos(position) { DebugTextPosBreakpoint() }
            lastPosition = position
          }
        }
      }

      def haltBlock(haltProto: Halt.Proto): Nothing = {
        removeBlockEnd(block.blockEnd)
        haltProto()
        blockParsing.break()
      }

      def makeReturn(retValue: Node): Unit = {
        val ret = block.blockEnd.asInstanceOf[Return]
        val proxy = ret.inValue
        assert(proxy.isInstanceOf[Proxy] && proxy.singleUse == ret)
        proxy.replaceBy(retValue)
      }

      def makeThrow(xobj: Node): Unit = {
        Throw(xobj)
      }

      def makeBranch(branch: Branch, selector: Node): Unit = {
        val proxy = branch.selector
        assert(proxy.isInstanceOf[Proxy] && proxy.singleUse == branch)
        proxy.replaceBy(selector)
        adjustBlockEnd()
        tryEliminateConstBranch(branch)
      }

      def makeIf(condition: Node): Unit = {
        makeBranch(block.blockEnd.asInstanceOf[If], condition)
      }

      def makeSwitch(selector: Node): Unit = {
        makeBranch(block.blockEnd.asInstanceOf[Switch], selector)
      }

      def nullCheck(obj: Node, forceTrusted: Boolean = false): Unit = {
        if (obj.tpe == ThinType) {
          assert(!forceTrusted)
          ThinNullCheck(trusted = noNullCheck)(obj)
        } else {
          NullCheck(trusted = forceTrusted || noNullCheck || !managedContext)(obj)
        }
      }

      def clinitCheck(klass: symlevel.ClassType): Unit = {
        if (managedContext) {
          Clinit(klass)()
        } else if (Env.isWorkMode && !klass.isPreClinited) {
          InitializedAssert(klass)()
        }
      }

      def pushCPEntry(index: Int): Unit = {
        import bytecode.Tag.*
        import com.huawei.excelsior.jet.compiler.bytecode.ConstantPoolAccessResult.*

        val node = (cp.getTag(index): @unchecked) match {
          case INTEGER => IConst(cp.getInt(index))
          case LONG =>    LConst(cp.getLong(index))

          case FLOAT =>   FConst(cp.getFloat(index))
          case DOUBLE =>  DConst(cp.getDouble(index))

          case STRING =>
            val constStr = cp.getConstString(index)

            if (managedContext) {
              ensurePrepared(PreparationRequired.forConstString(constStr))
            } else {
              // Nothing to do. ConstString are allowed in unmanaged context only for AJ intrinsics implementation.
              // If any one will survive through compiler, assert in lowering will fail.
            }

            // The host check is possible because AJ, Java and Scala classes contain only their own string literals.
            val strType = if (constStr.getHost.isJavaReference) {
              typeProvider.getStringType
            } else if (constStr.getHost.isXScalaType) {
              typeProvider.getXScalaString
            } else {
              typeProvider.getAJStringType
            }
            // It is controlled as a workaround for JET-10876.
            // Bind it to entry of current method where current class must be already prepared.
            ConstString(constStr, strType).withExplicitArgs(entryBlock)

          case CLASS =>
            val access = cp.getType(index)
            access.getResult match {
              case OK =>
                if (managedContext) {
                  ClassObject(access.getObject)()
                } else {
                  Null()   // argument of intrinsic, ignore it
                }

              case DEFERRED =>
                tryDeferred(access.getObject.getName) {
                  Deferred.ClassObject(index)()
                }

              case ERROR =>
                throwErrorAndHalt(access.getError)
            }

          case METHOD_TYPE => Deferred.MethodType(index)()

          case METHOD_HANDLE => Deferred.MethodHandle(index)()
        }

        st push node
      }

      def pushConst(tkind: BytecodeTypeKind, value: Int): Unit = {
        val node = (tkind: @unchecked) match {
          case BytecodeTypeKind.DOUBLE => DConst(value.toDouble)
          case BytecodeTypeKind.FLOAT  => FConst(value.toFloat)
          case BytecodeTypeKind.LONG   => LConst(value.toLong)
          case BytecodeTypeKind.INT | BytecodeTypeKind.BYTE | BytecodeTypeKind.SHORT => IConst(value)
          case BytecodeTypeKind.CLASS  => assert(value == 0); Null()
        }
        st push node
      }

      private def checkLocal(tkind: BytecodeTypeKind, node: Node): Unit = {
        if (tkind.isReference) {
          assert(node.tpe.isTraceableRefType || node.tpe == ThinType || node.tpe == ReturnAddressType)
        } else {
          // Note: do not forget about "bottom" type. TODO: should we explicitly check that node.isInstanceOf[NoValue] here?
          assert(Type.lteq(node.tpe, ValueType(fromBytecode(tkind))))
        }
      }

      def pushLocal(tkind: BytecodeTypeKind, index: Int): Unit = {
        val node = st(index)
        checkLocal(tkind, node)
        st push node
      }

      def storeLocal(tkind: BytecodeTypeKind, index: Int): Unit = {
        val node = st.pop()
        checkLocal(tkind, node)
        st(index) = node
      }

      def arithOp(tkind: BytecodeTypeKind, op: ArithOp): Unit = {
        import ArithOp.*

        val tpe = ValueType(fromBytecode(tkind))
        val node = if (op == NEG) {
          val a = st.pop()
          Neg(tpe)(a)

        } else {
          val a2 = st.pop()
          val a1 = st.pop()
          (op: @unchecked) match {
            case ADD  => Add(a1, a2)
            case SUB  => Sub(a1, a2)

            case MUL  => Mul(a1, a2)

            case DIV | REM =>
              if (tpe.isIntegralType) {
                DivisorCheck(trusted = !managedContext)(a2)
                op match {
                  case DIV => IDiv(tpe)(a1, a2)
                  case REM => IRem(tpe)(a1, a2)
                  case _ => shouldNotReachHere(op)
                }
              } else {
                assert(tpe.isFloatingPointType)
                op match {
                  case DIV => FDiv(tpe)(a1, a2)
                  case REM => FRem(tpe)(a1, a2)
                  case _ => shouldNotReachHere(op)
                }
              }

            case AND  => And(a1, a2)
            case OR   => Or(a1, a2)
            case XOR  => Xor(a1, a2)


            case CMP | CMPL | CMPG => ThreeCmp(tpe, op)(a1, a2)
            case LSL | ASR | LSR => Shift(op, a1, a2)
          }
        }
        st push node
      }

      def convert(op: ConvertOp): Unit = {
        val from = op.srcKind
        val to   = op.dstKind

        val arg  = st.pop()
        val value = JavaConvert(from, to)(arg)
        st push value
      }

      def stackOp(op: Bytecode): Unit = {
        val depth = st.stackDepth
        def dropped(n: Int) = (st.stackDepth == depth - n)
        def shouldDrop(n: Int): Unit = { assert(dropped(n)) }
        def pop2() = (st.pop(), st.pop())

        (op: @unchecked) match {
          case POP =>
            st.pop()
            shouldDrop(1)

          case POP2 =>
            st.pop()
            if (dropped(1)) {
              st.pop()
            }
            shouldDrop(2)

          case SWAP =>
            val (v1, v2) = pop2()
            shouldDrop(2)
            st.push(v1, v2)

          case DUP =>
            val x = st.pop()
            shouldDrop(1)
            st.push(x, x)

          case DUP_X1 =>
            val (v1, v2) = pop2()
            shouldDrop(2)
            st.push(v1, v2, v1)

          case DUP_X2 =>
            val v1 = st.pop()
            shouldDrop(1)
            val v2 = st.pop()
            if (dropped(2)) {
              val v3 = st.pop()
              shouldDrop(3)
              st.push(v1, v3, v2, v1)
            } else {
              shouldDrop(3)
              st.push(v1, v2, v1)
            }

          case DUP2 =>
            val v1 = st.pop()
            if (dropped(1)) {
              val v2 = st.pop()
              shouldDrop(2)
              st.push(v2, v1, v2, v1)
            } else {
              shouldDrop(2)
              st.push(v1, v1)
            }

          case DUP2_X1 =>
            val v1 = st.pop()
            if (dropped(1)) {
              val (v2, v3) = pop2()
              shouldDrop(3)
              st.push(v2, v1, v3, v2, v1)
            } else {
              val v2 = st.pop()
              shouldDrop(3)
              st.push(v1, v2, v1)
            }

          case DUP2_X2 =>
            val v1 = st.pop()
            if (dropped(1)) {
              val v2 = st.pop()
              shouldDrop(2)
              val v3 = st.pop()
              if (dropped(3)) {
                val v4 = st.pop()
                shouldDrop(4)
                st.push(v2, v1, v4, v3, v2, v1)
              } else {
                shouldDrop(4)
                st.push(v2, v1, v3, v2, v1)
              }
            } else {
              shouldDrop(2)
              val v2 = st.pop()
              if (dropped(3)) {
                val v3 = st.pop()
                shouldDrop(4)
                st.push(v1, v3, v2, v1)
              } else {
                shouldDrop(4)
                st.push(v1, v2, v1)
              }
            }

        }
      }

      def increment(local: Int, delta: Int): Unit = {
        st(local) = Add(st(local), IConst(delta))
      }

      override def unaryIf(tkind: BytecodeTypeKind, op: CompareOp, bc: Int): Unit = {
        val arg = st.pop()
        val cmpType = tkind match {
          case BytecodeTypeKind.INT => IntType
          case BytecodeTypeKind.CLASS => arg.tpe
          case _ => shouldNotReachHere(tkind)
        }
        val nullValue: Node = cmpType match {
          case IntType => IConst(0)
          case _ => AnyNull(cmpType)
        }
        makeIf(Cmp(cmpType, Condition(op))(arg, nullValue))
      }

      override def binaryIf(tkind: BytecodeTypeKind, op: CompareOp, bc: Int): Unit = {
        val a2 = st.pop()
        val a1 = st.pop()
        val cmpType = tkind match {
          case BytecodeTypeKind.INT => IntType
          case BytecodeTypeKind.CLASS => a1.tpe | a2.tpe
          case _ => shouldNotReachHere(tkind)
        }
        makeIf(Cmp(cmpType, Condition(op))(a1, a2))
      }

      override def tableSwitch(bcDefault: Int, lowMatch: Int, highMatch: Int, bcTargets: Array[Int]): Unit = {
        makeSwitch(st.pop())
      }

      override def lookupSwitch(bcDefault: Int, matches: Array[Int], bcTargets: Array[Int]): Unit = {
        makeSwitch(st.pop())
      }

      def jump(bc: Int): Unit = {
        // do nothing
      }

      def ret(param: Int): Unit = {
        assert(st(param).tpe == ReturnAddressType)
      }

      def jsr(bc: Int): Unit = {
        st push ReturnAddress()
      }

      def doReturn(tkind: BytecodeTypeKind, isLastBytecode: Boolean): Unit = {
        makeReturn( if (tkind.isVoid) Void() else st.pop() )
      }

      def fieldOp(index: Int, akind: FieldAccessKind): Unit = {
        import ConstantPoolAccessResult.*

        val fieldAccess = cp.getField(index, akind)
        fieldAccess.getResult match {
          case OK | DEFERRED =>
            val field = fieldAccess.getObject

            assert(akind.isInstance == !field.isStatic)

            val value = if (akind.isWrite) st.pop() else null
            val obj = if (akind.isInstance) st.pop() else null

            fieldOpImpl(index, cp.getFieldRefClass(index), field, obj, value)

          case ERROR =>
            throwErrorAndHalt(fieldAccess.getError)
        }
      }

      def fieldOpImpl(index: Int, refClass: symlevel.Type, field: Field, obj: Node, value: Node): Unit = {
        val tpe = ValueType.fromSig(field.getType)

        val write = value != null
        val statik = field.isStatic
        val absent = field.getDeclaringClass.isDeferred

        val volat = if (absent) {
          assert(index != DAIGenerator.NO_CP_INDEX)
          false // deferred thunks contain necessary barriers
        } else {
          field.isVolatile
        }

        val finalFieldsRequirePublicationBarrier = !env.enabled(GenerateWriteBarriers) // see JET-12699
        if (write && !statik && field.isFinal && method.isConstructor && (field.getDeclaringClass == method.getDeclaringClass) && finalFieldsRequirePublicationBarrier) {
          needMemBarBeforeReturn = true
        }

        if (!absent) {
          if (!statik) {
            nullCheck(obj)
          } else if (field.getDeclaringClass.hasRunTimeTypeInfo) {
            clinitCheck(field.getDeclaringClass)
            if (env.enabled(ForceAddAggressiveClinitAnalysisAssert) &&
                !write && !method.isClinit &&
                isFieldAnalyzableByClinitAnalysis(field) && isAggressiveClinitAnalysisAllowedFor(field.getDeclaringClass)) {

              AggressiveClinitAnalysisAssert(field)()
            }
          }
        }

        def doFieldOp(): Unit = {

          if (env.enabled(GenerateWriteBarriers) && write && field.getType.isTraceableReference) {
            if (statik) {
              if (currentInlineContext.method.isManaged) {
                WriteBarrier.static(value)
              } else {
                VerificationStaticWriteBarrier(value)
              }
            } else {
              if (currentInlineContext.method.isManaged) {
                WriteBarrier.instance(obj, value)
              } else {
                VerificationInstanceWriteBarrier(obj, value)
              }
            }
          }

          val op = if (absent) {
            tryDeferred(field.getFullName) {
              Deferred.FieldOp(index, field.getType, write, statik)(Deferred.FieldOp.makeArgs(obj, value, write, statik): _*)
            }

          } else {
            (write, statik) match {
              case (false, false) =>
                val g = GetField(field)(obj)
                // String.value field is known to be non-null, state it explicitly.
                // FIXME: use jca for this, but first fix JET-14280
                if (field == Java.Lang.String.value) {
                  NullCheck(trusted = true)(g)
                }
                g

              case (true,  false) => PutField(field)(obj, value)

              case (false, true)  =>
                if (!env.enabled(XGenAsserts) &&
                    field.isSynthetic && field.isFinal && field.getType.jbcKind == BytecodeTypeKind.BOOLEAN && field.getName == "$assertionsDisabled") {
                  // Completely remove Java assertion check.
                  IConst(1)
                } else {
                  ensurePrepared(PreparationRequired.forGetStatic(field))
                  GetStatic(field)
                }

              case (true,  true)  =>
                ensurePrepared(PreparationRequired.forPutStatic(field))
                PutStatic(field)(value)
            }
          }

          if (!write) {
            st push op
          }
        }

        if (write) {
          if (volat) MemBarrier(Set(LOAD_STORE, STORE_STORE))()
          doFieldOp()
          if (volat) MemBarrier(Set(STORE_LOAD, STORE_STORE))()
        } else {
          doFieldOp()
          if (volat) MemBarrier(Set(LOAD_LOAD, LOAD_STORE))()
        }
      }

      def arrayLength(): Unit = {
        val obj = st.pop()
        nullCheck(obj)
        st push jbcArrayLength(obj)
      }

      def jbcArrayLength(obj: Node) = {
        if (rootDeclaringClass.isXScalaType) {
          ScalaArrayLength(obj)
        } else {
          JavaArrayLength(obj)
        }
      }

      private def arrayOp(put: Boolean, tkind: TKind): Unit = {
        val arrayType = SignatureType.fromSymType(typeProvider.get1DimArrayType(tkind))
        val value   = if (put) st.pop() else null
        val idx     = st.pop()
        val arrObj  = st.pop()

        // Array aggregate optimization is afraid of checks, all of them should be eliminated.
        // NC is optimized by context types, but AIC & ASC are not.

        nullCheck(arrObj)

        val arrLength = jbcArrayLength(arrObj)

        val needIndexCheck = (idx, arrLength) match {
          case (IConst(index), IConst(arrLen)) if (0 <= index) && (index < arrLen) => false
          case _ => true
        }
        if (needIndexCheck) ArrayIndexCheck(arrayType, trusted = noArrayIndexCheck || !managedContext)(arrObj, idx, arrLength)

        val needStoreCheck = put && tkind.isReference && {
          val reallyNeed = (value, arrObj) match {
            case (_: AnyNull, _) => false

            case (cs: ConstString, newArray: AnyNewArray) if !newArray.allocType.isDeferred =>
              // Special handling for string put into new array,
              // general optimization of ArrayStoreCheck is done later.
              val arrType = JavaArrayType(newArray.allocType)
              // TODO: use hierarchy entity and eliminate branching
              if (cs.str.getHost.isXScalaType) {
                !(arrType.arrayElement.asInstanceOf[ReferenceType] >= ReferenceType.xscalaString)
              } else {
                !(arrType.arrayElement.asInstanceOf[ReferenceType] >= ReferenceType.javaLangString)
              }

            case _ => true
          }
          if (!reallyNeed) stats.count(StatsKind.TypeOpt, "arraystorecheck striked out trivial", currentPosition())
          reallyNeed
        }
        if (needStoreCheck) ArrayStoreCheck(arrayType, trusted = noArrayStoreCheck || !managedContext)(arrObj, value)

        if (put) {
          if (env.enabled(GenerateWriteBarriers) && tkind.isReference) {
            if (currentInlineContext.method.isManaged) {
              WriteBarrier.instance(arrObj, value)
            } else {
              VerificationInstanceWriteBarrier(arrObj, value)
            }
          }

          if (!collectArrayAggregate(arrayType, arrObj, idx, value)) {
            ArrayPut(arrayType)(arrObj, idx, value)
          }
        } else {
          st push ArrayGet(arrayType)(arrObj, idx)
        }

      }

      def arrayGet(btkind: BytecodeTypeKind): Unit = { arrayOp(put = false, fromBytecode(btkind)) }

      def arrayPut(btkind: BytecodeTypeKind): Unit = { arrayOp(put = true, fromBytecode(btkind)) }

      private val MAX_JVM_ARITY = 255 // this is mandated by the JVM spec.

      private def createInvokeDynamicOrSigPoly(index: Int, refKind: DAIRefKind, methodType: MethodType, args: Seq[Node]): Deferred = {
        // Runtime code (j.l.i.MethodHandleNatives) defines when appendix argument is null or not null.
        // To simplify this logic we statically assume that all methods have appendix argument
        // except methods with MAX_JVM_ARITY arguments (because they have no place for extra argument).
        // This assumption is verified after resolve of the invoke via assert in RT code.
        val hasAppendix = (methodType.parameterSlotCount + 1) /*appendix*/ <= MAX_JVM_ARITY
        val (newMethodType, newArgs) = if (hasAppendix) {
          (methodType.appendParameterType(SignatureType.javaLangObject), args :+ Null())
        } else (methodType, args)

        Deferred.DynamicOrSigPolyInvoke(index, refKind, newMethodType, hasAppendix)(newArgs: _*)
      }

      def invoke(index: Int, akind: MAK): Unit = {
        import BitFieldExtract.*
        import ConstantPoolAccessResult.*

        val methodTypeErased = MethodType.jbcErased(cp.getRefSignature(index), typeProvider, akind.hasObjectArg)

        var targetArgs = IndexedSeq.fill(methodTypeErased.parameterCount)(st.pop()).reverse

        val dynOrSigPolyInvoke: Option[Node] = akind match {
          case MAK.VIRTUAL | MAK.STATIC if cp.isMethodSignaturePolymorphic(index) =>
            val sigPolyMethodID = cp.getSignaturePolymorphicMethodID(index)
            assert((sigPolyMethodID.isStatic && akind == MAK.STATIC) || akind == MAK.VIRTUAL)

            if (sigPolyMethodID.isMethodHandleInvoker) {
              assert(!sigPolyMethodID.isStatic)
              Some(createInvokeDynamicOrSigPoly(index, DAIRefKind.INVOKE_SIGPOLY, methodTypeErased, targetArgs))
            } else {
              assert(sigPolyMethodID == SigPolyMethodID.INVOKE_BASIC)
              Some(Deferred.SigPolyInvokeBasic(index, methodTypeErased)(targetArgs: _*))
            }
          case MAK.DYNAMIC =>
            LambdaTypeGenerator(_.getLambdaConstructor(rootDeclaringClass, index)) match {
              case None | Some(null) =>
                if (languagePack == LanguagePack.SCALA) {
                  RTSCall(RTSProc.JR_FatalError)(AJString.bstr(s"notImplemented lambda with deferred types: $rootDeclaringClass#$index"))
                  haltBlock(Halt.afterRTSCall(RTSProc.JR_FatalError, s"notImplemented lambda with deferred types: $rootDeclaringClass#$index"))
                  return
                } else {
                  Some(createInvokeDynamicOrSigPoly(index, DAIRefKind.INVOKE_DYNAMIC, methodTypeErased, targetArgs))
                }

              case Some(lambdaConstr) =>
                val newNode = createNew(lambdaConstr.method.getDeclaringClass)
                createInvoke(lambdaConstr, newNode +: targetArgs)
                Some(newNode)
            }
          case _ => None
        }

        if (dynOrSigPolyInvoke.nonEmpty) {
          if (!methodTypeErased.returnType.isZST) {
            st push dynOrSigPolyInvoke.get
          }
          return
        }

        val methodReferenceAccess = cp.getMethodReference(index, akind)

        val result = methodReferenceAccess.getResult match {
          case OK =>
            var targetRef = methodReferenceAccess.getObject
            if (targetRef.methodType.isVarArgs) {
              val VarArgsList(varArgs, varArgTypes) = targetArgs.last
              targetArgs = targetArgs.init ++ varArgs
              targetRef = targetRef.withMethodType(targetRef.methodType.appendVarArgs(varArgTypes)).asInstanceOf[BytecodeMethodReference]
            }

            val target = targetRef.method
            val ajCallKind = target.getAJCallKind

            ajCallKind match {
              case MethodAJCallKind.NORMAL =>
                createInvoke(targetRef, targetArgs)

              case MethodAJCallKind.UNCHECKED_CALL  =>
                createInvoke(target.getUncheckedCallTargetRef, targetArgs)

              case MethodAJCallKind.UNCHECKED_NEW  =>
                assert(managedContext)
                val targetInit = target.getUncheckedNewTargetRef
                val newNode = createNew(targetInit.method.getDeclaringClass)
                createInvoke(targetInit, newNode +: targetArgs)
                newNode

              case MethodAJCallKind.INDIRECT_CALL =>
                createInvoke(targetRef, targetArgs)

              case MethodAJCallKind.CALL_TO_MANAGED =>
                assert(!managedContext)
                createInvoke(targetRef, targetArgs)

              case MethodAJCallKind.THIN_UNCHECKED_CAST => targetArgs match {
                case Seq(thin) =>
                  val targetType = target.getDeclaringClass
                  assert(targetType.isThinClass)
                  ThinCheckCast(targetType, trusted = true)(thin)
                  thin
              }

              case MethodAJCallKind.GET_FLAT_THIN_INTRINSIC => targetArgs match {
                case Seq(struct, offset) =>
                  val targetType = target.getDeclaringClass
                  assert(targetType.isThinClass)
                  if (env.enabled(OptimizeGetFlatThin)) {
                    // These nodes are high-level operations with optimizations and context types. Thus they can be
                    // optimized better than pre-lowered patterns written below. But their optimizations provoke GVN
                    // and code motion to extra execution paths, which decrease interpreter performance by 25%.
                    // TODO: enable in the best future, where BGCM will handle these problems.
                    GetFlatThinCheck(struct, offset)
                    GetFlatThin(targetType)(struct, offset)
                  } else {
                    val addr = Add(struct, Extend(AddrType, AsmType.I32, signExtension = true, offset))
                    val thin = ReinterpretCast(AddrType, ThinType)(addr)
                    ThinCheckCast(targetType, trusted = true)(thin)
                    thin
                  }
              }

              case MethodAJCallKind.INTRINSIC_CALL | MethodAJCallKind.INTRINSIC_WITH_BODY_CALL =>
                target.getAJCallKind match {
                  case MethodAJCallKind.INTRINSIC_CALL =>
                    def fieldOpIntrinsic(obj: Node, value: Node, className: ConstString, fieldName: ConstString): Unit = {
                      val clazz = typeProvider.resolveTypeByName(method.getDeclaringClass, className.stringValue.replace('.', '/'))
                      assert(clazz.isClassOrInterface)
                      assert(!clazz.isThinClass)
                      val field = clazz.findField(fieldName.stringValue)
                      fieldOpImpl(DAIGenerator.NO_CP_INDEX, clazz, field, obj, value)
                    }

                    //to avoid copy&paste we process field access intrinsics here in dataflow
                    target.getIntrinsicType match {
                      case JavaFieldAccess_getBoolean | JavaFieldAccess_getByte | JavaFieldAccess_getChar | JavaFieldAccess_getDouble |
                           JavaFieldAccess_getFloat | JavaFieldAccess_getInt | JavaFieldAccess_getLong | JavaFieldAccess_getObject |
                           JavaFieldAccess_getAJObject | JavaFieldAccess_getShort |
                           AJFieldAccess_getBoolean | AJFieldAccess_getByte | AJFieldAccess_getChar | AJFieldAccess_getDouble |
                           AJFieldAccess_getFloat | AJFieldAccess_getInt | AJFieldAccess_getLong | AJFieldAccess_getObject |
                           AJFieldAccess_getShort => targetArgs match {
                        case Seq(obj, className: ConstString, fieldName: ConstString) =>
                          fieldOpIntrinsic(obj, null, className, fieldName)
                          return // result is already pushed on stack
                      }

                      case JavaFieldAccess_setBoolean | JavaFieldAccess_setByte | JavaFieldAccess_setChar | JavaFieldAccess_setDouble |
                           JavaFieldAccess_setFloat | JavaFieldAccess_setInt | JavaFieldAccess_setLong | JavaFieldAccess_setObject |
                           JavaFieldAccess_setAJObject | JavaFieldAccess_setShort |
                           AJFieldAccess_setBoolean | AJFieldAccess_setByte | AJFieldAccess_setChar | AJFieldAccess_setDouble |
                           AJFieldAccess_setFloat | AJFieldAccess_setInt | AJFieldAccess_setLong | AJFieldAccess_setObject |
                           AJFieldAccess_setShort => targetArgs match {
                        case Seq(obj, value, className: ConstString, fieldName: ConstString) =>
                          fieldOpIntrinsic(obj, value, className, fieldName)
                          return // result is already pushed on stack
                      }

                      case JavaFieldAccess_getLength => targetArgs match {
                        case Seq(obj) =>
                          nullCheck(obj)
                          jbcArrayLength(obj)
                      }

                      case DelayedIntrinsics_getObject => targetArgs match {
                        case Seq(obj, className: ConstString, fieldName: ConstString) =>
                          val cz = typeProvider.findClass(className.stringValue)
                          if (cz == null) {
                            DelayedGet(className.stringValue, fieldName.stringValue, TRefType)(obj)
                          } else {
                            fieldOpIntrinsic(obj, null, className, fieldName)
                            return // result is already pushed on stack
                          }
                      }

                      case DelayedIntrinsics_setObject => targetArgs match {
                        case Seq(obj, value, className: ConstString, fieldName: ConstString) =>
                          val cz = typeProvider.findClass(className.stringValue)
                          if (cz == null) {
                            DelayedPut(className.stringValue, fieldName.stringValue, TRefType)(obj, value)
                          } else {
                            fieldOpIntrinsic(obj, value, className, fieldName)
                            return // result is already pushed on stack
                          }
                      }

                      case DelayedIntrinsics_getInt => targetArgs match {
                        case Seq(obj, className: ConstString, fieldName: ConstString) =>
                          val cz = typeProvider.findClass(className.stringValue)
                          if (cz == null) {
                            DelayedGet(className.stringValue, fieldName.stringValue, IntType)(obj)
                          } else {
                            fieldOpIntrinsic(obj, null, className, fieldName)
                            return // result is already pushed on stack
                          }
                      }

                      case DelayedIntrinsics_setInt => targetArgs match {
                        case Seq(obj, value, className: ConstString, fieldName: ConstString) =>
                          val cz = typeProvider.findClass(className.stringValue)
                          if (cz == null) {
                            DelayedPut(className.stringValue, fieldName.stringValue, IntType)(obj, value)
                          } else {
                            fieldOpIntrinsic(obj, value, className, fieldName)
                            return // result is already pushed on stack
                          }
                      }

                      case DelayedIntrinsics_getLong => targetArgs match {
                        case Seq(obj, className: ConstString, fieldName: ConstString) =>
                          val cz = typeProvider.findClass(className.stringValue)
                          if (cz == null) {
                            DelayedGet(className.stringValue, fieldName.stringValue, LongType)(obj)
                          } else {
                            fieldOpIntrinsic(obj, null, className, fieldName)
                            return // result is already pushed on stack
                          }
                      }

                      case DelayedIntrinsics_setLong => targetArgs match {
                        case Seq(obj, value, className: ConstString, fieldName: ConstString) =>
                          val cz = typeProvider.findClass(className.stringValue)
                          if (cz == null) {
                            DelayedPut(className.stringValue, fieldName.stringValue, LongType)(obj, value)
                          } else {
                            fieldOpIntrinsic(obj, value, className, fieldName)
                            return // result is already pushed on stack
                          }
                      }

                      case _ => loadIntrinsic(target, target.getIntrinsicType, method, targetArgs)
                    }

                  case MethodAJCallKind.INTRINSIC_WITH_BODY_CALL =>
                    Option(target.getIntrinsicWithBodyType)
                      .flatMap(itype => loadIntrinsicWithBody(target, itype, method, targetArgs))
                      .getOrElse(createInvoke(targetRef, targetArgs))

                  case x => shouldNotReachHere(x)
                }
            }

          case DEFERRED =>
            val methodRef = methodReferenceAccess.getObject
            tryDeferred(s"${methodRef.refClass.getName}.${methodRef.methodName}") {
              Deferred.UnresolvedInvoke(index, methodRef)(targetArgs: _*)
            }

          case ERROR =>
            throwErrorAndHalt(methodReferenceAccess.getError)
        }

        if (!methodTypeErased.returnType.isZST) {
          st push result
        }
      }

      private def createInvoke(targetRef: MethodReference, targetArgs: Seq[Node]) = {
        val target = targetRef.method
        val refClass = targetRef.refClass

        def receiver = { assert(targetRef.hasReceiverParameter); targetArgs(targetRef.getReceiverArgIndex)}

        if (!target.isStatic) {
          // De facto, Unsafe instance is always non-null. Also note that all its methods are static-like.
          val trustedUnsafeCall =
            !env.enabled(NoAggressiveUnsafeNullCheckElimination) &&
              rootDeclaringClass.isOptimizedAggressively &&
              target.getDeclaringClass.isSunMiscUnsafe
          nullCheck(receiver, forceTrusted = trustedUnsafeCall)
          if (trustedUnsafeCall) {
            stats.count(StatsKind.UnsafeOpt, "remove nullcheck", currentPosition())
          }
        }

        if (target.isThinConstructor) {
          assert(target.isStatic)
          nullCheck(targetArgs.head)
        }

        ensurePrepared(PreparationRequired.forInvoke(targetRef))
        val invoke = if (target.isAJDelayedIntrinsic) {
          val hasZSTRetByVal = target.getMethodType.hasRetByValParameter && target.getReturnType.isZST
          val adjustedArgs = Option.when(hasZSTRetByVal)(Void()).toSeq ++ targetArgs
          val n = DelayedMethodAddr(target.getAJDelayedIntrinsicClassName, target.getAJDelayedIntrinsicName)()
          Call(targetRef.withMethodType(targetRef.realMethodType))(n +: adjustedArgs*)

        } else if (target.isIndirectCall) {
          assert(targetRef.accessKind == MethodReferenceAccessKind.STATIC)
          assert(targetRef.methodType.parameterCount == targetRef.realMethodType.parameterCount + 1)
          Call(targetRef.withMethodType(targetRef.realMethodType))(targetArgs*)

        } else if (targetRef.isInterfCall) {
          if (target.getDeclaringClass.isXScalaAnyRef || target.getDeclaringClass.isJavaLangObject) {
            // Do early deinterfization of such cases for O1 (to avoid special handling of such calls in lowering)
            val deinterfRef = targetRef.withRefClassAndAccessKind(CompiledType(target.getDeclaringClass), MethodReferenceAccessKind.VIRTUAL)
            Invoke(deinterfRef)(targetArgs*)

          } else {
            val ciao = WeakCast(refClass)(receiver, WeakCast.NoCheck())
            InvokeInterface(targetRef, ciao)(targetArgs*)
          }

        } else {
          val devirtRef = if (target.isAJInlineForced && targetRef.accessKind == MethodReferenceAccessKind.VIRTUAL) {
            // Do early devirtualization of such cases to not waste time later
            // (and in case regular devirtualization is disabled).
            assert(target.isFinal || refClass.isFinal || refClass.isUltraThinClass)
            targetRef.withAccessKind(MethodReferenceAccessKind.SPECIAL)
          } else {
            targetRef
          }
          Invoke(devirtRef)(targetArgs*)
        }

        invoke match {
          case AnyDirectCall(t) if t.isAjNoReturn || locallyAnalyzeMethod(t).exists(_.isNoReturn) =>
            if (t.isAjNoReturn) {
              stats.count(NoReturn, s"call of method ${t.getName} marked as 'NoReturn' because it marked as 'AjNoReturn'")
            } else {
              stats.count(NoReturn, s"call of method ${t.getName} analyzed as 'NoReturn'")
            }
            haltBlock(Halt.explained("call marked as 'NoReturn'"))
          case _ => invoke
        }
      }

      def doNew(index: Int): Unit = {
        import ConstantPoolAccessResult.*
        assert(managedContext)

        val klassAccess = cp.getClassType(index)
        val newOp = klassAccess.getResult match {
          case OK =>
            createNew(klassAccess.getObject)

          case DEFERRED =>
            tryDeferred(klassAccess.getObject.getName) {
              Deferred.New(index)()
            }

          case ERROR =>
            throwErrorAndHalt(klassAccess.getError)
        }

        st push newOp
      }

      def createNew(klass: symlevel.ClassType): New = {
        if (!klass.isAbstractClass && !klass.isInterface) {
          clinitCheck(klass)
          ensurePrepared(PreparationRequired.forType(klass))
          New(SignatureType.fromSymType(klass))()

        } else {
          assert(!klass.isAJManagedType)
          if (klass.isXScalaType) {
            throwErrorAndHalt(RTSProc.JR_ThrowScalaInstantiationError, ImportedIndex(klass))
          } else {
            assert(klass.isJavaReference)
            throwErrorAndHalt(RTSProc.JR_ThrowInstantiationError, ImportedIndex(klass))
          }
        }
      }

      def doThrow(): Unit = {
        assert(managedContext)
        val xobj = st.pop()
        nullCheck(xobj)
        makeThrow(xobj)
      }

      private def instanceOf(typeAccess: Access[symlevel.ClassType], obj: Node): Node = {
        import ConstantPoolAccessResult.*

        typeAccess.getResult match {
          case OK =>
            val targetType = typeAccess.getObject
            if (targetType.isThinClass) {
              assert(targetType.isPolyThinClass)
              ThinInstanceOf(targetType)(obj)
            } else {
              assert(managedContext)
              InstanceOf(SignatureType.fromSymType(targetType))(obj)
            }

          case DEFERRED =>
            tryDeferred(typeAccess.getObject.getName) {
              Deferred.InstanceOf(typeAccess.getDeferredInfo.cpIndex)(obj)
            }

          case ERROR =>
            throwErrorAndHalt(typeAccess.getError)
        }
      }

      def instanceOf(index: Int): Unit =
        st push instanceOf(cp.getClassType(index), st.pop())

      def checkCast(index: Int): Unit = {
        import ConstantPoolAccessResult.*

        val obj = st.pop()

        val typeAccess = cp.getClassType(index)
        typeAccess.getResult match {
          case OK =>
            val targetType = typeAccess.getObject
            if (targetType.isThinClass) {
              assert(targetType.isPolyThinClass)
              ThinCheckCast(targetType)(obj)
            } else {
              // JET-15082 fix: ignore `checkcast` to `ManagedEopType`
              //
              // `ManagedEopType` is fake interface used to represent `ManagedEop` values in compiler.
              // No object implements this interface, therefore, `checkcast` to it will always fail.
              //
              // Moreover, `ManagedEop` may hold an enriched value, but `checkcast` implementation
              // will treat is as plain (see `TypeChecks#lowerInterfaceCast`, `IFaceOps#cast`).
              if (!typeProvider.isManagedEopUnderlyingType(targetType)) {
                if (!rootDeclaringClass.isXScalaType || targetType != typeProvider.getSerializableType) {
                  // scalac inserts such casts (e.g. in scala.collection.SetOps.concat)
                  CheckCast(SignatureType.fromSymType(targetType), trusted = !managedContext)(obj)
                }
              }
            }

          case DEFERRED =>
            tryDeferred(typeAccess.getObject.getName) {
              Deferred.CheckCast(index)(obj)
            }

          case ERROR =>
            throwErrorAndHalt(typeAccess.getError)
        }

        st push obj
      }

      override def newPrimitiveArray(btkind: BytecodeTypeKind): Unit = {
        val tkind = fromBytecode(btkind)

        assert(managedContext)
        assert(tkind.isPrimitive)

        val arrayType = typeProvider.getArraySigType(typeProvider.getPrimitiveType(tkind), 1)
        val len = st.pop()
        ensurePrepared(PreparationRequired.forType(arrayType))
        val node = NewArray(arrayType)(len)
        st push node
      }

      override def newObjectArray(index: Int): Unit = {
        import ConstantPoolAccessResult.*

        assert(managedContext)

        val klassAccess = cp.getType(index)
        klassAccess.getResult match {
          case OK | DEFERRED =>
            val klass = klassAccess.getObject
            val len = st.pop()

            val array = if (klass.isDeferred) {
              val allDimNum = 1 + (if (klass.isJBCArray) klass.getArrayDimnum else 0)
              tryDeferred(klass.getName) {
                Deferred.NewArray(index, allDimNum, 1)(len)
              }

            } else {
              val arrayType = typeProvider.getArrayType(klass, 1)
              ensurePrepared(PreparationRequired.forType(arrayType))
              NewArray(SignatureType.fromSymType(arrayType))(len)
            }
            st push array

          case ERROR =>
            throwErrorAndHalt(klassAccess.getError)
        }
      }

      override def newMultiObjectArray(index: Int, dimNum: Int): Unit = {
        import ConstantPoolAccessResult.*

        assert(managedContext)
        assert(dimNum > 0)

        val arrayTypeAccess = cp.getType(index)
        arrayTypeAccess.getResult match {
          case OK | DEFERRED =>
            val arrayType = arrayTypeAccess.getObject
            assert(arrayType.isJBCArray)
            val allDimNum = arrayType.getArrayDimnum
            assert(allDimNum >= dimNum)

            val dims = Seq.fill(dimNum)(st.pop()).reverse
            val array = if (arrayType.isDeferred) {
              tryDeferred(arrayType.getName) {
                Deferred.NewArray(index, allDimNum, dims.length)(dims: _*)
              }
            } else {
              ensurePrepared(PreparationRequired.forType(arrayType))
              NewArray(SignatureType.fromSymType(arrayType))(dims: _*)
            }
            st push array

          case ERROR =>
            throwErrorAndHalt(arrayTypeAccess.getError)
        }
      }

      // bytecode.parsing.ControlFlowParser intentionally places each monitor operation in the end of block so this method may not fail
      private def findMonitorEnter(block: BBlock) = ScalaCollections.firstElement(block.spineBackward) match {
        case Some(enter: MonitorEnter) => enter
        case _ => shouldNotReachHere(s"$block should contain MonitorEnter")
      }

      def monitorEnter(): Unit = {
        assert(managedContext)

        val outerRegion = cfState.outerMonitorBlockMap.get(block) map { outerEnterBlock =>
          val outerEnter = findMonitorEnter(outerEnterBlock)
          assert(outerEnter dominates block) // structured locking analyzer should provide this
          outerEnter.syncRegion
        }

        val obj = st.pop()
        val lockObj = getLockableObj(obj)
        nullCheck(lockObj)
        MonitorEnter(lockObj, SynchronizedRegion(outerRegion))
      }

      def monitorExit(): Unit = {
        assert(managedContext)

        val (syncRegion, requiresNC) =
          if (isUnstructuredLocking) {
            (MonitorExit.IntentionallyInvalidPairedEnter(), true)
          } else cfState.pairedEnterBlockMap.get(block) match {
            case Some(pairedEnterBlock) =>
              val enter = findMonitorEnter(pairedEnterBlock)
              assert(enter dominates block)
              // in case of structured locking it is guaranteed that obj is already null-checked
              (enter.syncRegion, false)

            case None =>
              shouldNotReachHere("locking is considered structured but we have no paired enter")
          }

        val obj = st.pop()
        val lockObj = getLockableObj(obj)
        nullCheck(lockObj, forceTrusted = !requiresNC)
        MonitorExit(lockObj, syncRegion)
      }

      private def getLockableObj(obj: Node): Node = nodeType(obj) match {
        // implicit synchronization on scala/runtime/LazyRef and other wrappers is may be inserted by scalac
        // in implementation of lazy val local variables, so we need to switch synchronization target to special injected lock field
        case tpe: UpperBounded if tpe.root.symType.isXScalaType => tpe.root.symType match {
          case Scala.Runtime.Support.LazyType(lazyType) =>
            val lazyField = lazyType._lock
            val lockField = XScala.Sync.LockJET.lock

            val lazyLock    = GetField(lazyField)(obj)
            val lockableObj = GetField(lockField)(lazyLock)
            lockableObj
        }
        case _  =>
          if (rootDeclaringClass.isXScalaType) {
            assert(rootMethod.getName == "sync" && rootDeclaringClass.getName == "xscala/sync/LockJET",
              "synchronization in Scala LP should be used only for Lock objects")
          }
          obj
      }

      def tryDeferred(errmsg: => String)(node: => Deferred): Deferred = {
        if (env.enabled(LogUnresolvedErrors)) {
          println(s"UNRESOLVED: deferred $errmsg at ${currentPosition()}")
        }

        if (languagePack.supports(JAVA) && env.enabled(IgnoreResolveErrors)) {
          node
        } else {
          RTSCall(RTSProc.JR_FatalError)(AJString.bstr(s"Unsupported deferred: $errmsg at ${currentPosition()}"))
          haltBlock(Halt.afterRTSCall(RTSProc.JR_FatalError, s"Unsupported deferred: $errmsg at ${currentPosition()}"))
        }
      }
    }
  }
}
