/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.
 * This source file is part of the Cangjie project, licensed under Apache-2.0
 * with Runtime Library Exception.
 *
 * See https://cangjie-lang.cn/pages/LICENSE for license information.
 */

package com.huawei.excelsior.jet.assembler

import com.huawei.excelsior.common.Arch
import com.huawei.excelsior.jet.assembler.Width.*
import com.huawei.excelsior.jet.assembler.fixups.{DataAlignment, Relocation, RelocationKind}
import com.huawei.excelsior.jet.assembler.fixups.RelocationKind.{ADDR32, ADDR64}
import xscala.io.ByteBuffer

import scala.annotation.nowarn
import scala.collection.mutable.ArrayBuffer

/** A machine-independent buffer for the generated code and data.
  * Contains a sequence of generated bytes, collection of fixups and collection of code labels.
  *
  * @author paul
  * @author cypok
  * @author conwor
  */
object Segment {
  val UNSPECIFIED_ALIGNMENT = -1
}

@nowarn("msg=match may not be exhaustive")
final class Segment(_symbol: Symbol) extends ByteBuffer {

  // Additional attributes
  private var alignment = Segment.UNSPECIFIED_ALIGNMENT
  private var symbol: Symbol = _symbol
  private var appended = false
  private var _frozen = false

  def this() = this(null) // TODO-DECAF: use default parameters

  def isBound = symbol != null

  def bind(symbol: Symbol): Unit = {
    assert(!isBound)
    this.symbol = symbol
  }

  def getSymbol = { // TODO-DECAF
    assert(isBound)
    symbol
  }

  def getAlignment = alignment // TODO-DECAF: rewrite to Scala getter/setter

  /** Sets alignment of segment's start. */
  def alignStart(alignment: Int): Unit = {
    assert(alignment != 0)
    if (this.alignment <= alignment) {
      this.alignment = alignment
    }
  }

  /** Ensures that segment's contents after current position will have given alignment.
    * Note that alignment is satisfied using `filler`.
    */
  override def align(alignment: Int, filler: Int): Unit =
    addFixup(new DataAlignment(alignment, filler))

  /** Marks this segment as appended to some other segment.
    *
    * After that this segment could not be used as normal segment any more,
    * because all its insides (labels, fixups, ...) have been moved to parent.
    */
  private def markAppended(): Unit = {
    appended = true
    _frozen = true

    // this will invalidate segment after appending
    bytes = null
    _length = 0
    alignment = 0
    symbol = null
    labels = null
    fixups = null
    literals = null
  }

  /** Appends `that` segment to `this` segment. Intentionally package-private. You should use Emitter.appendSegment, not this one. */
  def append(that: Segment): Unit = {
    assert(!this.frozen)
    assert(!that.frozen)
    assert(!this.appended)
    assert(!that.appended)
    assert(!that.isBound) // TODO: support this functionality
    assert(that.getAlignment == Segment.UNSPECIFIED_ALIGNMENT, "append of segments with custom alignment is not implemented")

    val thatOffset = this.length

    this.append(that: ByteBuffer)

    // Transform code labels from appended segment to this segment
    that.labels foreach (_.moveTo(this, thatOffset))

    this.fixups ++= that.fixups

    this.literals ++= that.literals

    that.markAppended()
  }

  /** Performs all actions required to fix size of segment and generate all additional data (literals).
    * Call to this method leads to establishing binary layout of the segment.
    */
  def freeze(): Unit = if (!frozen) {
    assert(literals.isEmpty)
    expandFixups()
    _frozen = true
  }

  def frozen = _frozen

  /** Performs segment freezing and resolve fixups, using given `fixupsConverter` for external fixups.
    * TODO: return bytes array from this method and remove getBytesPointer method.
    */
  def finish(fixupsConverter: Relocation.Converter): Unit = {
    freeze()
    fixups foreach (_.resolve(fixupsConverter))
    fixups.clear()
  }

  def fixupsIterator = fixups.iterator

  def fixupsLength = fixups.length


  ///////////////////////////////////////////////////////////////////////////////////////////////
  // Labels support

  private[assembler] var labels = new ArrayBuffer[Label]

  def newLabel = new Label

  // TODO: deduplicate labels bound to the same position?
  def bindLabel(label: Label): Unit = label.bind(this)

  def newBoundLabel = {
    val label = newLabel
    bindLabel(label)
    label
  }

  def getLabelPosition(label: Label) = {
    assert(frozen)
    assert(label.segment == this)
    label.position
  }

  def filterLabels(predicate: Label => Boolean) = labels.filter(predicate) // TODO-DECAF: remove


  ///////////////////////////////////////////////////////////////////////////////////////////////
  // Fixups support

  private var fixups = new ArrayBuffer[Fixup]

  def addFixup(fixup: Fixup): Unit = {
    bindLabel(fixup)
    fixups += fixup
    putZeroes(fixup.size)
  }

  def addDataAddress(target: Symbol, kind: RelocationKind): Unit =
    addFixup(new Relocation(kind, target, 0))

  def addDataAddress(target: Symbol, arch: Arch): Unit =
    addDataAddress(target, if (arch.is32Bit) ADDR32 else ADDR64)

  /** Returns sequence of fixups from `this` segment sorted by position. */
  def getFixups: collection.IndexedSeq[Fixup] = fixups


  ///////////////////////////////////////////////////////////////////////////////////////////////
  // Variable-size fixups support

  private def expandSegmentForVFixups(vFixups: Array[Fixup], originalPositions: Array[Int], originalSizes: Array[Int], newLength: Int): Unit = {
    val oldBytes = bytes
    val oldLength = length

    var alreadyCopiedBytes = 0
    assert(newLength > length)
    bytes = new Array[Byte](newLength)
    _length = 0 // always equal to (alreadyCopiedBytes + size of expanded vfs)

    for (i <- vFixups.indices) {
      // Copy bytes from previous vFixup until this vf
      val size = originalPositions(i) + originalSizes(i) - alreadyCopiedBytes
      Array.copy(oldBytes, alreadyCopiedBytes, bytes, length, size)
      alreadyCopiedBytes += size
      _length += size + vFixups(i).size - originalSizes(i)
    }

    // Copy remaining bytes.
    val size = oldLength - alreadyCopiedBytes
    Array.copy(oldBytes, alreadyCopiedBytes, bytes, length, size)
    _length += size
    assert(length == newLength)
  }

  /** Expands all variable-size fixups on demand. */
  private[assembler] def expandFixups(): Unit = {
    assert(!frozen)

    val vFixups = fixups.filter(_.isVariable).toArray

    val needToExpand = vFixups exists { f =>
      val delta = (f.expectedSize - f.size) ensuring (_ >= 0)
      delta != 0
    }

    if (needToExpand) {
      val originalPositions = vFixups.map(_.position)
      val originalSizes = vFixups.map(_.size)

      // Calculates segment's layout induced by expanded fixups. Sets positions of labels according with new
      // layout. Note that `labels` are populated on label binding, not creation, so they are ordered by
      // position. Fixups are sorted as well.
      var newLength = length

      // TODO-DECAF: improve and use WhileChanged
      var changed = true
      while (changed) {
        changed = false
        var delta = 0
        for (l <- labels) {
          changed |= (delta > 0)
          l.incrementPosition(delta)
          l match {
            case f: Fixup if f.isVariable =>
              delta += f.resize(-delta)
              assert(delta >= 0)
            case _ =>
          }
        }
        newLength += delta
      }

      expandSegmentForVFixups(vFixups, originalPositions, originalSizes, newLength)
    }

    vFixups foreach (_.freeze())
  }

  /** Returns length of segment only in case it doesn't have variable fixups. */
  def getActualLength = {
    assert(!hasVariableFixups)
    length
  }

  private def hasVariableFixups: Boolean = fixups.exists(_.isVariable)


  ///////////////////////////////////////////////////////////////////////////////////////////////
  // Literals support

  private var literals = new ArrayBuffer[Literal]

  /** Adds new externally created literal. */
  private[assembler] def addLiteral(literal: Literal): Literal = {
    assert(!frozen)
    literals += literal
    literal
  }

  def emitLiteral(literal: Literal): Unit = {
    align(literal.alignment)
    bindLabel(literal)
    literal.emit()
  }

  private[assembler] def flushLiterals(): Unit = {
    literals foreach emitLiteral
    literals.clear()
  }

  def setUnsigned(width: Width, pos: Int, data: Long): Unit = {
    assert(width == W64 || data == data.toInt)
    width match {
      case W8  => setW8(pos, data.toInt)
      case W16 => setW16(pos, data.toInt)
      case W32 => setW32(pos, data.toInt)
      case W64 => setW64(pos, data)
    }
  }

  def setSigned(width: Width, pos: Int, data: Long): Unit = {
    width match {
      case W8  => assert(data == data.toByte);  setW8(pos, data.toInt & 0xff)
      case W16 => assert(data == data.toShort); setW16(pos, data.toInt & 0xffff)
      case W32 => assert(data == data.toInt);   setW32(pos, data.toInt)
      case W64 => setW64(pos, data)
    }
  }

  def getUnsigned(width: Width, pos: Int): Long = {
    width match {
      case W8  => getUW8(pos)
      case W16 => getUW16(pos)
      case W32 => getUW32(pos)
      case W64 => getW64(pos)
    }
  }

  def getSigned(width: Width, pos: Int): Long = {
    width match {
      case W8  => getW8(pos)
      case W16 => getW16(pos)
      case W32 => getW32(pos)
      case W64 => getW64(pos)
    }
  }

  def patchSigned(width: Width, pos: Int, addend: Long): Unit = setSigned(width, pos, getSigned(width, pos) + addend)
}
