/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.
 * This source file is part of the Cangjie project, licensed under Apache-2.0
 * with Runtime Library Exception.
 *
 * See https://cangjie-lang.cn/pages/LICENSE for license information.
 */

package com.huawei.excelsior.jet.compiler.intrinsics

import com.huawei.excelsior.jet.common.XString
import com.huawei.excelsior.jet.compiler.bytecode.BytecodeTypeKind
import com.huawei.excelsior.jet.compiler.bytecode.BytecodeTypeKind.*
import com.huawei.excelsior.jet.compiler.symlevel.TypeKind
import com.huawei.excelsior.jet.compiler.util.Names.AJ.mangleName

/** Intrinsics without body (must be generated by any compiler) */
enum IntrinsicWithoutBody(className: String, methodName: String, signature: String,
                          specialParamsCount: Int, opType: BytecodeTypeKind) extends Intrinsic {

  case GCPoints_gcPoint extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/memory/gc/GCPoints", "gcPoint", "()V")

  case AJSyntax_bstr extends IntrinsicWithoutBody("com/huawei/excelsior/aj/lang/AJSyntax", mangleName("bstr", "(Ljava/lang/String;)Lcom/huawei/excelsior/aj/util/BString;"), "(Ljava/lang/String;)&", 1)
  case AJSyntax_ustr extends IntrinsicWithoutBody("com/huawei/excelsior/aj/lang/AJSyntax", mangleName("ustr", "(Ljava/lang/String;)Lcom/huawei/excelsior/aj/util/UString;"), "(Ljava/lang/String;)&", 1)
  case AJMSyntax_aj extends IntrinsicWithoutBody("com/huawei/excelsior/aj/lang/AJMSyntax", "aj", "(Ljava/lang/String;)Lcom/huawei/excelsior/aj/lang/AJString;")
  case StackAlloc_rawAlloc extends IntrinsicWithoutBody("com/huawei/excelsior/aj/lang/StackAlloc", mangleName("rawAlloc", "(II)Lcom/huawei/excelsior/aj/lang/Address;"), "(II)&", 2)
  case Address_getBoolean extends IntrinsicWithoutBody("com/huawei/excelsior/aj/lang/Address", mangleName("getBoolean", "()Z"), "(&)Z", BOOLEAN)
  case Address_getByte extends IntrinsicWithoutBody("com/huawei/excelsior/aj/lang/Address", mangleName("getByte", "()B"), "(&)B", BYTE)
  case Address_getShort extends IntrinsicWithoutBody("com/huawei/excelsior/aj/lang/Address", mangleName("getShort", "()S"), "(&)S", SHORT)
  case Address_getChar extends IntrinsicWithoutBody("com/huawei/excelsior/aj/lang/Address", mangleName("getChar", "()C"), "(&)C", CHAR)
  case Address_getInt extends IntrinsicWithoutBody("com/huawei/excelsior/aj/lang/Address", mangleName("getInt", "()I"), "(&)I", INT)
  case Address_getLong extends IntrinsicWithoutBody("com/huawei/excelsior/aj/lang/Address", mangleName("getLong", "()J"), "(&)J", LONG)
  case Address_getFloat extends IntrinsicWithoutBody("com/huawei/excelsior/aj/lang/Address", mangleName("getFloat", "()F"), "(&)F", FLOAT)
  case Address_getDouble extends IntrinsicWithoutBody("com/huawei/excelsior/aj/lang/Address", mangleName("getDouble", "()D"), "(&)D", DOUBLE)
  case Address_putBoolean extends IntrinsicWithoutBody("com/huawei/excelsior/aj/lang/Address", mangleName("putBoolean", "(Z)V"), "(&Z)V", BOOLEAN)
  case Address_putByte extends IntrinsicWithoutBody("com/huawei/excelsior/aj/lang/Address", mangleName("putByte", "(B)V"), "(&B)V", BYTE)
  case Address_putShort extends IntrinsicWithoutBody("com/huawei/excelsior/aj/lang/Address", mangleName("putShort", "(S)V"), "(&S)V", SHORT)
  case Address_putChar extends IntrinsicWithoutBody("com/huawei/excelsior/aj/lang/Address", mangleName("putChar", "(C)V"), "(&C)V", CHAR)
  case Address_putInt extends IntrinsicWithoutBody("com/huawei/excelsior/aj/lang/Address", mangleName("putInt", "(I)V"), "(&I)V", INT)
  case Address_putLong extends IntrinsicWithoutBody("com/huawei/excelsior/aj/lang/Address", mangleName("putLong", "(J)V"), "(&J)V", LONG)
  case Address_putFloat extends IntrinsicWithoutBody("com/huawei/excelsior/aj/lang/Address", mangleName("putFloat", "(F)V"), "(&F)V", FLOAT)
  case Address_putDouble extends IntrinsicWithoutBody("com/huawei/excelsior/aj/lang/Address", mangleName("putDouble", "(D)V"), "(&D)V", DOUBLE)
  case Address_getAddr extends IntrinsicWithoutBody("com/huawei/excelsior/aj/lang/Address", mangleName("getAddr", "()Lcom/huawei/excelsior/aj/lang/Address;"), "(&)&")
  case Address_putAddr extends IntrinsicWithoutBody("com/huawei/excelsior/aj/lang/Address", mangleName("putAddr", "(Lcom/huawei/excelsior/aj/lang/Address;)V"), "(&&)V")

  case PlainEop_asAJObject extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/jobject/Eop$Plain", mangleName("asAJObject", "()Lcom/huawei/excelsior/aj/lang/AJObject;"), "(&)Lcom/huawei/excelsior/aj/lang/AJObject;")
  case PlainEop_fromAJObject extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/jobject/Eop$Plain", mangleName("fromAJObject", "(Lcom/huawei/excelsior/aj/lang/AJObject;)Lcom/huawei/excelsior/jet/runtime/jobject/Eop$Plain;"), "(Lcom/huawei/excelsior/aj/lang/AJObject;)&")

  case EopUtils_asJavaObject extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/jobject/EopUtils", mangleName("asJavaObject", "(Lcom/huawei/excelsior/jet/runtime/jobject/Eop$Plain;)Ljava/lang/Object;"), "(&)Ljava/lang/Object;")
  case ScalaEopUtils_asScalaObject extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/jobject/ScalaEopUtils", mangleName("asScalaObject", "(Lcom/huawei/excelsior/jet/runtime/jobject/Eop$Plain;)Lcom/huawei/excelsior/aj/lang/AJObject;"), "(&)Lcom/huawei/excelsior/aj/lang/AJObject;")

  case ManagedEop_constrPlainImpl extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/jobject/ManagedEop", mangleName("constrPlainImpl", "(Lcom/huawei/excelsior/aj/lang/AJObject;)Lcom/huawei/excelsior/jet/runtime/jobject/ManagedEop;"), "(Lcom/huawei/excelsior/aj/lang/AJObject;)Lcom/huawei/excelsior/aj/jetrt/ManagedEopType;")
  case ManagedEop_copyEnrichment extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/jobject/ManagedEop", mangleName("copyEnrichment", "(Lcom/huawei/excelsior/aj/lang/AJObject;Lcom/huawei/excelsior/jet/runtime/jobject/ManagedEop;)Lcom/huawei/excelsior/jet/runtime/jobject/ManagedEop;"), "(Lcom/huawei/excelsior/aj/lang/AJObject;Lcom/huawei/excelsior/aj/jetrt/ManagedEopType;)Lcom/huawei/excelsior/aj/jetrt/ManagedEopType;")
  case ManagedEop_extractValue extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/jobject/ManagedEop", mangleName("extractValue", "(Lcom/huawei/excelsior/jet/runtime/jobject/ManagedEop;)Lcom/huawei/excelsior/aj/lang/AJObject;"), "(Lcom/huawei/excelsior/aj/jetrt/ManagedEopType;)Lcom/huawei/excelsior/aj/lang/AJObject;")

  // In some cases class could be a local
  // and we don't generate any code in implementation of this intrinsic
  // so we don't save it as param, and simply drop it
  case Unchecked_cast extends IntrinsicWithoutBody("com/huawei/excelsior/aj/jetrt/Unchecked", mangleName("cast", "(Lcom/huawei/excelsior/aj/lang/AJManaged;Ljava/lang/Class;)Lcom/huawei/excelsior/aj/lang/AJManaged;"), "(Lcom/huawei/excelsior/aj/lang/AJObject;&)Lcom/huawei/excelsior/aj/lang/AJObject;")
  case UncheckedJava_cast extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/jobject/UncheckedJava", mangleName("cast", "(Ljava/lang/Object;Ljava/lang/Class;)Ljava/lang/Object;"), "(Ljava/lang/Object;&)Ljava/lang/Object;")
  case UncheckedJava_cast_byName extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/jobject/UncheckedJava", mangleName("cast", "(Ljava/lang/Object;Lcom/huawei/excelsior/aj/util/BString;)Ljava/lang/Object;"), "(Ljava/lang/Object;&)Ljava/lang/Object;")

  case ManagedObjects_asLockable extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/jobject/ManagedObjects", "asLockable", "(Ljava/lang/Object;)Lcom/huawei/excelsior/aj/lang/LockableAJObject;")
  case JETVarArgs_getVarArgs extends IntrinsicWithoutBody("com/huawei/excelsior/aj/lang/VarArgs", mangleName("getVarArgs", "()Lcom/huawei/excelsior/aj/lang/VarArgs;"), "()&")
  case CVarArgs_getVarArgs extends IntrinsicWithoutBody("com/huawei/excelsior/aj/lang/CVarArgs", mangleName("getVarArgs", "()Lcom/huawei/excelsior/aj/lang/CVarArgs;"), "()&")
  case VarArgsBuilder_start extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/VarArgsBuilder", "start", "()Lcom/huawei/excelsior/aj/internal/comp/VarArgsBuilder;")
  case VarArgsBuilder_done extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/VarArgsBuilder", "done", "(Lcom/huawei/excelsior/aj/internal/comp/VarArgsBuilder;)[Ljava/lang/Object;")
  case VarArgsBuilder_arg_B extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/VarArgsBuilder", "arg", "(BLcom/huawei/excelsior/aj/internal/comp/VarArgsBuilder;)Lcom/huawei/excelsior/aj/internal/comp/VarArgsBuilder;", BYTE)
  case VarArgsBuilder_arg_S extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/VarArgsBuilder", "arg", "(SLcom/huawei/excelsior/aj/internal/comp/VarArgsBuilder;)Lcom/huawei/excelsior/aj/internal/comp/VarArgsBuilder;", SHORT)
  case VarArgsBuilder_arg_I extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/VarArgsBuilder", "arg", "(ILcom/huawei/excelsior/aj/internal/comp/VarArgsBuilder;)Lcom/huawei/excelsior/aj/internal/comp/VarArgsBuilder;", INT)
  case VarArgsBuilder_arg_J extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/VarArgsBuilder", "arg", "(JLcom/huawei/excelsior/aj/internal/comp/VarArgsBuilder;)Lcom/huawei/excelsior/aj/internal/comp/VarArgsBuilder;", LONG)
  case VarArgsBuilder_arg_C extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/VarArgsBuilder", "arg", "(CLcom/huawei/excelsior/aj/internal/comp/VarArgsBuilder;)Lcom/huawei/excelsior/aj/internal/comp/VarArgsBuilder;", CHAR)
  case VarArgsBuilder_arg_Z extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/VarArgsBuilder", "arg", "(ZLcom/huawei/excelsior/aj/internal/comp/VarArgsBuilder;)Lcom/huawei/excelsior/aj/internal/comp/VarArgsBuilder;", BYTE)
  case VarArgsBuilder_arg_F extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/VarArgsBuilder", "arg", "(FLcom/huawei/excelsior/aj/internal/comp/VarArgsBuilder;)Lcom/huawei/excelsior/aj/internal/comp/VarArgsBuilder;", FLOAT)
  case VarArgsBuilder_arg_D extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/VarArgsBuilder", "arg", "(DLcom/huawei/excelsior/aj/internal/comp/VarArgsBuilder;)Lcom/huawei/excelsior/aj/internal/comp/VarArgsBuilder;", DOUBLE)
  case CodeAddrIntrinsics_getMethodAddr extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/CodeAddrIntrinsics", mangleName("getMethodAddr", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lcom/huawei/excelsior/aj/lang/CodeAddr;"), "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)&", 3)
  case ManagedExecEnv_getManagedExecEnv extends IntrinsicWithoutBody("com/huawei/excelsior/aj/util/ManagedExecEnv", mangleName("getManagedExecEnv", "()Lcom/huawei/excelsior/aj/util/ManagedExecEnv;"), "()&")
  case CJNativeThreadLocal_get extends  IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/thread/CJNativeThreadLocalStorage$CJNativeThreadLocal", mangleName("get", "()Lcom/huawei/excelsior/jet/runtime/thread/CJNativeThreadLocalStorage$CJNativeThreadLocal;"), "()&")
  case StackDescriptor_getCurrentStackDescriptor extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/memory/gc/stack/StackDescriptor", mangleName("getCurrentStackDescriptor", "()Lcom/huawei/excelsior/jet/runtime/memory/gc/stack/StackDescriptor;"), "()&")
  case FrameHeader_getCurrentFrameHeader extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/excepts/FrameHeader", mangleName("getCurrentFrameHeader", "()Lcom/huawei/excelsior/jet/runtime/excepts/FrameHeader;"), "()&")
  case JavaFieldAccess_getBoolean extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/JavaFieldAccessIntrinsics", "getBoolean", "(Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)Z", 2, BOOLEAN)
  case JavaFieldAccess_getByte extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/JavaFieldAccessIntrinsics", "getByte", "(Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)B", 2, BYTE)
  case JavaFieldAccess_getShort extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/JavaFieldAccessIntrinsics", "getShort", "(Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)S", 2, SHORT)
  case JavaFieldAccess_getChar extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/JavaFieldAccessIntrinsics", "getChar", "(Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)C", 2, CHAR)
  case JavaFieldAccess_getInt extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/JavaFieldAccessIntrinsics", "getInt", "(Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)I", 2, INT)
  case JavaFieldAccess_getLong extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/JavaFieldAccessIntrinsics", "getLong", "(Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)J", 2, LONG)
  case JavaFieldAccess_getFloat extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/JavaFieldAccessIntrinsics", "getFloat", "(Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)F", 2, FLOAT)
  case JavaFieldAccess_getDouble extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/JavaFieldAccessIntrinsics", "getDouble", "(Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)D", 2, DOUBLE)
  case JavaFieldAccess_getObject extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/JavaFieldAccessIntrinsics", "getObject", "(Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Object;", 2, CLASS)
  case JavaFieldAccess_getAJObject extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/JavaFieldAccessIntrinsics", "getAJObject", "(Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)Lcom/huawei/excelsior/aj/lang/AJObject;", 2, CLASS)
  case JavaFieldAccess_setBoolean extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/JavaFieldAccessIntrinsics", "setBoolean", "(Ljava/lang/Object;ZLjava/lang/String;Ljava/lang/String;)V", 2, BOOLEAN)
  case JavaFieldAccess_setByte extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/JavaFieldAccessIntrinsics", "setByte", "(Ljava/lang/Object;BLjava/lang/String;Ljava/lang/String;)V", 2, BYTE)
  case JavaFieldAccess_setShort extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/JavaFieldAccessIntrinsics", "setShort", "(Ljava/lang/Object;SLjava/lang/String;Ljava/lang/String;)V", 2, SHORT)
  case JavaFieldAccess_setChar extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/JavaFieldAccessIntrinsics", "setChar", "(Ljava/lang/Object;CLjava/lang/String;Ljava/lang/String;)V", 2, CHAR)
  case JavaFieldAccess_setInt extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/JavaFieldAccessIntrinsics", "setInt", "(Ljava/lang/Object;ILjava/lang/String;Ljava/lang/String;)V", 2, INT)
  case JavaFieldAccess_setLong extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/JavaFieldAccessIntrinsics", "setLong", "(Ljava/lang/Object;JLjava/lang/String;Ljava/lang/String;)V", 2, LONG)
  case JavaFieldAccess_setFloat extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/JavaFieldAccessIntrinsics", "setFloat", "(Ljava/lang/Object;FLjava/lang/String;Ljava/lang/String;)V", 2, FLOAT)
  case JavaFieldAccess_setDouble extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/JavaFieldAccessIntrinsics", "setDouble", "(Ljava/lang/Object;DLjava/lang/String;Ljava/lang/String;)V", 2, DOUBLE)
  case JavaFieldAccess_setAJObject extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/JavaFieldAccessIntrinsics", "setAJObject", "(Ljava/lang/Object;Lcom/huawei/excelsior/aj/lang/AJObject;Ljava/lang/String;Ljava/lang/String;)V", 2, CLASS)
  case JavaFieldAccess_setObject extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/JavaFieldAccessIntrinsics", "setObject", "(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)V", 2, CLASS)
  case JavaFieldAccess_getLength extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/JavaFieldAccessIntrinsics", "getLength", "(Ljava/lang/Object;)I")
  case AJFieldAccess_getBoolean extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/AJFieldAccessIntrinsics", mangleName("getBoolean", "(Lcom/huawei/excelsior/aj/lang/AJManaged;Ljava/lang/String;Ljava/lang/String;)Z"), "(Lcom/huawei/excelsior/aj/lang/AJObject;Ljava/lang/String;Ljava/lang/String;)Z", 2, BOOLEAN)
  case AJFieldAccess_getByte extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/AJFieldAccessIntrinsics", mangleName("getByte", "(Lcom/huawei/excelsior/aj/lang/AJManaged;Ljava/lang/String;Ljava/lang/String;)B"), "(Lcom/huawei/excelsior/aj/lang/AJObject;Ljava/lang/String;Ljava/lang/String;)B", 2, BYTE)
  case AJFieldAccess_getShort extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/AJFieldAccessIntrinsics", mangleName("getShort", "(Lcom/huawei/excelsior/aj/lang/AJManaged;Ljava/lang/String;Ljava/lang/String;)S"), "(Lcom/huawei/excelsior/aj/lang/AJObject;Ljava/lang/String;Ljava/lang/String;)S", 2, SHORT)
  case AJFieldAccess_getChar extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/AJFieldAccessIntrinsics", mangleName("getChar", "(Lcom/huawei/excelsior/aj/lang/AJManaged;Ljava/lang/String;Ljava/lang/String;)C"), "(Lcom/huawei/excelsior/aj/lang/AJObject;Ljava/lang/String;Ljava/lang/String;)C", 2, CHAR)
  case AJFieldAccess_getInt extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/AJFieldAccessIntrinsics", mangleName("getInt", "(Lcom/huawei/excelsior/aj/lang/AJManaged;Ljava/lang/String;Ljava/lang/String;)I"), "(Lcom/huawei/excelsior/aj/lang/AJObject;Ljava/lang/String;Ljava/lang/String;)I", 2, INT)
  case AJFieldAccess_getLong extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/AJFieldAccessIntrinsics", mangleName("getLong", "(Lcom/huawei/excelsior/aj/lang/AJManaged;Ljava/lang/String;Ljava/lang/String;)J"), "(Lcom/huawei/excelsior/aj/lang/AJObject;Ljava/lang/String;Ljava/lang/String;)J", 2, LONG)
  case AJFieldAccess_getFloat extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/AJFieldAccessIntrinsics", mangleName("getFloat", "(Lcom/huawei/excelsior/aj/lang/AJManaged;Ljava/lang/String;Ljava/lang/String;)F"), "(Lcom/huawei/excelsior/aj/lang/AJObject;Ljava/lang/String;Ljava/lang/String;)F", 2, FLOAT)
  case AJFieldAccess_getDouble extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/AJFieldAccessIntrinsics", mangleName("getDouble", "(Lcom/huawei/excelsior/aj/lang/AJManaged;Ljava/lang/String;Ljava/lang/String;)D"), "(Lcom/huawei/excelsior/aj/lang/AJObject;Ljava/lang/String;Ljava/lang/String;)D", 2, DOUBLE)
  case AJFieldAccess_getObject extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/AJFieldAccessIntrinsics", mangleName("getObject", "(Lcom/huawei/excelsior/aj/lang/AJManaged;Ljava/lang/String;Ljava/lang/String;)Lcom/huawei/excelsior/aj/lang/AJObject;"), "(Lcom/huawei/excelsior/aj/lang/AJObject;Ljava/lang/String;Ljava/lang/String;)Lcom/huawei/excelsior/aj/lang/AJObject;", 2, CLASS)
  case AJFieldAccess_setBoolean extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/AJFieldAccessIntrinsics", mangleName("setBoolean", "(Lcom/huawei/excelsior/aj/lang/AJManaged;ZLjava/lang/String;Ljava/lang/String;)V"), "(Lcom/huawei/excelsior/aj/lang/AJObject;ZLjava/lang/String;Ljava/lang/String;)V", 2, BOOLEAN)
  case AJFieldAccess_setByte extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/AJFieldAccessIntrinsics", mangleName("setByte", "(Lcom/huawei/excelsior/aj/lang/AJManaged;BLjava/lang/String;Ljava/lang/String;)V"), "(Lcom/huawei/excelsior/aj/lang/AJObject;BLjava/lang/String;Ljava/lang/String;)V", 2, BYTE)
  case AJFieldAccess_setShort extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/AJFieldAccessIntrinsics", mangleName("setShort", "(Lcom/huawei/excelsior/aj/lang/AJManaged;SLjava/lang/String;Ljava/lang/String;)V"), "(Lcom/huawei/excelsior/aj/lang/AJObject;SLjava/lang/String;Ljava/lang/String;)V", 2, SHORT)
  case AJFieldAccess_setChar extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/AJFieldAccessIntrinsics", mangleName("setChar", "(Lcom/huawei/excelsior/aj/lang/AJManaged;CLjava/lang/String;Ljava/lang/String;)V"), "(Lcom/huawei/excelsior/aj/lang/AJObject;CLjava/lang/String;Ljava/lang/String;)V", 2, CHAR)
  case AJFieldAccess_setInt extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/AJFieldAccessIntrinsics", mangleName("setInt", "(Lcom/huawei/excelsior/aj/lang/AJManaged;ILjava/lang/String;Ljava/lang/String;)V"), "(Lcom/huawei/excelsior/aj/lang/AJObject;ILjava/lang/String;Ljava/lang/String;)V", 2, INT)
  case AJFieldAccess_setLong extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/AJFieldAccessIntrinsics", mangleName("setLong", "(Lcom/huawei/excelsior/aj/lang/AJManaged;JLjava/lang/String;Ljava/lang/String;)V"), "(Lcom/huawei/excelsior/aj/lang/AJObject;JLjava/lang/String;Ljava/lang/String;)V", 2, LONG)
  case AJFieldAccess_setFloat extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/AJFieldAccessIntrinsics", mangleName("setFloat", "(Lcom/huawei/excelsior/aj/lang/AJManaged;FLjava/lang/String;Ljava/lang/String;)V"), "(Lcom/huawei/excelsior/aj/lang/AJObject;FLjava/lang/String;Ljava/lang/String;)V", 2, FLOAT)
  case AJFieldAccess_setDouble extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/AJFieldAccessIntrinsics", mangleName("setDouble", "(Lcom/huawei/excelsior/aj/lang/AJManaged;DLjava/lang/String;Ljava/lang/String;)V"), "(Lcom/huawei/excelsior/aj/lang/AJObject;DLjava/lang/String;Ljava/lang/String;)V", 2, DOUBLE)
  case AJFieldAccess_setObject extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/AJFieldAccessIntrinsics", mangleName("setObject", "(Lcom/huawei/excelsior/aj/lang/AJManaged;Lcom/huawei/excelsior/aj/lang/AJObject;Ljava/lang/String;Ljava/lang/String;)V"), "(Lcom/huawei/excelsior/aj/lang/AJObject;Lcom/huawei/excelsior/aj/lang/AJObject;Ljava/lang/String;Ljava/lang/String;)V", 2, CLASS)

  case DelayedIntrinsics_setObject extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/DelayedIntrinsics", "setObject", "(Lcom/huawei/excelsior/aj/lang/AJObject;Lcom/huawei/excelsior/aj/lang/AJObject;Ljava/lang/String;Ljava/lang/String;)V", 2, CLASS)
  case DelayedIntrinsics_getObject extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/DelayedIntrinsics", "getObject", "(Lcom/huawei/excelsior/aj/lang/AJObject;Ljava/lang/String;Ljava/lang/String;)Lcom/huawei/excelsior/aj/lang/AJObject;", 2, CLASS)
  case DelayedIntrinsics_setInt extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/DelayedIntrinsics", "setInt", "(Lcom/huawei/excelsior/aj/lang/AJObject;ILjava/lang/String;Ljava/lang/String;)V", 2, CLASS)
  case DelayedIntrinsics_getInt extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/DelayedIntrinsics", "getInt", "(Lcom/huawei/excelsior/aj/lang/AJObject;Ljava/lang/String;Ljava/lang/String;)I", 2, CLASS)
  case DelayedIntrinsics_setLong extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/DelayedIntrinsics", "setLong", "(Lcom/huawei/excelsior/aj/lang/AJObject;JLjava/lang/String;Ljava/lang/String;)V", 2, CLASS)
  case DelayedIntrinsics_getLong extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/DelayedIntrinsics", "getLong", "(Lcom/huawei/excelsior/aj/lang/AJObject;Ljava/lang/String;Ljava/lang/String;)J", 2, CLASS)
  case DelayedIntrinsics_getMethodVNum extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/DelayedIntrinsics", "getInstanceMethodVNum", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I", 3)
  case DelayedIntrinsics_getFieldAddr extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/DelayedIntrinsics", mangleName("getInstanceFieldAddress", "(Lcom/huawei/excelsior/aj/lang/AJObject;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lcom/huawei/excelsior/aj/lang/Address;"), "(Lcom/huawei/excelsior/aj/lang/AJObject;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)&", 3)
  case DelayedIntrinsics_getMethodAddr extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/DelayedIntrinsics", mangleName("getMethodAddr", "(Ljava/lang/String;Ljava/lang/String;)Lcom/huawei/excelsior/aj/lang/CodeAddr;"), "(Ljava/lang/String;Ljava/lang/String;)&", 2)

  case TypeHandle_of extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/typedesc/TypeHandle", mangleName("of", "(Ljava/lang/String;)Lcom/huawei/excelsior/jet/runtime/typedesc/TypeHandle;"), "(Ljava/lang/String;)&", 1)
  case RunTimeTypeInfo_of extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/typedesc/RunTimeTypeInfo", mangleName("of", "(Ljava/lang/String;)Lcom/huawei/excelsior/jet/runtime/typedesc/RunTimeTypeInfo;"), "(Ljava/lang/String;)&", 1)
  case InstanceDescriptor_of extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/typedesc/InstanceDescriptor", mangleName("of", "(Ljava/lang/String;)Lcom/huawei/excelsior/jet/runtime/typedesc/InstanceDescriptor;"), "(Ljava/lang/String;)&", 1)
  case RunTimeTypeInfo_raw extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/typedesc/RunTimeTypeInfo", mangleName("raw", "(Ljava/lang/String;)Lcom/huawei/excelsior/jet/runtime/typedesc/RunTimeTypeInfo;"), "(Ljava/lang/String;)&", 1)
  case InstanceDescriptor_raw extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/typedesc/InstanceDescriptor", mangleName("raw", "(Ljava/lang/String;)Lcom/huawei/excelsior/jet/runtime/typedesc/InstanceDescriptor;"), "(Ljava/lang/String;)&", 1)
  case JavaTypeHandle_of extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/typedesc/JavaTypeHandle", mangleName("of", "(Ljava/lang/String;)Lcom/huawei/excelsior/jet/runtime/typedesc/JavaTypeHandle;"), "(Ljava/lang/String;)&", 1)
  case JavaRunTimeTypeInfo_of extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/typedesc/JavaRunTimeTypeInfo", mangleName("of", "(Ljava/lang/String;)Lcom/huawei/excelsior/jet/runtime/typedesc/JavaRunTimeTypeInfo;"), "(Ljava/lang/String;)&", 1)
  case JavaInstanceDescriptor_of extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/typedesc/JavaInstanceDescriptor", mangleName("of", "(Ljava/lang/String;)Lcom/huawei/excelsior/jet/runtime/typedesc/JavaInstanceDescriptor;"), "(Ljava/lang/String;)&", 1)
  case JavaRunTimeTypeInfo_raw extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/typedesc/JavaRunTimeTypeInfo", mangleName("raw", "(Ljava/lang/String;)Lcom/huawei/excelsior/jet/runtime/typedesc/JavaRunTimeTypeInfo;"), "(Ljava/lang/String;)&", 1)
  case JavaInstanceDescriptor_raw extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/typedesc/JavaInstanceDescriptor", mangleName("raw", "(Ljava/lang/String;)Lcom/huawei/excelsior/jet/runtime/typedesc/JavaInstanceDescriptor;"), "(Ljava/lang/String;)&", 1)
  case ScalaTypeHandle_of extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/typedesc/ScalaTypeHandle", mangleName("of", "(Ljava/lang/String;)Lcom/huawei/excelsior/jet/runtime/typedesc/ScalaTypeHandle;"), "(Ljava/lang/String;)&", 1)
  case ScalaRunTimeTypeInfo_of extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/typedesc/ScalaRunTimeTypeInfo", mangleName("of", "(Ljava/lang/String;)Lcom/huawei/excelsior/jet/runtime/typedesc/ScalaRunTimeTypeInfo;"), "(Ljava/lang/String;)&", 1)
  case ScalaInstanceDescriptor_of extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/typedesc/ScalaInstanceDescriptor", mangleName("of", "(Ljava/lang/String;)Lcom/huawei/excelsior/jet/runtime/typedesc/ScalaInstanceDescriptor;"), "(Ljava/lang/String;)&", 1)
  case ScalaRunTimeTypeInfo_raw extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/typedesc/ScalaRunTimeTypeInfo", mangleName("raw", "(Ljava/lang/String;)Lcom/huawei/excelsior/jet/runtime/typedesc/ScalaRunTimeTypeInfo;"), "(Ljava/lang/String;)&", 1)
  case ScalaInstanceDescriptor_raw extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/typedesc/ScalaInstanceDescriptor", mangleName("raw", "(Ljava/lang/String;)Lcom/huawei/excelsior/jet/runtime/typedesc/ScalaInstanceDescriptor;"), "(Ljava/lang/String;)&", 1)
  case CangjieTypeHandle_of extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/typedesc/CangjieTypeHandle", mangleName("of", "(Ljava/lang/String;)Lcom/huawei/excelsior/jet/runtime/typedesc/CangjieTypeHandle;"), "(Ljava/lang/String;)&", 1)
  case CangjieRunTimeTypeInfo_of extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/typedesc/CangjieRunTimeTypeInfo", mangleName("of", "(Ljava/lang/String;)Lcom/huawei/excelsior/jet/runtime/typedesc/CangjieRunTimeTypeInfo;"), "(Ljava/lang/String;)&", 1)
  case CangjieInstanceDescriptor_of extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/typedesc/CangjieInstanceDescriptor", mangleName("of", "(Ljava/lang/String;)Lcom/huawei/excelsior/jet/runtime/typedesc/CangjieInstanceDescriptor;"), "(Ljava/lang/String;)&", 1)
  case CangjieRunTimeTypeInfo_raw extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/typedesc/CangjieRunTimeTypeInfo", mangleName("raw", "(Ljava/lang/String;)Lcom/huawei/excelsior/jet/runtime/typedesc/CangjieRunTimeTypeInfo;"), "(Ljava/lang/String;)&", 1)
  case CangjieInstanceDescriptor_raw extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/typedesc/CangjieInstanceDescriptor", mangleName("raw", "(Ljava/lang/String;)Lcom/huawei/excelsior/jet/runtime/typedesc/CangjieInstanceDescriptor;"), "(Ljava/lang/String;)&", 1)
  case GCPoints_genTrapCheckOnAddress extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/memory/gc/GCPoints", mangleName("genTrapCheckOnAddress", "(Lcom/huawei/excelsior/aj/lang/Address;)V"), "(&)V")
  case MethodInfoFrameDescriptor_of extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/excepts/MethodInfoFrameDescriptor", mangleName("of", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lcom/huawei/excelsior/jet/runtime/excepts/MethodInfoFrameDescriptor;"), "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)&", 3)
  case CompiledLayoutInfo_size extends IntrinsicWithoutBody("com/huawei/excelsior/aj/jetrt/CompiledLayoutInfo", "size", "(Ljava/lang/String;)I", 1)

  case GCSafetyValidatorIntrinsics_enterGCSafetyChecksFreeSection extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/GCSafetyValidatorIntrinsics", "enterGCSafetyChecksFreeSection", "()V")
  case GCSafetyValidatorIntrinsics_leaveGCSafetyChecksFreeSection extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/GCSafetyValidatorIntrinsics", "leaveGCSafetyChecksFreeSection", "()V")

  case ThinTypeInternals_thinAlloc extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/ThinTypeInternals", mangleName("thinAlloc", "(Ljava/lang/String;)Lcom/huawei/excelsior/aj/lang/Address;"), "(Ljava/lang/String;)&", 1)
  case ThinTypeInternals_newThin extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/ThinTypeInternals", mangleName("newThin", "(Lcom/huawei/excelsior/aj/lang/Address;Ljava/lang/String;)Lcom/huawei/excelsior/aj/lang/ThinType;"), "(&Ljava/lang/String;)Lcom/huawei/excelsior/aj/lang/ThinType;", 1)
  case ThinTypeInternals_thinAsAddress extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/ThinTypeInternals", mangleName("thinAsAddress", "(Lcom/huawei/excelsior/aj/lang/ThinType;)Lcom/huawei/excelsior/aj/lang/Address;"), "(Lcom/huawei/excelsior/aj/lang/ThinType;)&")
  case ThinTypeInternals_addressAsThin extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/ThinTypeInternals", mangleName("addressAsThin", "(Lcom/huawei/excelsior/aj/lang/Address;)Lcom/huawei/excelsior/aj/lang/ThinType;"), "(&)Lcom/huawei/excelsior/aj/lang/ThinType;")
  case ThinTypeInternals_requireNonNull extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/ThinTypeInternals", "requireNonNull", "(Lcom/huawei/excelsior/aj/lang/ThinType;)Lcom/huawei/excelsior/aj/lang/ThinType;")

  case ManagedTypeInternals_requireNonNull extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/ManagedTypeInternals", "requireNonNull", "(Lcom/huawei/excelsior/aj/lang/AJObject;)Lcom/huawei/excelsior/aj/lang/AJObject;")

  case AJRefArray_get extends IntrinsicWithoutBody("com/huawei/excelsior/aj/lang/AJRefArray", mangleName("get", "(Lcom/huawei/excelsior/aj/lang/AddrUInt;)Lcom/huawei/excelsior/aj/lang/AJManaged;"), "(&)Lcom/huawei/excelsior/aj/lang/AJObject;", CLASS)
  case AJRefArray_set extends IntrinsicWithoutBody("com/huawei/excelsior/aj/lang/AJRefArray", mangleName("set", "(Lcom/huawei/excelsior/aj/lang/AddrUInt;Lcom/huawei/excelsior/aj/lang/AJManaged;)V"), "(&Lcom/huawei/excelsior/aj/lang/AJObject;)V", CLASS)
  case AJRefArray_length extends IntrinsicWithoutBody("com/huawei/excelsior/aj/lang/AJRefArray", mangleName("length", "()Lcom/huawei/excelsior/aj/lang/AddrUInt;"), "()&", CLASS)

  case AJByteArray_get extends IntrinsicWithoutBody("com/huawei/excelsior/aj/lang/AJByteArray", mangleName("get", "(Lcom/huawei/excelsior/aj/lang/AddrUInt;)B"), "(&)B", BYTE)
  case AJByteArray_set extends IntrinsicWithoutBody("com/huawei/excelsior/aj/lang/AJByteArray", mangleName("set", "(Lcom/huawei/excelsior/aj/lang/AddrUInt;B)V"), "(&B)V", BYTE)
  case AJByteArray_length extends IntrinsicWithoutBody("com/huawei/excelsior/aj/lang/AJByteArray", mangleName("length", "()Lcom/huawei/excelsior/aj/lang/AddrUInt;"), "()&", BYTE)

  case AJBooleanArray_get extends IntrinsicWithoutBody("com/huawei/excelsior/aj/lang/AJBooleanArray", mangleName("get", "(Lcom/huawei/excelsior/aj/lang/AddrUInt;)Z"), "(&)Z", BOOLEAN)
  case AJBooleanArray_set extends IntrinsicWithoutBody("com/huawei/excelsior/aj/lang/AJBooleanArray", mangleName("set", "(Lcom/huawei/excelsior/aj/lang/AddrUInt;Z)V"), "(&Z)V", BOOLEAN)
  case AJBooleanArray_length extends IntrinsicWithoutBody("com/huawei/excelsior/aj/lang/AJBooleanArray", mangleName("length", "()Lcom/huawei/excelsior/aj/lang/AddrUInt;"), "()&", BOOLEAN)

  case AJCharArray_get extends IntrinsicWithoutBody("com/huawei/excelsior/aj/lang/AJCharArray", mangleName("get", "(Lcom/huawei/excelsior/aj/lang/AddrUInt;)C"), "(&)C", CHAR)
  case AJCharArray_set extends IntrinsicWithoutBody("com/huawei/excelsior/aj/lang/AJCharArray", mangleName("set", "(Lcom/huawei/excelsior/aj/lang/AddrUInt;C)V"), "(&C)V", CHAR)
  case AJCharArray_length extends IntrinsicWithoutBody("com/huawei/excelsior/aj/lang/AJCharArray", mangleName("length", "()Lcom/huawei/excelsior/aj/lang/AddrUInt;"), "()&", CHAR)

  case AJShortArray_get extends IntrinsicWithoutBody("com/huawei/excelsior/aj/lang/AJShortArray", mangleName("get", "(Lcom/huawei/excelsior/aj/lang/AddrUInt;)S"), "(&)S", SHORT)
  case AJShortArray_set extends IntrinsicWithoutBody("com/huawei/excelsior/aj/lang/AJShortArray", mangleName("set", "(Lcom/huawei/excelsior/aj/lang/AddrUInt;S)V"), "(&S)V", SHORT)
  case AJShortArray_length extends IntrinsicWithoutBody("com/huawei/excelsior/aj/lang/AJShortArray", mangleName("length", "()Lcom/huawei/excelsior/aj/lang/AddrUInt;"), "()&", SHORT)

  case AJIntArray_get extends IntrinsicWithoutBody("com/huawei/excelsior/aj/lang/AJIntArray", mangleName("get", "(Lcom/huawei/excelsior/aj/lang/AddrUInt;)I"), "(&)I", INT)
  case AJIntArray_set extends IntrinsicWithoutBody("com/huawei/excelsior/aj/lang/AJIntArray", mangleName("set", "(Lcom/huawei/excelsior/aj/lang/AddrUInt;I)V"), "(&I)V", INT)
  case AJIntArray_length extends IntrinsicWithoutBody("com/huawei/excelsior/aj/lang/AJIntArray", mangleName("length", "()Lcom/huawei/excelsior/aj/lang/AddrUInt;"), "()&", INT)

  case AJLongArray_get extends IntrinsicWithoutBody("com/huawei/excelsior/aj/lang/AJLongArray", mangleName("get", "(Lcom/huawei/excelsior/aj/lang/AddrUInt;)J"), "(&)J", LONG)
  case AJLongArray_set extends IntrinsicWithoutBody("com/huawei/excelsior/aj/lang/AJLongArray", mangleName("set", "(Lcom/huawei/excelsior/aj/lang/AddrUInt;J)V"), "(&J)V", LONG)
  case AJLongArray_length extends IntrinsicWithoutBody("com/huawei/excelsior/aj/lang/AJLongArray", mangleName("length", "()Lcom/huawei/excelsior/aj/lang/AddrUInt;"), "()&", LONG)

  case AJFloatArray_get extends IntrinsicWithoutBody("com/huawei/excelsior/aj/lang/AJFloatArray", mangleName("get", "(Lcom/huawei/excelsior/aj/lang/AddrUInt;)F"), "(&)F", FLOAT)
  case AJFloatArray_set extends IntrinsicWithoutBody("com/huawei/excelsior/aj/lang/AJFloatArray", mangleName("set", "(Lcom/huawei/excelsior/aj/lang/AddrUInt;F)V"), "(&F)V", FLOAT)
  case AJFloatArray_length extends IntrinsicWithoutBody("com/huawei/excelsior/aj/lang/AJFloatArray", mangleName("length", "()Lcom/huawei/excelsior/aj/lang/AddrUInt;"), "()&", FLOAT)

  case AJDoubleArray_get extends IntrinsicWithoutBody("com/huawei/excelsior/aj/lang/AJDoubleArray", mangleName("get", "(Lcom/huawei/excelsior/aj/lang/AddrUInt;)D"), "(&)D", DOUBLE)
  case AJDoubleArray_set extends IntrinsicWithoutBody("com/huawei/excelsior/aj/lang/AJDoubleArray", mangleName("set", "(Lcom/huawei/excelsior/aj/lang/AddrUInt;D)V"), "(&D)V", DOUBLE)
  case AJDoubleArray_length extends IntrinsicWithoutBody("com/huawei/excelsior/aj/lang/AJDoubleArray", mangleName("length", "()Lcom/huawei/excelsior/aj/lang/AddrUInt;"), "()&", DOUBLE)

  case ManagedArrayIntrinsic_allocRefArray extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/ManagedArrayIntrinsics", mangleName("allocRefArray", "(Lcom/huawei/excelsior/aj/lang/AddrUInt;)Lcom/huawei/excelsior/aj/lang/AJRefArray;"), "(&)Lcom/huawei/excelsior/aj/lang/AJRefArray;", CLASS)
  case ManagedArrayIntrinsic_allocByteArray extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/ManagedArrayIntrinsics", mangleName("allocByteArray", "(Lcom/huawei/excelsior/aj/lang/AddrUInt;)Lcom/huawei/excelsior/aj/lang/AJByteArray;"), "(&)Lcom/huawei/excelsior/aj/lang/AJByteArray;", BYTE)
  case ManagedArrayIntrinsic_allocBooleanArray extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/ManagedArrayIntrinsics", mangleName("allocBooleanArray", "(Lcom/huawei/excelsior/aj/lang/AddrUInt;)Lcom/huawei/excelsior/aj/lang/AJBooleanArray;"), "(&)Lcom/huawei/excelsior/aj/lang/AJBooleanArray;", BOOLEAN)
  case ManagedArrayIntrinsic_allocCharArray extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/ManagedArrayIntrinsics", mangleName("allocCharArray", "(Lcom/huawei/excelsior/aj/lang/AddrUInt;)Lcom/huawei/excelsior/aj/lang/AJCharArray;"), "(&)Lcom/huawei/excelsior/aj/lang/AJCharArray;", CHAR)
  case ManagedArrayIntrinsic_allocShortArray extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/ManagedArrayIntrinsics", mangleName("allocShortArray", "(Lcom/huawei/excelsior/aj/lang/AddrUInt;)Lcom/huawei/excelsior/aj/lang/AJShortArray;"), "(&)Lcom/huawei/excelsior/aj/lang/AJShortArray;", SHORT)
  case ManagedArrayIntrinsic_allocIntArray extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/ManagedArrayIntrinsics", mangleName("allocIntArray", "(Lcom/huawei/excelsior/aj/lang/AddrUInt;)Lcom/huawei/excelsior/aj/lang/AJIntArray;"), "(&)Lcom/huawei/excelsior/aj/lang/AJIntArray;", INT)
  case ManagedArrayIntrinsic_allocLongArray extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/ManagedArrayIntrinsics", mangleName("allocLongArray", "(Lcom/huawei/excelsior/aj/lang/AddrUInt;)Lcom/huawei/excelsior/aj/lang/AJLongArray;"), "(&)Lcom/huawei/excelsior/aj/lang/AJLongArray;", LONG)
  case ManagedArrayIntrinsic_allocFloatArray extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/ManagedArrayIntrinsics", mangleName("allocFloatArray", "(Lcom/huawei/excelsior/aj/lang/AddrUInt;)Lcom/huawei/excelsior/aj/lang/AJFloatArray;"), "(&)Lcom/huawei/excelsior/aj/lang/AJFloatArray;", FLOAT)
  case ManagedArrayIntrinsic_allocDoubleArray extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/ManagedArrayIntrinsics", mangleName("allocDoubleArray", "(Lcom/huawei/excelsior/aj/lang/AddrUInt;)Lcom/huawei/excelsior/aj/lang/AJDoubleArray;"), "(&)Lcom/huawei/excelsior/aj/lang/AJDoubleArray;", DOUBLE)

  case SoftExceptions_getIntFieldWithSoftException extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/excepts/SoftExceptions", mangleName("getIntFieldWithSoftException", "(Lcom/huawei/excelsior/aj/lang/AJObject;Lcom/huawei/excelsior/aj/lang/AddrUInt;Lcom/huawei/excelsior/jet/runtime/excepts/SoftExceptions$Kind;)I"), "(Lcom/huawei/excelsior/aj/lang/AJObject;&I)I", 1, INT)
  case SoftExceptions_getAddrUIntFieldWithSoftException extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/excepts/SoftExceptions", mangleName("getAddrUIntFieldWithSoftException", "(Lcom/huawei/excelsior/aj/lang/AJObject;Lcom/huawei/excelsior/aj/lang/AddrUInt;Lcom/huawei/excelsior/jet/runtime/excepts/SoftExceptions$Kind;)Lcom/huawei/excelsior/aj/lang/AddrUInt;"), "(Lcom/huawei/excelsior/aj/lang/AJObject;&I)&", 1)
  case SoftExceptions_genTDBarrier extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/excepts/SoftExceptions", "genTDBarrier", "(Lcom/huawei/excelsior/aj/lang/AJObject;)V")

  case FieldUpdaterIntrinsics_fieldOffset extends IntrinsicWithoutBody("com/huawei/excelsior/aj/internal/comp/FieldUpdaterIntrinsics", "fieldOffset", "(Ljava/lang/String;Ljava/lang/String;)I", 2, INT)

  case CriticalSection_incHeldLocks extends IntrinsicWithoutBody("com/huawei/excelsior/aj/os/CriticalSection", "incHeldLocks", "()V")
  case CriticalSection_decHeldLocks extends IntrinsicWithoutBody("com/huawei/excelsior/aj/os/CriticalSection", "decHeldLocks", "()V")

  case CheckedMath_checkedAdd8  extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/cangjie/CangjieUtils$CheckedMath", "checkedAdd8",  "(II)I")
  case CheckedMath_checkedAdd16 extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/cangjie/CangjieUtils$CheckedMath", "checkedAdd16", "(II)I")
  case CheckedMath_checkedAdd32 extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/cangjie/CangjieUtils$CheckedMath", "checkedAdd32", "(II)I")
  case CheckedMath_checkedAdd64 extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/cangjie/CangjieUtils$CheckedMath", "checkedAdd64", "(JJ)J")
  case CheckedMath_checkedSub8  extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/cangjie/CangjieUtils$CheckedMath", "checkedSub8",  "(II)I")
  case CheckedMath_checkedSub16 extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/cangjie/CangjieUtils$CheckedMath", "checkedSub16", "(II)I")
  case CheckedMath_checkedSub32 extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/cangjie/CangjieUtils$CheckedMath", "checkedSub32", "(II)I")
  case CheckedMath_checkedSub64 extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/cangjie/CangjieUtils$CheckedMath", "checkedSub64", "(JJ)J")
  case CheckedMath_checkedMul8  extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/cangjie/CangjieUtils$CheckedMath", "checkedMul8",  "(II)I")
  case CheckedMath_checkedMul16 extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/cangjie/CangjieUtils$CheckedMath", "checkedMul16", "(II)I")
  case CheckedMath_checkedMul32 extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/cangjie/CangjieUtils$CheckedMath", "checkedMul32", "(II)I")
  case CheckedMath_checkedMul64 extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/cangjie/CangjieUtils$CheckedMath", "checkedMul64", "(JJ)J")
  case CheckedMath_checkedDiv8  extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/cangjie/CangjieUtils$CheckedMath", "checkedDiv8",  "(II)I")
  case CheckedMath_checkedDiv16 extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/cangjie/CangjieUtils$CheckedMath", "checkedDiv16", "(II)I")
  case CheckedMath_checkedDiv32 extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/cangjie/CangjieUtils$CheckedMath", "checkedDiv32", "(II)I")
  case CheckedMath_checkedDiv64 extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/cangjie/CangjieUtils$CheckedMath", "checkedDiv64", "(JJ)J")
  case CheckedMath_checkedRem8  extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/cangjie/CangjieUtils$CheckedMath", "checkedRem8",  "(II)I")
  case CheckedMath_checkedRem16 extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/cangjie/CangjieUtils$CheckedMath", "checkedRem16", "(II)I")
  case CheckedMath_checkedRem32 extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/cangjie/CangjieUtils$CheckedMath", "checkedRem32", "(II)I")
  case CheckedMath_checkedRem64 extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/cangjie/CangjieUtils$CheckedMath", "checkedRem64", "(JJ)J")

  case CheckedMath_checkedUAdd8  extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/cangjie/CangjieUtils$CheckedMath", "checkedUAdd8",  "(II)I")
  case CheckedMath_checkedUAdd16 extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/cangjie/CangjieUtils$CheckedMath", "checkedUAdd16", "(II)I")
  case CheckedMath_checkedUAdd32 extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/cangjie/CangjieUtils$CheckedMath", "checkedUAdd32", "(II)I")
  case CheckedMath_checkedUAdd64 extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/cangjie/CangjieUtils$CheckedMath", "checkedUAdd64", "(JJ)J")
  case CheckedMath_checkedUSub8  extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/cangjie/CangjieUtils$CheckedMath", "checkedUSub8",  "(II)I")
  case CheckedMath_checkedUSub16 extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/cangjie/CangjieUtils$CheckedMath", "checkedUSub16", "(II)I")
  case CheckedMath_checkedUSub32 extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/cangjie/CangjieUtils$CheckedMath", "checkedUSub32", "(II)I")
  case CheckedMath_checkedUSub64 extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/cangjie/CangjieUtils$CheckedMath", "checkedUSub64", "(JJ)J")
  case CheckedMath_checkedUMul8  extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/cangjie/CangjieUtils$CheckedMath", "checkedUMul8",  "(II)I")
  case CheckedMath_checkedUMul16 extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/cangjie/CangjieUtils$CheckedMath", "checkedUMul16", "(II)I")
  case CheckedMath_checkedUMul32 extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/cangjie/CangjieUtils$CheckedMath", "checkedUMul32", "(II)I")
  case CheckedMath_checkedUMul64 extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/cangjie/CangjieUtils$CheckedMath", "checkedUMul64", "(JJ)J")

  // TODO: refactor all about intrinsics identification
  case XScalaMath_sin   extends IntrinsicWithoutBody("xscala/Math", "sin",           "(D)D",  DOUBLE)
  case XScalaMath_cos   extends IntrinsicWithoutBody("xscala/Math", "cos",           "(D)D",  DOUBLE)
  case XScalaMath_tan   extends IntrinsicWithoutBody("xscala/Math", "tan",           "(D)D",  DOUBLE)
  case XScalaMath_asin  extends IntrinsicWithoutBody("xscala/Math", "asin",          "(D)D",  DOUBLE)
  case XScalaMath_acos  extends IntrinsicWithoutBody("xscala/Math", "acos",          "(D)D",  DOUBLE)
  case XScalaMath_atan  extends IntrinsicWithoutBody("xscala/Math", "atan",          "(D)D",  DOUBLE)
  case XScalaMath_exp   extends IntrinsicWithoutBody("xscala/Math", "exp",           "(D)D",  DOUBLE)
  case XScalaMath_log   extends IntrinsicWithoutBody("xscala/Math", "log",           "(D)D",  DOUBLE)
  case XScalaMath_sqrt  extends IntrinsicWithoutBody("xscala/Math", "sqrt",          "(D)D",  DOUBLE)
  case XScalaMath_ceil  extends IntrinsicWithoutBody("xscala/Math", "ceil",          "(D)D",  DOUBLE)
  case XScalaMath_floor extends IntrinsicWithoutBody("xscala/Math", "floor",         "(D)D",  DOUBLE)
  case XScalaMath_rint  extends IntrinsicWithoutBody("xscala/Math", "rint",          "(D)D",  DOUBLE)
  case XScalaMath_atan2 extends IntrinsicWithoutBody("xscala/Math", "atan2",         "(DD)D", DOUBLE)
  case XScalaMath_pow   extends IntrinsicWithoutBody("xscala/Math", "pow",           "(DD)D", DOUBLE)
  case XScalaMath_rem1  extends IntrinsicWithoutBody("xscala/Math", "IEEEremainder", "(DD)D", DOUBLE)
  case XScalaMath_dabs  extends IntrinsicWithoutBody("xscala/Math", "abs",           "(D)D",  DOUBLE)
  case XScalaMath_fabs  extends IntrinsicWithoutBody("xscala/Math", "abs",           "(F)F",  FLOAT)

  case InvalidateExecEnv extends IntrinsicWithoutBody("com/huawei/excelsior/jet/runtime/thread/fibers/scheduling/SchedulingProhibited", "invalidateExecEnv", "()V")

  def this(className: String, methodName: String, signature: String, specialParamsCount: Int) = {
    this(className, methodName, signature, specialParamsCount, null)
  }

  def this(className: String, methodName: String, signature: String, opType: BytecodeTypeKind) = {
    this(className, methodName, signature, 0, opType)
  }

  def this(className: String, methodName: String, signature: String) = {
    this(className, methodName, signature, 0)
  }

  override def getClassName = XString.ascii(className)
  override def getMethodName = XString.ascii(methodName)
  override def getSignature = XString.ascii(signature.replace(Intrinsic.ADDR_SIG_PLACEHOLDER, TypeKind.address.getBCSignatureChar))
  override def getOpType = opType ensuring (_ != null)

  def getSpecialParamsCount = specialParamsCount
}
