/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.
 * This source file is part of the Cangjie project, licensed under Apache-2.0
 * with Runtime Library Exception.
 *
 * See https://cangjie-lang.cn/pages/LICENSE for license information.
 */

package com.huawei.excelsior.jet.compiler.intrinsics

import com.huawei.excelsior.jet.common.XString
import com.huawei.excelsior.jet.compiler.bytecode.BytecodeTypeKind
import com.huawei.excelsior.jet.compiler.bytecode.BytecodeTypeKind.*
import com.huawei.excelsior.jet.compiler.symlevel.TypeKind
import com.huawei.excelsior.jet.compiler.util.Names.AJ.mangleName

/** Intrinsics with body (should be generated by good optimizing compiler) */
enum IntrinsicWithBody(className: String, methodName: String, signature: String, opType: BytecodeTypeKind = null) extends Intrinsic {
  case ArrayAccessHelper_getByte extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/ArrayAccessHelper", mangleName("getByte", "(Lcom/huawei/excelsior/aj/lang/Address;I)B"), "(&I)B", BYTE)
  case ArrayAccessHelper_getShort extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/ArrayAccessHelper", mangleName("getShort", "(Lcom/huawei/excelsior/aj/lang/Address;I)S"), "(&I)S", SHORT)
  case ArrayAccessHelper_getChar extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/ArrayAccessHelper", mangleName("getChar", "(Lcom/huawei/excelsior/aj/lang/Address;I)C"), "(&I)C", CHAR)
  case ArrayAccessHelper_getInt extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/ArrayAccessHelper", mangleName("getInt", "(Lcom/huawei/excelsior/aj/lang/Address;I)I"), "(&I)I", INT)
  case ArrayAccessHelper_getLong extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/ArrayAccessHelper", mangleName("getLong", "(Lcom/huawei/excelsior/aj/lang/Address;I)J"), "(&I)J", LONG)
  case ArrayAccessHelper_getBoolean extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/ArrayAccessHelper", mangleName("getBoolean", "(Lcom/huawei/excelsior/aj/lang/Address;I)Z"), "(&I)Z", BOOLEAN)
  case ArrayAccessHelper_getFloat extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/ArrayAccessHelper", mangleName("getFloat", "(Lcom/huawei/excelsior/aj/lang/Address;I)F"), "(&I)F", FLOAT)
  case ArrayAccessHelper_getDouble extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/ArrayAccessHelper", mangleName("getDouble", "(Lcom/huawei/excelsior/aj/lang/Address;I)D"), "(&I)D", DOUBLE)

  case ArrayAccessHelper_setByte extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/ArrayAccessHelper", mangleName("setByte", "(Lcom/huawei/excelsior/aj/lang/Address;IB)V"), "(&IB)V", BYTE)
  case ArrayAccessHelper_setShort extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/ArrayAccessHelper", mangleName("setShort", "(Lcom/huawei/excelsior/aj/lang/Address;IS)V"), "(&IS)V", SHORT)
  case ArrayAccessHelper_setChar extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/ArrayAccessHelper", mangleName("setChar", "(Lcom/huawei/excelsior/aj/lang/Address;IC)V"), "(&IC)V", CHAR)
  case ArrayAccessHelper_setInt extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/ArrayAccessHelper", mangleName("setInt", "(Lcom/huawei/excelsior/aj/lang/Address;II)V"), "(&II)V", INT)
  case ArrayAccessHelper_setLong extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/ArrayAccessHelper", mangleName("setLong", "(Lcom/huawei/excelsior/aj/lang/Address;IJ)V"), "(&IJ)V", LONG)
  case ArrayAccessHelper_setBoolean extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/ArrayAccessHelper", mangleName("setBoolean", "(Lcom/huawei/excelsior/aj/lang/Address;IZ)V"), "(&IZ)V", BOOLEAN)
  case ArrayAccessHelper_setFloat extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/ArrayAccessHelper", mangleName("setFloat", "(Lcom/huawei/excelsior/aj/lang/Address;IF)V"), "(&IF)V", FLOAT)
  case ArrayAccessHelper_setDouble extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/ArrayAccessHelper", mangleName("setDouble", "(Lcom/huawei/excelsior/aj/lang/Address;ID)V"), "(&ID)V", DOUBLE)

  case ArrayAccessHelper_setStruct extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/ArrayAccessHelper", mangleName("setStruct", "(Lcom/huawei/excelsior/aj/lang/Address;ILcom/huawei/excelsior/aj/lang/StructType;)V"), "(&I&)V")
  case ArrayAccessHelper_getFlat extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/ArrayAccessHelper", mangleName("getFlat", "(Lcom/huawei/excelsior/aj/lang/Address;II)Lcom/huawei/excelsior/aj/lang/Address;"), "(&II)&")

  case UInt32_div extends IntrinsicWithBody("com/huawei/excelsior/aj/lang/UInt32", mangleName("div", "(Lcom/huawei/excelsior/aj/lang/UInt32;)Lcom/huawei/excelsior/aj/lang/UInt32;"), "(II)I")
  case UInt32_mod extends IntrinsicWithBody("com/huawei/excelsior/aj/lang/UInt32", mangleName("mod", "(Lcom/huawei/excelsior/aj/lang/UInt32;)Lcom/huawei/excelsior/aj/lang/UInt32;"), "(II)I")
  case UInt32_lss extends IntrinsicWithBody("com/huawei/excelsior/aj/lang/UInt32", mangleName("lss", "(Lcom/huawei/excelsior/aj/lang/UInt32;)Z"), "(II)Z")
  case UInt32_leq extends IntrinsicWithBody("com/huawei/excelsior/aj/lang/UInt32", mangleName("leq", "(Lcom/huawei/excelsior/aj/lang/UInt32;)Z"), "(II)Z")
  case UInt64_div extends IntrinsicWithBody("com/huawei/excelsior/aj/lang/UInt64", mangleName("div", "(Lcom/huawei/excelsior/aj/lang/UInt64;)Lcom/huawei/excelsior/aj/lang/UInt64;"), "(JJ)J")
  case UInt64_mod extends IntrinsicWithBody("com/huawei/excelsior/aj/lang/UInt64", mangleName("mod", "(Lcom/huawei/excelsior/aj/lang/UInt64;)Lcom/huawei/excelsior/aj/lang/UInt64;"), "(JJ)J")
  case UInt64_lss extends IntrinsicWithBody("com/huawei/excelsior/aj/lang/UInt64", mangleName("lss", "(Lcom/huawei/excelsior/aj/lang/UInt64;)Z"), "(JJ)Z")
  case UInt64_leq extends IntrinsicWithBody("com/huawei/excelsior/aj/lang/UInt64", mangleName("leq", "(Lcom/huawei/excelsior/aj/lang/UInt64;)Z"), "(JJ)Z")

  case MemoryBarrier_S_L extends IntrinsicWithBody("com/huawei/excelsior/aj/util/MemoryBarrier", "S_L", "()V")
  case MemoryBarrier_S_S extends IntrinsicWithBody("com/huawei/excelsior/aj/util/MemoryBarrier", "S_S", "()V")
  case MemoryBarrier_L_S extends IntrinsicWithBody("com/huawei/excelsior/aj/util/MemoryBarrier", "L_S", "()V")
  case MemoryBarrier_L_L extends IntrinsicWithBody("com/huawei/excelsior/aj/util/MemoryBarrier", "L_L", "()V")

  case EscapeWriteBarriers_instanceWriteBarrier extends IntrinsicWithBody("com/huawei/excelsior/jet/runtime/memory/gc/top/EscapeWriteBarriers", mangleName("instanceWriteBarrier", "(Lcom/huawei/excelsior/jet/runtime/jobject/ManagedEop;Lcom/huawei/excelsior/jet/runtime/jobject/ManagedEop;)Lcom/huawei/excelsior/jet/runtime/jobject/ManagedEop;"), "(Lcom/huawei/excelsior/aj/jetrt/ManagedEopType;Lcom/huawei/excelsior/aj/jetrt/ManagedEopType;)Lcom/huawei/excelsior/aj/jetrt/ManagedEopType;")
  case EscapeWriteBarriers_staticWriteBarrier extends IntrinsicWithBody("com/huawei/excelsior/jet/runtime/memory/gc/top/EscapeWriteBarriers", mangleName("staticWriteBarrier", "(Lcom/huawei/excelsior/jet/runtime/jobject/ManagedEop;)Lcom/huawei/excelsior/jet/runtime/jobject/ManagedEop;"), "(Lcom/huawei/excelsior/aj/jetrt/ManagedEopType;)Lcom/huawei/excelsior/aj/jetrt/ManagedEopType;")

  case GCBarriers_localReachabilityShield extends IntrinsicWithBody("com/huawei/excelsior/jet/runtime/memory/gc/GCBarriers", "localReachabilityShield", "(Lcom/huawei/excelsior/aj/lang/AJObject;)V")

  case UnmanagedMath_numberOfLeadingZeros_I extends IntrinsicWithBody("com/huawei/excelsior/aj/lang/UnmanagedMath", "numberOfLeadingZeros", "(I)I")
  case UnmanagedMath_numberOfLeadingZeros_L extends IntrinsicWithBody("com/huawei/excelsior/aj/lang/UnmanagedMath", "numberOfLeadingZeros", "(J)I")
  case UnmanagedMath_numberOfTrailingZeros_I extends IntrinsicWithBody("com/huawei/excelsior/aj/lang/UnmanagedMath", "numberOfTrailingZeros", "(I)I")
  case UnmanagedMath_numberOfTrailingZeros_L extends IntrinsicWithBody("com/huawei/excelsior/aj/lang/UnmanagedMath", "numberOfTrailingZeros", "(J)I")

  case UnmanagedMath_reinterpretCast_F2I extends IntrinsicWithBody("com/huawei/excelsior/aj/lang/UnmanagedMath", "reinterpretCast", "(F)I")
  case UnmanagedMath_reinterpretCast_I2F extends IntrinsicWithBody("com/huawei/excelsior/aj/lang/UnmanagedMath", "reinterpretCast", "(I)F")
  case UnmanagedMath_reinterpretCast_D2L extends IntrinsicWithBody("com/huawei/excelsior/aj/lang/UnmanagedMath", "reinterpretCast", "(D)J")
  case UnmanagedMath_reinterpretCast_L2D extends IntrinsicWithBody("com/huawei/excelsior/aj/lang/UnmanagedMath", "reinterpretCast", "(J)D")

  case UnmanagedMath_bitCount_I extends IntrinsicWithBody("com/huawei/excelsior/aj/lang/UnmanagedMath", "bitCount", "(I)I", INT)
  case UnmanagedMath_bitCount_L extends IntrinsicWithBody("com/huawei/excelsior/aj/lang/UnmanagedMath", "bitCount", "(J)I", LONG)

  case UnmanagedMath_bswapInt extends IntrinsicWithBody("com/huawei/excelsior/aj/lang/UnmanagedMath", "bswapInt", "(I)I", INT)
  case UnmanagedMath_bswapLong extends IntrinsicWithBody("com/huawei/excelsior/aj/lang/UnmanagedMath", "bswapLong", "(J)J", LONG)

  case UnmanagedMath_mulh32  extends IntrinsicWithBody("com/huawei/excelsior/aj/lang/UnmanagedMath",  "mulh", "(II)I", INT)
  case UnmanagedMath_umulh32 extends IntrinsicWithBody("com/huawei/excelsior/aj/lang/UnmanagedMath", "umulh", "(II)I", INT)
  case UnmanagedMath_mulh64  extends IntrinsicWithBody("com/huawei/excelsior/aj/lang/UnmanagedMath",  "mulh", "(JJ)J", LONG)
  case UnmanagedMath_umulh64 extends IntrinsicWithBody("com/huawei/excelsior/aj/lang/UnmanagedMath", "umulh", "(JJ)J", LONG)
  
  case CompilerHintIntrinsics_coldCode extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/comp/CompilerHintIntrinsics", "coldCode", "()I")
  case CompilerHintIntrinsics_hotCode extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/comp/CompilerHintIntrinsics", "hotCode", "()I")

  case ComputableAtCompileTime_isArray extends IntrinsicWithBody("com/huawei/excelsior/jet/runtime/metatype/CompileTimeComputable$ComputableAtCompileTime", "isArray", "(Lcom/huawei/excelsior/aj/lang/AJObject;)Z")
  case CompileTime_isArray extends IntrinsicWithBody("com/huawei/excelsior/jet/runtime/metatype/CompileTimeComputable$CompileTime", "isArray", "(Lcom/huawei/excelsior/aj/lang/AJObject;)Z")
  case ComputableAtCompileTime_isNull extends IntrinsicWithBody("com/huawei/excelsior/jet/runtime/metatype/CompileTimeComputable$ComputableAtCompileTime", "isNull", "(Lcom/huawei/excelsior/aj/lang/AJObject;)Z")
  case CompileTime_isNull extends IntrinsicWithBody("com/huawei/excelsior/jet/runtime/metatype/CompileTimeComputable$CompileTime", "isNull", "(Lcom/huawei/excelsior/aj/lang/AJObject;)Z")
  case ComputableAtCompileTime_hasTraceableFields extends IntrinsicWithBody("com/huawei/excelsior/jet/runtime/metatype/CompileTimeComputable$ComputableAtCompileTime", "hasTraceableFields", "(Lcom/huawei/excelsior/aj/lang/AJObject;)Z")
  case CompileTime_hasTraceableFields extends IntrinsicWithBody("com/huawei/excelsior/jet/runtime/metatype/CompileTimeComputable$CompileTime", "hasTraceableFields", "(Lcom/huawei/excelsior/aj/lang/AJObject;)Z")

  case ComputableAtCompileTime_getReferenceArrayElementFormalTypeName extends IntrinsicWithBody("com/huawei/excelsior/jet/runtime/metatype/JavaCompileTimeComputable$ComputableAtCompileTime", "getReferenceArrayElementFormalTypeName", "(Ljava/lang/Object;)Z")
  case CompileTime_getReferenceArrayElementFormalTypeName extends IntrinsicWithBody("com/huawei/excelsior/jet/runtime/metatype/JavaCompileTimeComputable$CompileTime", mangleName("getReferenceArrayElementFormalTypeName", "(Ljava/lang/Object;)Lcom/huawei/excelsior/aj/util/BString;"), "(Ljava/lang/Object;)&")
  case ComputableAtCompileTime_getComponentType extends IntrinsicWithBody("com/huawei/excelsior/jet/runtime/metatype/JavaCompileTimeComputable$ComputableAtCompileTime", "getComponentType", "(Ljava/lang/Class;)Z")
  case CompileTime_getComponentType extends IntrinsicWithBody("com/huawei/excelsior/jet/runtime/metatype/JavaCompileTimeComputable$CompileTime", "getComponentType", "(Ljava/lang/Class;)Ljava/lang/Class;")
  case ComputableAtCompileTime_getArrayDimNum extends IntrinsicWithBody("com/huawei/excelsior/jet/runtime/metatype/JavaCompileTimeComputable$ComputableAtCompileTime", mangleName("getArrayDimNum", "(Lcom/huawei/excelsior/jet/runtime/typedesc/JavaInstanceDescriptor;)Z"), "(&)Z")
  case CompileTime_getArrayDimNum extends IntrinsicWithBody("com/huawei/excelsior/jet/runtime/metatype/JavaCompileTimeComputable$CompileTime", mangleName("getArrayDimNum", "(Lcom/huawei/excelsior/jet/runtime/typedesc/JavaInstanceDescriptor;)I"), "(&)I")
  case ComputableAtCompileTime_getArrayElemLog2Size extends IntrinsicWithBody("com/huawei/excelsior/jet/runtime/metatype/JavaCompileTimeComputable$ComputableAtCompileTime", mangleName("getArrayElemLog2Size", "(Lcom/huawei/excelsior/jet/runtime/typedesc/JavaInstanceDescriptor;)Z"), "(&)Z")
  case CompileTime_getArrayElemLog2Size extends IntrinsicWithBody("com/huawei/excelsior/jet/runtime/metatype/JavaCompileTimeComputable$CompileTime", mangleName("getArrayElemLog2Size", "(Lcom/huawei/excelsior/jet/runtime/typedesc/JavaInstanceDescriptor;)I"), "(&)I")
  case ComputableAtCompileTime_hasPrimitiveArrayBaseType extends IntrinsicWithBody("com/huawei/excelsior/jet/runtime/metatype/JavaCompileTimeComputable$ComputableAtCompileTime", mangleName("hasPrimitiveArrayBaseType", "(Lcom/huawei/excelsior/jet/runtime/typedesc/JavaInstanceDescriptor;)Z"), "(&)Z")
  case CompileTime_hasPrimitiveArrayBaseType extends IntrinsicWithBody("com/huawei/excelsior/jet/runtime/metatype/JavaCompileTimeComputable$CompileTime", mangleName("hasPrimitiveArrayBaseType", "(Lcom/huawei/excelsior/jet/runtime/typedesc/JavaInstanceDescriptor;)Z"), "(&)Z")
  case ComputableAtCompileTime_isArrayClass extends IntrinsicWithBody("com/huawei/excelsior/jet/runtime/metatype/JavaCompileTimeComputable$ComputableAtCompileTime", "isArrayClass", "(Ljava/lang/Class;)Z")
  case CompileTime_isArrayClass extends IntrinsicWithBody("com/huawei/excelsior/jet/runtime/metatype/JavaCompileTimeComputable$CompileTime", "isArrayClass", "(Ljava/lang/Class;)Z")
  case ComputableAtCompileTime_isInstance extends IntrinsicWithBody("com/huawei/excelsior/jet/runtime/metatype/JavaCompileTimeComputable$ComputableAtCompileTime", "isInstance", "(Ljava/lang/Class;Ljava/lang/Object;)Z")
  case CompileTime_isInstance extends IntrinsicWithBody("com/huawei/excelsior/jet/runtime/metatype/JavaCompileTimeComputable$CompileTime", "isInstance", "(Ljava/lang/Class;Ljava/lang/Object;)Z")
  case ComputableAtCompileTime_isAssignable extends IntrinsicWithBody("com/huawei/excelsior/jet/runtime/metatype/JavaCompileTimeComputable$ComputableAtCompileTime", "isAssignable", "(Ljava/lang/Class;Ljava/lang/Class;)Z")
  case CompileTime_isAssignable extends IntrinsicWithBody("com/huawei/excelsior/jet/runtime/metatype/JavaCompileTimeComputable$CompileTime", "isAssignable", "(Ljava/lang/Class;Ljava/lang/Class;)Z")

  case AllocArray_newArray extends IntrinsicWithBody("com/huawei/excelsior/jet/runtime/memory/jalloc/AllocArray", "newArray", "(Ljava/lang/Object;I)[Ljava/lang/Object;")

  case FieldAccessHelper_getFlat extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/comp/ErasableFieldAccessHelper", mangleName("getFlat", "(Lcom/huawei/excelsior/aj/lang/Address;I)Lcom/huawei/excelsior/aj/lang/Address;"), "(&I)&")

  case FieldAccessHelper_getByte extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/comp/ErasableFieldAccessHelper", mangleName("getByte", "(Lcom/huawei/excelsior/aj/lang/Address;I)B"), "(&I)B", BYTE)
  case FieldAccessHelper_getShort extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/comp/ErasableFieldAccessHelper", mangleName("getShort", "(Lcom/huawei/excelsior/aj/lang/Address;I)S"), "(&I)S", SHORT)
  case FieldAccessHelper_getChar extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/comp/ErasableFieldAccessHelper", mangleName("getChar", "(Lcom/huawei/excelsior/aj/lang/Address;I)C"), "(&I)C", CHAR)
  case FieldAccessHelper_getInt extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/comp/ErasableFieldAccessHelper", mangleName("getInt", "(Lcom/huawei/excelsior/aj/lang/Address;I)I"), "(&I)I", INT)
  case FieldAccessHelper_getLong extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/comp/ErasableFieldAccessHelper", mangleName("getLong", "(Lcom/huawei/excelsior/aj/lang/Address;I)J"), "(&I)J", LONG)
  case FieldAccessHelper_getBoolean extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/comp/ErasableFieldAccessHelper", mangleName("getBoolean", "(Lcom/huawei/excelsior/aj/lang/Address;I)Z"), "(&I)Z", BOOLEAN)
  case FieldAccessHelper_getFloat extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/comp/ErasableFieldAccessHelper", mangleName("getFloat", "(Lcom/huawei/excelsior/aj/lang/Address;I)F"), "(&I)F", FLOAT)
  case FieldAccessHelper_getDouble extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/comp/ErasableFieldAccessHelper", mangleName("getDouble", "(Lcom/huawei/excelsior/aj/lang/Address;I)D"), "(&I)D", DOUBLE)

  case FieldAccessHelper_setByte extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/comp/ErasableFieldAccessHelper", mangleName("setByte", "(Lcom/huawei/excelsior/aj/lang/Address;IB)B"), "(&IB)B", BYTE)
  case FieldAccessHelper_setShort extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/comp/ErasableFieldAccessHelper", mangleName("setShort", "(Lcom/huawei/excelsior/aj/lang/Address;IS)S"), "(&IS)S", SHORT)
  case FieldAccessHelper_setChar extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/comp/ErasableFieldAccessHelper", mangleName("setChar", "(Lcom/huawei/excelsior/aj/lang/Address;IC)C"), "(&IC)C", CHAR)
  case FieldAccessHelper_setInt extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/comp/ErasableFieldAccessHelper", mangleName("setInt", "(Lcom/huawei/excelsior/aj/lang/Address;II)I"), "(&II)I", INT)
  case FieldAccessHelper_setLong extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/comp/ErasableFieldAccessHelper", mangleName("setLong", "(Lcom/huawei/excelsior/aj/lang/Address;IJ)J"), "(&IJ)J", LONG)
  case FieldAccessHelper_setBoolean extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/comp/ErasableFieldAccessHelper", mangleName("setBoolean", "(Lcom/huawei/excelsior/aj/lang/Address;IZ)Z"), "(&IZ)Z", BOOLEAN)
  case FieldAccessHelper_setFloat extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/comp/ErasableFieldAccessHelper", mangleName("setFloat", "(Lcom/huawei/excelsior/aj/lang/Address;IF)F"), "(&IF)F", FLOAT)
  case FieldAccessHelper_setDouble extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/comp/ErasableFieldAccessHelper", mangleName("setDouble", "(Lcom/huawei/excelsior/aj/lang/Address;ID)D"), "(&ID)D", DOUBLE)

  case JavaCallStackUtils_getCallerClassHandle extends IntrinsicWithBody("com/huawei/excelsior/jet/runtime/excepts/JavaCallStackUtils", mangleName("getCallerClassHandle", "(I)Lcom/huawei/excelsior/jet/runtime/typedesc/JavaTypeHandle;"), "(I)&")

  // TODO remove type
  case AtomicIntrinsics_atomicCASInt extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/AtomicIntrinsics", mangleName("compareAndSwap", "(Lcom/huawei/excelsior/aj/lang/Address;II)Z"), "(&II)Z", BOOLEAN)
  case AtomicIntrinsics_atomicCASLong extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/AtomicIntrinsics", mangleName("compareAndSwap", "(Lcom/huawei/excelsior/aj/lang/Address;JJ)Z"), "(&JJ)Z", BOOLEAN)

  case MemoryHints_prefetchForWrite extends IntrinsicWithBody("com/huawei/excelsior/jet/runtime/memory/MemoryHints", mangleName("prefetchForWrite", "(Lcom/huawei/excelsior/aj/lang/Address;)V"), "(&)V", VOID)

  // TODO: make mechanism for not AJ intrinsics, or rebrand this mechanism.
  case JavaMath_sin   extends IntrinsicWithBody("java/lang/Math", "sin",           "(D)D",  DOUBLE)
  case JavaMath_cos   extends IntrinsicWithBody("java/lang/Math", "cos",           "(D)D",  DOUBLE)
  case JavaMath_tan   extends IntrinsicWithBody("java/lang/Math", "tan",           "(D)D",  DOUBLE)
  case JavaMath_asin  extends IntrinsicWithBody("java/lang/Math", "asin",          "(D)D",  DOUBLE)
  case JavaMath_acos  extends IntrinsicWithBody("java/lang/Math", "acos",          "(D)D",  DOUBLE)
  case JavaMath_atan  extends IntrinsicWithBody("java/lang/Math", "atan",          "(D)D",  DOUBLE)
  case JavaMath_exp   extends IntrinsicWithBody("java/lang/Math", "exp",           "(D)D",  DOUBLE)
  case JavaMath_log   extends IntrinsicWithBody("java/lang/Math", "log",           "(D)D",  DOUBLE)
  case JavaMath_sqrt  extends IntrinsicWithBody("java/lang/Math", "sqrt",          "(D)D",  DOUBLE)
  case JavaMath_ceil  extends IntrinsicWithBody("java/lang/Math", "ceil",          "(D)D",  DOUBLE)
  case JavaMath_floor extends IntrinsicWithBody("java/lang/Math", "floor",         "(D)D",  DOUBLE)
  case JavaMath_rint  extends IntrinsicWithBody("java/lang/Math", "rint",          "(D)D",  DOUBLE)
  case JavaMath_atan2 extends IntrinsicWithBody("java/lang/Math", "atan2",         "(DD)D", DOUBLE)
  case JavaMath_pow   extends IntrinsicWithBody("java/lang/Math", "pow",           "(DD)D", DOUBLE)
  case JavaMath_rem1  extends IntrinsicWithBody("java/lang/Math", "IEEEremainder", "(DD)D", DOUBLE)
  case JavaMath_dabs  extends IntrinsicWithBody("java/lang/Math", "abs",           "(D)D",  DOUBLE)
  case JavaMath_fabs  extends IntrinsicWithBody("java/lang/Math", "abs",           "(F)F",  FLOAT)

  case Half_fromFloat extends IntrinsicWithBody("com/huawei/excelsior/aj/lang/Half", mangleName("fromFloat", "(F)Lcom/huawei/excelsior/aj/lang/Half;"), "(F)S", SHORT)
  case Half_toFloat extends IntrinsicWithBody("com/huawei/excelsior/aj/lang/Half", mangleName("toFloat", "()F"), "(S)F", FLOAT)

  case AJEnum_ordinal extends IntrinsicWithBody("com/huawei/excelsior/aj/lang/AJEnum", "ordinal", "()I")

  case MemBar_SL_SL extends IntrinsicWithBody("com/huawei/excelsior/aj/util/MemoryBarrier", "SL_SL", "()V")
  case MemBar_L_SL extends IntrinsicWithBody("com/huawei/excelsior/aj/util/MemoryBarrier", "L_SL", "()V")
  case MemBar_SL_L extends IntrinsicWithBody("com/huawei/excelsior/aj/util/MemoryBarrier", "SL_L", "()V")
  case MemBar_SL_S extends IntrinsicWithBody("com/huawei/excelsior/aj/util/MemoryBarrier", "SL_S", "()V")
  case MemBar_S_SL extends IntrinsicWithBody("com/huawei/excelsior/aj/util/MemoryBarrier", "S_SL", "()V")

  case MemAtomic_casByte extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/AtomicIntrinsics", mangleName("compareAndSwap", "(Lcom/huawei/excelsior/aj/lang/Address;BB)B"), "(&BB)B", BYTE)
  case MemAtomic_casShort extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/AtomicIntrinsics", mangleName("compareAndSwap", "(Lcom/huawei/excelsior/aj/lang/Address;SS)S"), "(&SS)S", SHORT)
  case MemAtomic_casInt extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/AtomicIntrinsics", mangleName("compareAndSwap", "(Lcom/huawei/excelsior/aj/lang/Address;II)I"), "(&II)I", INT)
  case MemAtomic_casLong extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/AtomicIntrinsics", mangleName("compareAndSwap", "(Lcom/huawei/excelsior/aj/lang/Address;JJ)J"), "(&JJ)J", LONG)

  case MemAtomic_addByte extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/AtomicIntrinsics", mangleName("fetchAdd", "(Lcom/huawei/excelsior/aj/lang/Address;B)B"), "(&B)B", BYTE)
  case MemAtomic_andByte extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/AtomicIntrinsics", mangleName("fetchAnd", "(Lcom/huawei/excelsior/aj/lang/Address;B)B"), "(&B)B", BYTE)
  case MemAtomic_orByte extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/AtomicIntrinsics", mangleName("fetchOr", "(Lcom/huawei/excelsior/aj/lang/Address;B)B"), "(&B)B", BYTE)
  case MemAtomic_xorByte extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/AtomicIntrinsics", mangleName("fetchXor", "(Lcom/huawei/excelsior/aj/lang/Address;B)B"), "(&B)B", BYTE)
  case MemAtomic_minByte extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/AtomicIntrinsics", mangleName("fetchMin", "(Lcom/huawei/excelsior/aj/lang/Address;B)B"), "(&B)B", BYTE)
  case MemAtomic_maxByte extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/AtomicIntrinsics", mangleName("fetchMax", "(Lcom/huawei/excelsior/aj/lang/Address;B)B"), "(&B)B", BYTE)
  case MemAtomic_swapByte extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/AtomicIntrinsics", mangleName("swap", "(Lcom/huawei/excelsior/aj/lang/Address;B)B"), "(&B)B", BYTE)

  case MemAtomic_addShort extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/AtomicIntrinsics", mangleName("fetchAdd", "(Lcom/huawei/excelsior/aj/lang/Address;S)S"), "(&S)S", SHORT)
  case MemAtomic_andShort extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/AtomicIntrinsics", mangleName("fetchAnd", "(Lcom/huawei/excelsior/aj/lang/Address;S)S"), "(&S)S", SHORT)
  case MemAtomic_orShort extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/AtomicIntrinsics", mangleName("fetchOr", "(Lcom/huawei/excelsior/aj/lang/Address;S)S"), "(&S)S", SHORT)
  case MemAtomic_xorShort extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/AtomicIntrinsics", mangleName("fetchXor", "(Lcom/huawei/excelsior/aj/lang/Address;S)S"), "(&S)S", SHORT)
  case MemAtomic_minShort extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/AtomicIntrinsics", mangleName("fetchMin", "(Lcom/huawei/excelsior/aj/lang/Address;S)S"), "(&S)S", SHORT)
  case MemAtomic_maxShort extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/AtomicIntrinsics", mangleName("fetchMax", "(Lcom/huawei/excelsior/aj/lang/Address;S)S"), "(&S)S", SHORT)
  case MemAtomic_swapShort extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/AtomicIntrinsics", mangleName("swap", "(Lcom/huawei/excelsior/aj/lang/Address;S)S"), "(&S)S", SHORT)

  case MemAtomic_addInt extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/AtomicIntrinsics", mangleName("fetchAdd", "(Lcom/huawei/excelsior/aj/lang/Address;I)I"), "(&I)I", INT)
  case MemAtomic_andInt extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/AtomicIntrinsics", mangleName("fetchAnd", "(Lcom/huawei/excelsior/aj/lang/Address;I)I"), "(&I)I", INT)
  case MemAtomic_orInt extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/AtomicIntrinsics", mangleName("fetchOr", "(Lcom/huawei/excelsior/aj/lang/Address;I)I"), "(&I)I", INT)
  case MemAtomic_xorInt extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/AtomicIntrinsics", mangleName("fetchXor", "(Lcom/huawei/excelsior/aj/lang/Address;I)I"), "(&I)I", INT)
  case MemAtomic_minInt extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/AtomicIntrinsics", mangleName("fetchMin", "(Lcom/huawei/excelsior/aj/lang/Address;I)I"), "(&I)I", INT)
  case MemAtomic_uminInt extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/AtomicIntrinsics", mangleName("fetchMin", "(Lcom/huawei/excelsior/aj/lang/Address;Lcom/huawei/excelsior/aj/lang/UInt32;)Lcom/huawei/excelsior/aj/lang/UInt32;"), "(&I)I", INT)
  case MemAtomic_maxInt extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/AtomicIntrinsics", mangleName("fetchMax", "(Lcom/huawei/excelsior/aj/lang/Address;I)I"), "(&I)I", INT)
  case MemAtomic_umaxInt extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/AtomicIntrinsics", mangleName("fetchMax", "(Lcom/huawei/excelsior/aj/lang/Address;Lcom/huawei/excelsior/aj/lang/UInt32;)Lcom/huawei/excelsior/aj/lang/UInt32;"), "(&I)I", INT)
  case MemAtomic_swapInt extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/AtomicIntrinsics", mangleName("swap", "(Lcom/huawei/excelsior/aj/lang/Address;I)I"), "(&I)I", INT)

  case MemAtomic_addLong extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/AtomicIntrinsics", mangleName("fetchAdd", "(Lcom/huawei/excelsior/aj/lang/Address;J)J"), "(&J)J", LONG)
  case MemAtomic_andLong extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/AtomicIntrinsics", mangleName("fetchAnd", "(Lcom/huawei/excelsior/aj/lang/Address;J)J"), "(&J)J", LONG)
  case MemAtomic_orLong extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/AtomicIntrinsics", mangleName("fetchOr", "(Lcom/huawei/excelsior/aj/lang/Address;J)J"), "(&J)J", LONG)
  case MemAtomic_xorLong extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/AtomicIntrinsics", mangleName("fetchXor", "(Lcom/huawei/excelsior/aj/lang/Address;J)J"), "(&J)J", LONG)
  case MemAtomic_minLong extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/AtomicIntrinsics", mangleName("fetchMin", "(Lcom/huawei/excelsior/aj/lang/Address;J)J"), "(&J)J", LONG)
  case MemAtomic_uminLong extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/AtomicIntrinsics", mangleName("fetchMin", "(Lcom/huawei/excelsior/aj/lang/Address;Lcom/huawei/excelsior/aj/lang/UInt64;)Lcom/huawei/excelsior/aj/lang/UInt64;"), "(&J)J", LONG)
  case MemAtomic_maxLong extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/AtomicIntrinsics", mangleName("fetchMax", "(Lcom/huawei/excelsior/aj/lang/Address;J)J"), "(&J)J", LONG)
  case MemAtomic_umaxLong extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/AtomicIntrinsics", mangleName("fetchMax", "(Lcom/huawei/excelsior/aj/lang/Address;Lcom/huawei/excelsior/aj/lang/UInt64;)Lcom/huawei/excelsior/aj/lang/UInt64;"), "(&J)J", LONG)
  case MemAtomic_swapLong extends IntrinsicWithBody("com/huawei/excelsior/aj/internal/AtomicIntrinsics", mangleName("swap", "(Lcom/huawei/excelsior/aj/lang/Address;J)J"), "(&J)J", LONG)
  case GCBarriers_beginLocalUnmovable extends IntrinsicWithBody("com/huawei/excelsior/jet/runtime/memory/gc/GCBarriers", mangleName("beginLocalUnmovable", "(Lcom/huawei/excelsior/aj/lang/AJObject;)Lcom/huawei/excelsior/jet/runtime/memory/gc/GCBarriers$UnmovableHandle;"), "(Lcom/huawei/excelsior/aj/lang/AJObject;)Lcom/huawei/excelsior/aj/lang/AJObject;")
  case GCBarriers_endLocalUnmovable extends IntrinsicWithBody("com/huawei/excelsior/jet/runtime/memory/gc/GCBarriers", mangleName("endLocalUnmovable", "(Lcom/huawei/excelsior/jet/runtime/memory/gc/GCBarriers$UnmovableHandle;)V"), "(Lcom/huawei/excelsior/aj/lang/AJObject;)V")

  case Address_loadAcquireByte extends IntrinsicWithBody("com/huawei/excelsior/aj/lang/Address", mangleName("loadAcquireByte", "()B"), "(&)B", BYTE)
  case Address_loadAcquireBoolean extends IntrinsicWithBody("com/huawei/excelsior/aj/lang/Address", mangleName("loadAcquireBoolean", "()Z"), "(&)Z", BOOLEAN)
  case Address_loadAcquireShort extends IntrinsicWithBody("com/huawei/excelsior/aj/lang/Address", mangleName("loadAcquireShort", "()S"), "(&)S", SHORT)
  case Address_loadAcquireChar extends IntrinsicWithBody("com/huawei/excelsior/aj/lang/Address", mangleName("loadAcquireChar", "()C"), "(&)C", CHAR)
  case Address_loadAcquireInt extends IntrinsicWithBody("com/huawei/excelsior/aj/lang/Address", mangleName("loadAcquireInt", "()I"), "(&)I", INT)
  case Address_loadAcquireLong extends IntrinsicWithBody("com/huawei/excelsior/aj/lang/Address", mangleName("loadAcquireLong", "()J"), "(&)J", LONG)
  case Address_loadAcquireFloat extends IntrinsicWithBody("com/huawei/excelsior/aj/lang/Address", mangleName("loadAcquireFloat", "()F"), "(&)F", FLOAT)
  case Address_loadAcquireDouble extends IntrinsicWithBody("com/huawei/excelsior/aj/lang/Address", mangleName("loadAcquireDouble", "()D"), "(&)D", DOUBLE)
  case Address_storeReleaseByte extends IntrinsicWithBody("com/huawei/excelsior/aj/lang/Address", mangleName("storeReleaseByte", "(B)V"), "(&B)V", BYTE)
  case Address_storeReleaseBoolean extends IntrinsicWithBody("com/huawei/excelsior/aj/lang/Address", mangleName("storeReleaseBoolean", "(Z)V"), "(&Z)V", BOOLEAN)
  case Address_storeReleaseShort extends IntrinsicWithBody("com/huawei/excelsior/aj/lang/Address", mangleName("storeReleaseShort", "(S)V"), "(&S)V", SHORT)
  case Address_storeReleaseChar extends IntrinsicWithBody("com/huawei/excelsior/aj/lang/Address", mangleName("storeReleaseChar", "(C)V"), "(&C)V", CHAR)
  case Address_storeReleaseInt extends IntrinsicWithBody("com/huawei/excelsior/aj/lang/Address", mangleName("storeReleaseInt", "(I)V"), "(&I)V", INT)
  case Address_storeReleaseLong extends IntrinsicWithBody("com/huawei/excelsior/aj/lang/Address", mangleName("storeReleaseLong", "(J)V"), "(&J)V", LONG)
  case Address_storeReleaseFloat extends IntrinsicWithBody("com/huawei/excelsior/aj/lang/Address", mangleName("storeReleaseFloat", "(F)V"), "(&F)V", FLOAT)
  case Address_storeReleaseDouble extends IntrinsicWithBody("com/huawei/excelsior/aj/lang/Address", mangleName("storeReleaseDouble", "(D)V"), "(&D)V", DOUBLE)
  case Address_loadAcquireAddr extends IntrinsicWithBody("com/huawei/excelsior/aj/lang/Address", mangleName("loadAcquireAddr", "()Lcom/huawei/excelsior/aj/lang/Address;"), "(&)&")
  case Address_storeReleaseAddr extends IntrinsicWithBody("com/huawei/excelsior/aj/lang/Address", mangleName("storeReleaseAddr", "(Lcom/huawei/excelsior/aj/lang/Address;)V"), "(&&)V")

  override def getClassName = XString.ascii(className)
  override def getMethodName = XString.ascii(methodName)
  override def getSignature = XString.ascii(signature.replace(Intrinsic.ADDR_SIG_PLACEHOLDER, TypeKind.address.getBCSignatureChar))
  override def getOpType = opType ensuring (_ != null)
}
