/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.
 * This source file is part of the Cangjie project, licensed under Apache-2.0
 * with Runtime Library Exception.
 *
 * See https://cangjie-lang.cn/pages/LICENSE for license information.
 */

package com.huawei.excelsior.jet.compiler.opt.lowering

import com.huawei.excelsior.common.Arch.CBC
import com.huawei.excelsior.common.CodeHelpers.*
import com.huawei.excelsior.jet.codeemitter.SymbolInfo.AccessKind
import com.huawei.excelsior.jet.compiler.Env.targetArch
import com.huawei.excelsior.jet.compiler.opt.ir.Universe
import com.huawei.excelsior.jet.compiler.options.BoolOption.NoTauTests
import com.huawei.excelsior.jet.compiler.types.Guards.{CHABitGuard, ConeGuard, LevelGuard, PointGuard, TypeGuard}
import com.huawei.excelsior.jet.compiler.types.ReferenceTypes.ClassType
import com.huawei.excelsior.jet.compiler.{RTConst, RTSProc, symlevel}
import com.huawei.excelsior.jet.compiler.symlevel.TypeKind.*
import com.huawei.excelsior.jet.compiler.symlevel.Type.asClassType
import com.huawei.excelsior.jet.compiler.types.CHA

import scala.annotation.nowarn

/**
 * Lowering of type check operations - all kinds of casts and instanceof.
 *
 * @author alexm
 */
private[lowering] trait TypeChecks extends Toolbox { self: Universe =>

  /** Lowers CheckCast operation. Returns resulting value. */
  private[lowering] def lowerCheckCast(checkCast: CheckCast): Unit = {
    checkCast match {
      case pc: PureCheck if pc.trusted =>
        // Trusted checks should have no uses (e.g. trusted check cast in JET-13229).
        assert(pc.valueUses.isEmpty)
        // TODO: generate check with fatal in work mode
        return
      case _ =>
    }

    assert (checkCast.inMemory == currentMemory)

    val obj = checkCast.obj
    val targetType = checkCast.targetType.symType

    assert(!targetType.isDeferred)

    if (isFastTypeCheck(targetType)) {
      val (nullEdge, doneEdges, throwEdges) = genFastTypeCheck(obj, targetType)
      val (rtsProc, args) = checkCast.throwInfo
      coldBlockWithErrorRTSCallAndHalt(throwEdges: _*)(checkCast, rtsProc, args: _*)
      continue(doneEdges :+ nullEdge :_*)

    } else {
      targetType.getKind match {
        case ARRAY =>
          assert(!targetType.isAJArray && !targetType.isCangjieArray, targetType)
          val proc = if (targetType.isXScalaType) RTSProc.JR_ScalaArrayCast else RTSProc.JR_ArrayCast
          RTSCall(proc)(obj, TypeHandle(targetType))

        case INTERFACE =>
          lowerInterfaceCheckCast(checkCast)

        case _ => shouldNotReachHere("CheckCast operation with unexpected target type " + targetType)
      }
    }
  }

  /** Returns `true` iff the type check to given type should be generated by inlined code. */
  private[lowering] def isFastTypeCheck(targetType: symlevel.Type): Boolean = {
    targetType.getKind match {
      case CLASS =>
        true
      case ARRAY =>
        !targetType.getArrayBase.isInterface
      case INTERFACE =>
        false
      case _ =>
        shouldNotReachHere("type check with unexpected target type " + targetType)
    }
  }

  /** Generates fast-path (inlined code) for type check.
    * Checks whether object is null. Cast to java.lang.Object should be checked beforehand.
    *
    * @return tuple of (control edge which correspond to null object case,
    *                   positive results (edges), negative results)
    */
  private def genFastTypeCheck(obj: Node, targetType: symlevel.Type): (BlockExit, Seq[BlockExit], Seq[BlockExit]) = {
    val nullEdge = makeNullTest(obj)

    val (yesEdges, noEdges) =
      targetType.getKind match {
        case CLASS => genFastClassTypeCheck(obj, targetType)
        case ARRAY => genFastArrayTypeCheck(obj, targetType)
        case _ => shouldNotReachHere("Unsupported fast type check for type kind: " + targetType.getKind)
      }

    (nullEdge, yesEdges, noEdges)
  }

  /**
    * Generates code for class type check. Object is already checked for null.
    *
    * @return tuple of (positive results (edges), negative results)
    */
  private def genFastClassTypeCheck(obj: Node, targetType: symlevel.Type, clearCCBit: Boolean = true): (Seq[BlockExit], Seq[BlockExit]) = {
    assert(targetType.isClass)
    assert(!targetType.isThinClass)
    assert(!targetType.isJavaLangObject || isO1Compiled)

    if (targetType.isFinal) {
      genFinalTypeCheck(obj, targetType)

    } else {
      val classType = ClassType(asClassType(targetType))
      val addrEQ = if (CHA.isKnownType(classType) && CHA.subClasses(classType).isEmpty) {
        val desc = genInstanceDescriptorAddr(obj)
        val targetDesc = RawInstanceDescriptor(targetType)
        val checkDesc = ifAddrEq(desc, targetDesc)
        continue(checkDesc.falseExit)
        ColdCodeMarker()
        Seq(checkDesc.trueExit)

      } else {
        Nil
      }

      val (trueExits, falseExits) = genJavaCohenCheck(obj, targetType, clearCCBit)
      (addrEQ ++ trueExits, falseExits)
    }
  }

  private def genFinalTypeCheck(obj: Node, targetType: symlevel.Type) = {
    val desc = genInstanceDescriptorAddr(obj)
    val targetDesc = RawInstanceDescriptor(targetType)
    val checkDesc = ifAddrEq(desc, targetDesc)
    (Seq(checkDesc.trueExit), Seq(checkDesc.falseExit))
  }

  private def genJavaCohenCheck(obj: Node, targetType: symlevel.Type, clearCCBit: Boolean = true): (Seq[BlockExit], Seq[BlockExit]) = {
    def patchAddr(addr: Node): Node = {
      if (clearCCBit) And(addr, IntegralConst(AddrIntType)(~RTConst.CohenDisplay.CC_BIT.intValue))
      else addr
    }

    assert(!targetType.isThinClass)

    val desc = genInstanceDescriptorAddr(obj)
    val targetDesc = RawInstanceDescriptor(targetType)
    val level = targetType.getCohenLevel
    assert(level > 0)
    if (level <= RTConst.CohenDisplay.INLINED_SIZE.intValue) {
      val cohenDesc = patchAddr(GetField(RT.InstanceDescriptor.inlinedCohenDesc(level))(desc))
      val checkCohenDesc = ifAddrEq(cohenDesc, targetDesc)
      (Seq(checkCohenDesc.trueExit), Seq(checkCohenDesc.falseExit))

    } else {
      val cohenLevel = genCohenLevel(desc)
      val checkLevel = If(Cmp(IntType, Condition.GE)(cohenLevel, IConst(level)))

      continue(checkLevel.trueExit)
      val outlined = GetField(RT.InstanceDescriptor.outlinedCohenDisplay)(desc)
      val cohenDesc = patchAddr(GetField(RT.InstanceDescriptor.outlinedCohenDesc(level))(outlined))
      val checkCohenDesc = ifAddrEq(cohenDesc, targetDesc)
      (Seq(checkCohenDesc.trueExit), Seq(checkLevel.falseExit, checkCohenDesc.falseExit))
    }
  }

  /** Generates code for Thin class type check. `obj` should already be checked for null.
    *
    * @return tuple of (positive results (edges), negative results)
    */
  private def genThinClassTypeCheck(obj: Node, targetType: symlevel.ClassType): (Seq[BlockExit], Seq[BlockExit]) = {
    assert(targetType.isThinClass)
    assert(obj.tpe == ThinType)

    val level = targetType.getCohenLevel
    assert(level > 0, "type checks with PolyThinType target should not reach lowering")

    val desc = genInstanceDescriptorAddr(obj)
    val targetDesc = ThinTypeHandle(targetType)

    if (targetType.isFinal) {
      val checkDesc = ifAddrEq(desc, targetDesc)
      (Seq(checkDesc.trueExit), Seq(checkDesc.falseExit))
    } else {
      val cohenLevel = GetField(RT.ThinTypeHandle.cohenLevel)(desc)
      val checkLevel = If(Cmp(IntType, Condition.GE)(cohenLevel, IConst(level)))

      continue(checkLevel.trueExit)
      val cohenDesc = GetField(RT.ThinTypeHandle.cohenDesc(level))(desc)
      val checkCohenDesc = ifAddrEq(cohenDesc, targetDesc)
      (Seq(checkCohenDesc.trueExit), Seq(checkLevel.falseExit, checkCohenDesc.falseExit))
    }
  }

  /**
    * Generates code for fast array type check. Object is already checked for null.
    *
    * @return tuple of (positive results (edges), negative results)
    */
  private def genFastArrayTypeCheck(obj: Node, targetType: symlevel.Type): (Seq[BlockExit], Seq[BlockExit]) = {
    assert (targetType.getKind == ARRAY)

    val baseType = targetType.getArrayBase
    assert (!baseType.isInterface)

    if (baseType.isPrimitive || baseType.isFinal) {
      genFinalTypeCheck(obj, targetType)

    } else {
      genJavaCohenCheck(obj, targetType)
    }
  }

  protected def lowerInterfaceCheckCast(checkCast: CheckCast): Unit = {
    val itableOffset = genInterfaceTypeCheckCall(checkCast)
    adjustDependingWeakCasts(checkCast, itableOffset)
  }

  /** Lowers InstanceOf operation. Returns resulting value. */
  private[lowering] def lowerInstanceOf(instanceOf: InstanceOf): Node = {
    val obj = instanceOf.obj
    val targetType = instanceOf.targetType.symType

    assert(!targetType.isDeferred)

    if (isFastTypeCheck(targetType)) {
      val (nullEdge, trueEdges, falseEdges) = genFastTypeCheck(obj, targetType)
      join(trueEdges.map(IConst(1) at _) ++ (falseEdges :+ nullEdge).map(IConst(0) at _) :_*)

    } else {
      targetType.getKind match {
        case ARRAY =>
          assert(!targetType.isAJArray && !targetType.isCangjieArray, targetType)
          val proc = if (targetType.isXScalaType) RTSProc.JR_ScalaArrayIs else RTSProc.JR_ArrayIs
          RTSCall(proc)(obj, TypeHandle(targetType))

        case INTERFACE =>
          lowerInterfaceInstanceOf(instanceOf)

        case _ => shouldNotReachHere("InstanceOf operation with unexpected target type " + targetType)
      }
    }
  }

  /** Lowers interface instanceof. Returns resulting value. */
  protected def lowerInterfaceInstanceOf(instanceOf: InstanceOf): Node = {
    // TODO: eliminate copy-paste with lowerInterfaceCheckCast
    val itableOffset = genInterfaceTypeCheckCall(instanceOf)
    adjustDependingWeakCasts(instanceOf, itableOffset)

    CondVal(Cmp(AddrIntType, Condition.GE)(itableOffset, IntegralConst(AddrIntType)(0)))
  }

  private def genInterfaceTypeCheckCall(check: AbstractTypeCheck) = {
    assert(check.targetType.isInterface)
    val (proc, cacheSize) = (check: @unchecked) match {
      case _: CheckCast => (RT.IFaceOps.cast(check.shouldBeInlined), RTConst.InterfCast1LCache.size)
      case _: InstanceOf => (RT.IFaceOps.instanceOf(check.shouldBeInlined), RTConst.InterfInstanceofCacheEx.size)
    }
    val obj = check.obj
    val itype = TypeHandle(check.targetType.symType)
    val cache = SymbolAddress(symbolLinker.makeUninitializedData(cacheSize))
    if (check.shouldBeInlined) {
      inlinedCall(proc)(obj, itype, cache)
    } else {
      DirectCall(proc)(obj, itype, cache)
    }
  }

  private[lowering] def adjustDependingWeakCasts(check: AbstractTypeCheck, itableOffset: Node): Unit = {
    check replaceUses {  case Edge(_, wc: WeakCast) =>
      assert(wc.targetType == check.targetType.symType)
      wc.replaceUsesBy(itableOffset)
      WeakCast.NoCheck()
    }
  }

  protected def genWeakCast(obj: Node, itype: symlevel.Type): Node = {
    val cache = SymbolAddress(symbolLinker.makeUninitializedData(RTConst.InterfCast1LCache.size))
    DirectCall(RT.IFaceOps.weakCast)(obj, TypeHandle(itype), cache)
  }

  protected def genWeakCastNoCache(obj: Node, itype: symlevel.Type): Node = {
    DirectCall(RT.IFaceOps.weakCastNoCache)(obj, TypeHandle(itype))
  }

  private def genBackupWeakCast(obj: Node, itype: symlevel.Type): Node = {
    ColdCodeMarker()
    if (useCacheForBackupWeakCast) genWeakCast(obj, itype) else genWeakCastNoCache(obj, itype)
  }

  protected def useCacheForBackupWeakCast: Boolean

  /** Lowers WeakCast operation. Returns resulting value. */
  private[lowering] def lowerWeakCast(weakCast: WeakCast): Node = {
    if (weakCast.uses.isEmpty) {
      return null // weakCast uses was replaced in adjustDependingWeakCasts()
    }

    // InstanceOf isn't lowered on CBC platform so WeakCast can have dominating check
    assert (targetArch == CBC || !weakCast.hasDominatingCheck)

    val itype = weakCast.targetType

    weakCast.obj match {
      case d @ Deprive(`itype`, rich) =>
        assert(!d.isLoweredWithWeakCast)
        val (_, offs) = genRichDecomposition(rich, itype, genBackupWeakCast(_, itype))
        offs

      case obj => genWeakCast(obj, itype)
    }
  }

  /** Lowers Deprive operation. Returns resulting value. */
  private[lowering] def lowerDeprive(deprive: Deprive): Node = {
    val itype = deprive.interfaceType
    if (deprive.isLoweredWithWeakCast) {
      val Some(weakCast) = deprive.uses.collectFirst {
        case wc @ WeakCast(`itype`, `deprive`) if !wc.hasDominatingCheck => wc
      }

      val (obj, offs) = genRichDecomposition(deprive.obj, itype, genBackupWeakCast(_, itype))
      // it is safe to replace all uses of this weak cast (see `PreLowering#processWeakCasts`)
      weakCast.replaceUsesBy(offs)
      obj
    } else {
      val (obj, _) = genRichDecomposition(deprive.obj, itype, _ => NoValue())
      obj
    }
  }

  /** Lowers Enrich operation if enriched pointers are disabled. Returns resulting value. */
  private[lowering] def lowerEnrich(enrich: Enrich): Node = {
    assert(!useEnrichedPointers)
    val obj = enrich.obj
    ReinterpretCast(obj.tpe, enrich.tpe)(obj)
  }

  /** Lowers ThinCheckCast operation. */
  private[lowering] def lowerThinCheckCast(thinCast: ThinCheckCast): Unit = {
    val targetType = thinCast.targetType ensuring (_.isThinClass)

    if (!thinCast.trusted) { // trusted ThinCheckCast is ALWAYS no-op
      val obj = thinCast.obj
      val nullEdge = makeNullTest(obj)
      val (passedEdges, failedEdges) = genThinClassTypeCheck(obj, targetType)

      val thinAddr = ReinterpretCast(ThinType, AddrType)(obj)
      coldBlockWithErrorRTSCallAndHalt(failedEdges: _*)(thinCast, RTSProc.ThinObj_castFailedError, thinAddr, ThinTypeHandle(targetType))

      continue(passedEdges :+ nullEdge : _*)
    }
  }

  /** Lowers ThinInstanceOf operation. */
  private[lowering] def lowerThinInstanceOf(thinInstanceOf: ThinInstanceOf): Node = {
    val obj = thinInstanceOf.obj
    val targetType = thinInstanceOf.targetType ensuring (_.isThinClass)

    val nullEdge = makeNullTest(obj)
    val (yesEdges, noEdges) = genThinClassTypeCheck(obj, asClassType(targetType))

    join(yesEdges.map(IConst(1) at _) ++ (noEdges :+ nullEdge).map(IConst(0) at _) :_*)
  }

  @nowarn("msg=match may not be exhaustive")
  private[lowering] def lowerTauTest(test: TauTest): Node = {
    assert(!env.enabled(NoTauTests))
    assert(!(test.obj.tpe == ThinType), "tau tests not implemented for Thin classes")
    test match {
      case MethodTest(obj, originalRef, target, ciao) =>
        assert(targetArch != CBC)

        val targetHost = target.getDeclaringClass
        val targetMethodAddr = symbolLinker.accessKind(targetHost.getTypeHandle) match {
          case AccessKind.DIRECT => SymbolAddress(target)

          case AccessKind.FAR => shouldNotReachHere()
        }

        val desc = genInstanceDescriptorAddr(obj)
        val methodAddr = if (originalRef.isInterfCall) {
          genInterfaceMethodAddr(desc, originalRef.virtualMethodSlot, ciao)
        } else if (originalRef.refClass.isJavaReference) {
          genJavaVirtualMethodAddr(desc, originalRef.virtualMethodSlot)
        } else if (originalRef.refClass.isXScalaType) {
          genScalaVirtualMethodAddr(desc, originalRef.virtualMethodSlot)
        } else if (originalRef.refClass.isCangjieType) {
          genCangjieVirtualMethodAddr(desc, originalRef.virtualMethodSlot)
        } else {
          assert(originalRef.refClass.isAJManagedType)
          genManagedVirtualMethodAddr(desc, originalRef.virtualMethodSlot)
        }

        Cmp(AddrType, Condition.EQ)(methodAddr, targetMethodAddr)

      case TypeTest(tg) => genTypeGuardTest(tg, test.obj)
    }
  }

  protected[lowering] def genTypeGuardTest(guard: TypeGuard, obj: Node) = guard match {
    case CHABitGuard =>
      val tsWord = GetField(RT.ManagedObj.tsWordConst)(obj)
      Cmp(IntType, Condition.NE)(
        And(tsWord, IConst(1 << RTConst.ObjTag.CHA_BIT.intValue)),
        IConst(0)
      )

    case PointGuard(klass) =>
      val desc = genInstanceDescriptorAddr(obj)
      Cmp(AddrType, Condition.EQ)(desc, RawInstanceDescriptor(klass))

    case LevelGuard(guardLevel) =>
      val desc = genInstanceDescriptorAddr(obj)
      val level = genCohenLevel(desc, clearLevelBit = false)
      Cmp(IntType, Condition.LE)(level, IConst(guardLevel))

    case ConeGuard(root, closed) =>
      genConeTest(obj, root, closed)

    case _ => shouldNotReachHere(guard)
  }

  private def genConeTest(obj: Node, root: symlevel.Type, closed: Boolean): Node = {
    val (trueExits, falseExits) = genFastClassTypeCheck(obj, root, clearCCBit = !closed)
    val trueValues  = trueExits  map (IConst(1) at _)
    val falseValues = falseExits map (IConst(0) at _)
    val result = join(trueValues ++ falseValues: _*)
    Cmp(IntType, Condition.NE)(
      result,
      IConst(0)
    )
  }

}
