%% Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.
%% This source file is part of the Cangjie project, licensed under Apache-2.0
%% with Runtime Library Exception.
%%
%% See https://cangjie-lang.cn/pages/LICENSE for license information.

flowchart TD
    CHIR --> 前端
    jbc[Java 字节码] --> 前端
    subgraph 汇编器
    direction TD
    CBC
    aarch64
    x86_64
    end
    subgraph 编译器
    前端 --> 优化器 --> 后端
    end
    后端 --> 汇编器
