/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.
 * This source file is part of the Cangjie project, licensed under Apache-2.0
 * with Runtime Library Exception.
 *
 * See https://cangjie-lang.cn/pages/LICENSE for license information.
 */

package com.huawei.excelsior.jet.compiler.opt.middle.transformations.xi

import com.huawei.excelsior.jet.compiler.opt.ir.Universe
import com.huawei.excelsior.jet.compiler.opt.middle.transformations.LoopsNormalizer
import com.huawei.excelsior.jet.compiler.options.BoolOption._
import com.huawei.excelsior.jet.compiler.options.NumOption._
import com.huawei.excelsior.jet.util.ScalaCollections
import com.huawei.excelsior.jet.util.graph.Loop

import scala.PartialFunction.condOpt

trait CangjieLoopOptimization extends XiTransform with LoopsNormalizer { self: Universe =>

  /** Simplifies convoluted for-in loop pattern in Cangjie to a normal do-while loop.
    *
    * The following construct:
    * {{{
    *   for (i in 0..n) {
    *     ...
    *   }
    * }}}
    * is generated by Cangjie frontend as:
    * {{{
    *   var i = 0
    *   var first = true
    *   while (i < n) {
    *     if (first) {
    *       first = false
    *     } else {
    *       i++
    *     }
    *     ...
    *   }
    * }}}
    *
    * This pattern can be simplified to a plain do-while loop by "partial peeling"
    * via [[XiScheduler.extract extraction]] of loop enter edge with the 2-block crossroad that corresponds to
    * {{{
    *   while (i < n) {
    *     if (first) {
    * }}}
    *
    * The following transformation takes place (copied nodes are enclosed in square brackets):
    * {{{
    *                IN    _______                    IN                    _________                  IN
    *                 |   /       |                    |                   /         |                  |
    *        p: phi(True,q)       |         [p]: phi(True)          p: phi(q)        |           [If(i < n)]
    *           If(i < n)         |             [If(i < n)]          If(i < n)       |             F/    \T   __________
    *            F/    \T         |               F/    \T            F/    \T       |             /      \  /          |
    *            /      \         |               /      \            /      \       |           OUT      BODY          |
    *          OUT     If(p)      |  ----->     OUT  [If([p])]       OUT    If(p)    |  ----->              \           |
    *                F/    \T     |                   F/    \T            F/    \T   |                    If(i < n)     |
    *                 \    /      |                    \    /              \    /    |                     F/    \T     |
    *          q: phi(p,False)    |                     q: phi([p],False,p,False)    |                     /      \_____|
    *                  BODY       |                               BODY               |                   OUT
    *                   |_________|                                |_________________|
    * }}}
    */
  def simplifyCangjieForInLoops(): Boolean = {
    if (!XiTransform.enabled(ForInLoopOptimization)) {
      return false
    }

    /** Matches following CFG loop pattern:
      * {{{
      *             IN   ___________
      *              |  /           |
      *       p: phi(c,q) <------------- header
      *             /   \           |
      *          ...     \          |
      *                 If(p) <--------- crossroad
      *                F/  \T       |
      *                 \  /        |
      *          q: phi(p,d) <---------- body
      *                  |__________|
      * }}}
      * where `c` and `d` are compile-time boolean constants (`True` or `False`) and `c != d`.
      *
      * Returns loop enter edge `(IN -> header)`.
      */
    object Candidate {
      def unapply(crossroad: If): Option[Edge] = {
        val crossroadBlock = crossroad.block
        val loop = cfg.loops.loopOf(crossroadBlock)

        // Crossroad with single predecessor block (header) and single successor block (body)
        (ScalaCollections.singleton(crossroadBlock.predBlocks), ScalaCollections.uniqueValue(crossroad.succBlocks)) match {
          case (Some(header), Some(body))
            // Without spinal nodes (including header)
            if header.spine.isEmpty && crossroadBlock.spine.isEmpty &&
              // Inside of a normalized loop where predecessor block is the header
              loop != null && loop.header == header && isNormalizedLoop(loop) &&
              // TODO: investigate performance degradation from enabling this (JET-13298)
              loop.exits.size <= env.valueOf(ForInLoopOptimizationExitLimit) =>

            // Selector is boolean phi in header with `True` or `False` constant as its starting value
            crossroad.selector match {
              case Phi(`header`, ConstCondition(c), q: Phi)
                // And another phi located in body
                if body == q.block =>

                // With the opposite value coming from corresponding constant crossroad exit
                q.phiArg(crossroad.exit(c).outEdge) match {
                  case ConstCondition(d) if c != d =>
                    val (enterEdge, _) = normalizedLoopHeaderEdges(loop)
                    Some(enterEdge)

                  case _ => None
                }
              case _ => None
            }
          case _ => None
        }
      }
    }

    val candidates = all[If] collect { case crossroad @ Candidate(enterEdge) => (crossroad, enterEdge) }
    if (candidates.isEmpty) {
      return false
    }

    xiTransform { scheduler =>
      for ((crossroad, enterEdge @ ControlEdge(_, header: Block)) <- candidates) {
        scheduler.extract(header, enterEdge)
        scheduler.extract(crossroad.block)
      }
    }

    true
  }

  /** Simplifies residual loop left after [[simplifyCangjieForInLoops]] transformation and further optimizations.
    *
    * Some for-in patterns in Cangjie after optimizations end up with a residual loop
    * with "boolean" inductive variable `p` instead of a proper integral one `i`:
    * {{{
    *                IN    _______
    *                 |   /       |
    *        p: phi(True,cmp)     |
    *     cmp: Cmp[NE](i, last)   |
    *              If(p)          |
    *            F/    \T         |
    *            /      \         |
    *          OUT      BODY      |
    *                     \_______|
    * }}}
    *
    * This residual loop can be simplified to a normal do-while loop with integral inductive variable
    * by performing "partial peeling" via [[XiScheduler.extract extraction]] of loop enter edge with loop header.
    *
    * The following transformation takes place (copied nodes are enclosed in square brackets):
    * {{{
    *                IN    _______                 IN
    *                 |   /       |                 |
    *        p: phi(True,cmp)     |            [If(True)]
    *     cmp: Cmp[NE](i, last)   |             F/    \T   ____________
    *              If(p)          |  ----->     /      \  /            |
    *            F/    \T         |           OUT      BODY            |
    *            /      \         |                      \             |
    *          OUT      BODY      |           cmp: Cmp[NE](i, last)    |
    *                     \_______|                   If(cmp)          |
    *                                                 F/    \T         |
    *                                                 /      \_________|
    *                                               OUT
    * }}}
    */
  def simplifyResidualCangjieForInLoops(): Boolean = {
    if (!XiTransform.enabled(ResidualForInLoopOptimization)) {
      return false
    }

    /** Matches residual loop pattern described above. */
    object ResidualLoop {
      def unapply(loop: Loop[Block]) = {
        val header = loop.header
        // Normalized loop with exit branch located in the header without side effects
        if (isNormalizedLoop(loop) && loop.exits(header) && header.spine.forall(SpinalNode.sideEffectFree)) {
          condOpt(header.blockEnd) {
            // That branch has boolean phi function as its selector with a Cmp value coming from backward edge
            case branch @ If(phi @ Phi(`header`, _, cmp: Cmp))
              // And the only use of that phi being the branch itself
              if (ScalaCollections.singleton(phi.valueUses) contains branch) &&
                // And the only use of Cmp being the phi function
                (ScalaCollections.singleton(cmp.valueUses) contains phi) => cmp
          }
        } else {
          None
        }
      }
    }

    val candidates = cfg.loops.iterator collect { case loop @ ResidualLoop(cmp) => (loop, cmp) }
    if (candidates.isEmpty) {
      return false
    }

    // Needed for correct var placement below.
    splitCriticalEdges()

    withIncrementalGCM {
      xiTransform { scheduler =>
        for ((loop, cmp) <- candidates) {

          val header = loop.header
          val (enterEdge, backwardEdge) = normalizedLoopHeaderEdges(loop)

          // Backward block is guaranteed to be present and not equal to header because of split critical edges above.
          val backwardBlock = backwardEdge.source.block
          assert(backwardBlock != header)

          val cmpPoint = upperPoint(cmp)
          if (cmpPoint.block == header) {
            // Cmp may be generated at backward branch, but it floats to header and would be copied together with it,
            // thus recreating boolean phi after SSA completion.
            // By replacing Cmp args with vars, we can "move" Cmp to the backward block and prevent its copying.
            val backwardBranch = backwardBlock.blockEnd
            for (e <- cmp.inEdges) {
              val arg = e.source
              withNewVar(arg.tpe) { (assignAt, readAt) =>
                assignAt(cmpPoint, arg)
                e.source = readAt(backwardBranch.inCtrl)
              }
            }
          }

          scheduler.extract(header, enterEdge)
        }
      }
    }

    true
  }
}
