/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.
 * This source file is part of the Cangjie project, licensed under Apache-2.0
 * with Runtime Library Exception.
 *
 * See https://cangjie-lang.cn/pages/LICENSE for license information.
 */

package com.huawei.excelsior.jet.compiler.opt.jprof.blame.representation

import xscala.io.TextInput
import xscala.matching.Regex
import xscala.util.StringOps.{r, toHexOption}

import scala.collection.mutable
import scala.util.{Try, Using}

/** Low-level parsing of `*.mreg` file, which is generated by opt if `-MarkedRegionsStat=f` is set
  * to preserve additional info about Marked Regions.
  *
  * @author haitaka
  * @author ijorch
  */
object MReg {
  // TODO: consider enhancing .mreg format to allow `representation.Method` here instead of plain `String`
  case class Region(method: String, id: Int)

  object IntStr {
    def unapply(s: String) = s.toIntOption
  }
  object HexInt {
    def unapply(s: String) = s.toHexOption
  }

  def parseSizes(sizesFilename: String) = {
    val codeUnitEntry: Regex = raw"code unit (\S+)".r
    val regionEntry: Regex = raw"- region (\d+) \[0x([0-9a-fA-F]+), 0x([0-9a-fA-F]+)\)".r

    val sizes = mutable.Map.empty[Region, Long]
    Using.resource(TextInput.fromFile(sizesFilename)) { file =>
      var lastMethod: String = null
      for (line <- file.getLines()) {
        val at = line indexOf " @ " // block ids are written after `@` sign
        val cropped = if (at != -1) line take at else line
        cropped match {
          case codeUnitEntry(method) =>
            lastMethod = method
          case regionEntry(IntStr(id), HexInt(start), HexInt(end)) =>
            assert(lastMethod != null);
            val reg = Region(lastMethod, id)
            val oldSize = sizes.getOrElse(reg, 0L)
            sizes(reg) = oldSize + end - start - 1
          case "" =>
          case _ =>
            throw new AssertionError(s"Unexpected line: $line")
        }
      }
    }
    sizes.toMap
  }

}
