/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.
 * This source file is part of the Cangjie project, licensed under Apache-2.0
 * with Runtime Library Exception.
 *
 * See https://cangjie-lang.cn/pages/LICENSE for license information.
 */

package com.huawei.excelsior.jet.compiler.lambda

import com.huawei.excelsior.common.Language.JAVA
import com.huawei.excelsior.jet.compiler.Env
import xscala.util.StringOps.asciiIsDecimal
import com.huawei.excelsior.jet.compiler.symlevel.{ClassType, Type}

/** We make class names for lambda classes stable via identifying them by corresponding InvokeDynamic constant pool
  * entry. There is one-to-one correspondence between InvokeDynamic constant pool entry and lambda class.
  * The naming policy also should be synchronized with lambda class naming in [[java.lang.invoke.LambdaMetafactory]].
  *
  * In language packs that doesn't support Java, we make names for lambda classes stable by given them sequential number of
  * corresponding InvokeDynamic constant pool entry.
  *
  * @author kit
  */
object LambdaClassNaming {
  private val LAMBDA_CLASS_NAME_INFIX = "$$Lambda$"

  /** Provides stable number postfix for lambda classes.
    *
    * Such numbering can be different in different language packs:
    *
    * - In Java LP number of lambda class is the number of corresponding InvokeDynamic entry of classfile constant pool.
    *
    *   This numbering is chosen to synchronize lambda class naming with [[java.lang.invoke.LambdaMetafactory]].
    *
    *   Example:
    *   {{{
    *     #0 = UTF8
    *     ...
    *     #42 = InvokeDynamic   -> given number is 42
    *     ...
    *     #2049 = InvokeDynamic -> given number is 2049
    *     ... and so on
    *   }}}
    *
    * - If language pack doesn't support java, then number of lambda class is sequential number of
    *   corresponding InvokeDynamic entry among all such entries in classfile constant pool.
    *
    *   This numbering is chosen because of instability constant pool entries numbering, generated by scalac,
    *   see JET-17425, JET-17444.
    *
    *   Example:
    *   {{{
    *     #0 = UTF8
    *     ... (no InvokeDynamic entries)
    *     #42 = InvokeDynamic   -> given number is 0"
    *     ... (no InvokeDynamic entries)
    *     #2049 = InvokeDynamic -> given number is 1"
    *     ... and so on
    *   }}}
    */
  private def numberingPolicy(hostClass: ClassType, cpInvokeDynamicEntry: Int): Int = {
    if Env.languagePack supports JAVA then cpInvokeDynamicEntry
    else hostClass.getClassConstantPool.getInvokeDynamicEntryNumber(cpInvokeDynamicEntry)
  }

  /** Returns class name for lambda. */
  def getLambdaClassName(hostClass: ClassType, cpInvokeDynamicEntry: Int) =
    hostClass.getName.replace('.', '/') + LAMBDA_CLASS_NAME_INFIX + numberingPolicy(hostClass, cpInvokeDynamicEntry)

  /** Returns name of host class of given lambda class. */
  def getLambdaClassHostName(lambdaClassName: String) = {
    val infixStart = lambdaClassName.lastIndexOf(LAMBDA_CLASS_NAME_INFIX)
    val cpideStart = infixStart + LAMBDA_CLASS_NAME_INFIX.length

    assert((infixStart > 0) /* infix is found */ &&
           (cpideStart < lambdaClassName.length) /* there is at least one symbol after it */ &&
           lambdaClassName.substring(cpideStart).forall(_.asciiIsDecimal),
           s"$lambdaClassName should be of form returned by `getLambdaClassName`.")

    lambdaClassName.substring(0, infixStart)
  }
}
