
interface I {
  func foo(
    x0: Byte,
    x1: Byte,
    x2: Byte,
    x3: Byte,
    x4: Byte,
    x5: Byte,
    x6: Byte,
    x7: Byte,
    x8: Byte,
    x9: Byte,
    x10: Byte,
    x11: Byte,
    x12: Byte,
    x13: Byte,
    x14: Byte,
    x15: Byte,
    x16: Byte,
    x17: Byte,
    x18: Byte,
    x19: Byte,
    x20: Byte,
    x21: Byte,
    x22: Byte,
    x23: Byte,
    x24: Byte,
    x25: Byte,
    x26: Byte,
    x27: Byte,
    x28: Byte,
    x29: Byte,
    x30: Byte,
    x31: Byte,
    x32: Byte,
    x33: Byte,
    x34: Byte,
    x35: Byte,
    x36: Byte,
    x37: Byte,
    x38: Byte,
    x39: Byte,
    x40: Byte,
    x41: Byte,
    x42: Byte,
    x43: Byte,
    x44: Byte,
    x45: Byte,
    x46: Byte,
    x47: Byte,
    x48: Byte,
    x49: Byte,
    x50: Byte,
    x51: Byte,
    x52: Byte,
    x53: Byte,
    x54: Byte,
    x55: Byte,
    x56: Byte,
    x57: Byte,
    x58: Byte,
    x59: Byte,
    x60: Byte,
    x61: Byte,
    x62: Byte,
    x63: Byte,
    x64: Byte,
    x65: Byte,
    x66: Byte,
    x67: Byte,
    x68: Byte,
    x69: Byte,
    x70: Byte,
    x71: Byte,
    x72: Byte,
    x73: Byte,
    x74: Byte,
    x75: Byte,
    x76: Byte,
    x77: Byte,
    x78: Byte,
    x79: Byte,
    x80: Byte,
    x81: Byte,
    x82: Byte,
    x83: Byte,
    x84: Byte,
    x85: Byte,
    x86: Byte,
    x87: Byte,
    x88: Byte,
    x89: Byte,
    x90: Byte,
    x91: Byte,
    x92: Byte,
    x93: Byte,
    x94: Byte,
    x95: Byte,
    x96: Byte,
    x97: Byte,
    x98: Byte,
    x99: Byte,
    x100: Byte,
    x101: Byte,
    x102: Byte,
    x103: Byte,
    x104: Byte,
    x105: Byte,
    x106: Byte,
    x107: Byte,
    x108: Byte,
    x109: Byte,
    x110: Byte,
    x111: Byte,
    x112: Byte,
    x113: Byte,
    x114: Byte,
    x115: Byte,
    x116: Byte,
    x117: Byte,
    x118: Byte,
    x119: Byte,
    x120: Byte
  ): Int32 { 0 }
}
public class Foo <: I {
  public func foo(
      x0: Byte,
      x1: Byte,
      x2: Byte,
      x3: Byte,
      x4: Byte,
      x5: Byte,
      x6: Byte,
      x7: Byte,
      x8: Byte,
      x9: Byte,
      x10: Byte,
      x11: Byte,
      x12: Byte,
      x13: Byte,
      x14: Byte,
      x15: Byte,
      x16: Byte,
      x17: Byte,
      x18: Byte,
      x19: Byte,
      x20: Byte,
      x21: Byte,
      x22: Byte,
      x23: Byte,
      x24: Byte,
      x25: Byte,
      x26: Byte,
      x27: Byte,
      x28: Byte,
      x29: Byte,
      x30: Byte,
      x31: Byte,
      x32: Byte,
      x33: Byte,
      x34: Byte,
      x35: Byte,
      x36: Byte,
      x37: Byte,
      x38: Byte,
      x39: Byte,
      x40: Byte,
      x41: Byte,
      x42: Byte,
      x43: Byte,
      x44: Byte,
      x45: Byte,
      x46: Byte,
      x47: Byte,
      x48: Byte,
      x49: Byte,
      x50: Byte,
      x51: Byte,
      x52: Byte,
      x53: Byte,
      x54: Byte,
      x55: Byte,
      x56: Byte,
      x57: Byte,
      x58: Byte,
      x59: Byte,
      x60: Byte,
      x61: Byte,
      x62: Byte,
      x63: Byte,
      x64: Byte,
      x65: Byte,
      x66: Byte,
      x67: Byte,
      x68: Byte,
      x69: Byte,
      x70: Byte,
      x71: Byte,
      x72: Byte,
      x73: Byte,
      x74: Byte,
      x75: Byte,
      x76: Byte,
      x77: Byte,
      x78: Byte,
      x79: Byte,
      x80: Byte,
      x81: Byte,
      x82: Byte,
      x83: Byte,
      x84: Byte,
      x85: Byte,
      x86: Byte,
      x87: Byte,
      x88: Byte,
      x89: Byte,
      x90: Byte,
      x91: Byte,
      x92: Byte,
      x93: Byte,
      x94: Byte,
      x95: Byte,
      x96: Byte,
      x97: Byte,
      x98: Byte,
      x99: Byte,
      x100: Byte,
      x101: Byte,
      x102: Byte,
      x103: Byte,
      x104: Byte,
      x105: Byte,
      x106: Byte,
      x107: Byte,
      x108: Byte,
      x109: Byte,
      x110: Byte,
      x111: Byte,
      x112: Byte,
      x113: Byte,
      x114: Byte,
      x115: Byte,
      x116: Byte,
      x117: Byte,
      x118: Byte,
      x119: Byte,
      x120: Byte
  ): Int32 {
    println("${x0}")
    println("${x1}")
    println("${x2}")
    println("${x3}")
    println("${x4}")
    println("${x5}")
    println("${x6}")
    println("${x7}")
    println("${x8}")
    println("${x9}")
    println("${x10}")
    println("${x11}")
    println("${x12}")
    println("${x13}")
    println("${x14}")
    println("${x15}")
    println("${x16}")
    println("${x17}")
    println("${x18}")
    println("${x19}")
    println("${x20}")
    println("${x21}")
    println("${x22}")
    println("${x23}")
    println("${x24}")
    println("${x25}")
    println("${x26}")
    println("${x27}")
    println("${x28}")
    println("${x29}")
    println("${x30}")
    println("${x31}")
    println("${x32}")
    println("${x33}")
    println("${x34}")
    println("${x35}")
    println("${x36}")
    println("${x37}")
    println("${x38}")
    println("${x39}")
    println("${x40}")
    println("${x41}")
    println("${x42}")
    println("${x43}")
    println("${x44}")
    println("${x45}")
    println("${x46}")
    println("${x47}")
    println("${x48}")
    println("${x49}")
    println("${x50}")
    println("${x51}")
    println("${x52}")
    println("${x53}")
    println("${x54}")
    println("${x55}")
    println("${x56}")
    println("${x57}")
    println("${x58}")
    println("${x59}")
    println("${x60}")
    println("${x61}")
    println("${x62}")
    println("${x63}")
    println("${x64}")
    println("${x65}")
    println("${x66}")
    println("${x67}")
    println("${x68}")
    println("${x69}")
    println("${x70}")
    println("${x71}")
    println("${x72}")
    println("${x73}")
    println("${x74}")
    println("${x75}")
    println("${x76}")
    println("${x77}")
    println("${x78}")
    println("${x79}")
    println("${x80}")
    println("${x81}")
    println("${x82}")
    println("${x83}")
    println("${x84}")
    println("${x85}")
    println("${x86}")
    println("${x87}")
    println("${x88}")
    println("${x89}")
    println("${x90}")
    println("${x91}")
    println("${x92}")
    println("${x93}")
    println("${x94}")
    println("${x95}")
    println("${x96}")
    println("${x97}")
    println("${x98}")
    println("${x99}")
    println("${x100}")
    println("${x101}")
    println("${x102}")
    println("${x103}")
    println("${x104}")
    println("${x105}")
    println("${x106}")
    println("${x107}")
    println("${x108}")
    println("${x109}")
    println("${x110}")
    println("${x111}")
    println("${x112}")
    println("${x113}")
    println("${x114}")
    println("${x115}")
    println("${x116}")
    println("${x117}")
    println("${x118}")
    println("${x119}")
    println("${x120}")
    0
  }
}

var i: I = Foo()

main() {
  i.foo(
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    27,
    28,
    29,
    30,
    31,
    32,
    33,
    34,
    35,
    36,
    37,
    38,
    39,
    40,
    41,
    42,
    43,
    44,
    45,
    46,
    47,
    48,
    49,
    50,
    51,
    52,
    53,
    54,
    55,
    56,
    57,
    58,
    59,
    60,
    61,
    62,
    63,
    64,
    65,
    66,
    67,
    68,
    69,
    70,
    71,
    72,
    73,
    74,
    75,
    76,
    77,
    78,
    79,
    80,
    81,
    82,
    83,
    84,
    85,
    86,
    87,
    88,
    89,
    90,
    91,
    92,
    93,
    94,
    95,
    96,
    97,
    98,
    99,
    100,
    101,
    102,
    103,
    104,
    105,
    106,
    107,
    108,
    109,
    110,
    111,
    112,
    113,
    114,
    115,
    116,
    117,
    118,
    119,
    120,
  )
}
